// Arc.cpp : 実装ファイル
//

#include "stdafx.h"
#include "ogg.h"
#include "Arc.h"


// CArc ダイアログ






IMPLEMENT_DYNAMIC(CArc, CCustomDialog)

CArc::CArc(CWnd* pParent /*=NULL*/)
	: CCustomDialog(CArc::IDD, pParent)
{

}

CArc::~CArc()
{
}

void CArc::DoDataExchange(CDataExchange* pDX)
{
	CCustomDialog::DoDataExchange(pDX);
	DDX_Control(pDX, IDC_LIST1, m_list);
	DDX_Control(pDX, IDOK, m_okdummy);
}

#include "CImageBase.h"
BEGIN_MESSAGE_MAP(CArc, CCustomDialog)
	ON_LBN_DBLCLK(IDC_LIST1, OnDblclkList1)
	ON_WM_PAINT()
	ON_BN_CLICKED(IDOK, &CArc::OnBnClickedOk)
	cmn(CArc);


// CArc メッセージ ハンドラ
extern CString fnn;

TCHAR tiarc[][128] = {
L"★OPEN YOUR EYES",
L"02 罪の子らの賛美歌",
L"03 大陸遠望",
L"04 勝利！",
L"05 予期せぬ終結",
L"06 つかの間の休息",
L"07 眠れない夜は",
L"08 ENCOUNTER BATTLE",
L"09 戦闘＃2",
L"10 聖堂",
L"11 フィールド＃1",
L"12 舞踏会",
L"13 トランクォーリー",
L"14 緊迫",
L"15 ラグニ村",
L"16 出発の日",
L"17 大海原へ",
L"18 港町タイニ",
L"19 悪だくみ",
L"20 さぁ、特訓だ！",
L"21 闇の足音-予兆-",
L"22 国境都市マルテュニ",
L"23 共和国首都ドーム",
L"24 差し迫る危機",
L"25 急げ！",
L"26 ふたりで…",
L"27 フィールド＃2",
L"28 いつもの朝",
L"29 港町アンスヴェルス",
L"30 サルディス湾",
L"31 聖都バアラ",
L"32 エリザベス・エンジン",

L"33 なつかしい景色",
L"34 ダンジョン＃1",
L"35 オカリナ",
L"36 EVERLASTING NIGHTMARE",
L"37 ラグニ村　another version",
L"38 BURST INTO THE BATTLE",
L"39 フィールド＃3",
L"40 荒廃の影",
L"41 分かたれた道",
L"42 神との決別",
L"43 対決",
L"44 フィールド＃4",
L"45 プリセロナのテーマ",
L"46 DESTRUCTION",
L"47 エステニュ・チョダル",
L"48 不吉",
L"49 セテバン研究地区",
L"50 DESERTED TOWN",
L"51 祈り",
L"52 変わりゆく世界",
L"53 ラクリモサ渓谷",
L"54 ESPIONAGE",
L"55 エルハイヴ要塞",
L"56 降臨",
L"57 戦闘＃4",
L"58 フィールド＃5",
L"59 ゲルナ高原",

L"60 幻夢",
L"61 BREAKTHROUGH",
L"62 エペソ",
L"63 あるマギの記憶",
L"64 審判の時",
L"65 MBRACE",
L"66 戦闘＃5",
L"67 FINAL ASSAULT",
L"68 フィールド＃5",
L"69 凍てついた過去",
L"70 FALL OF THE EMPIRE",
L"71 コンステルラリウム",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 旅の想い出",
L"75 鎮魂歌",
L"76 迫りくる脅威",
L"77 CASTLE WALKENSWAARD",
L"78 礼拝堂～アケナトン～",
L"79 ダンジョン＃2",
L"80 ダンジョン＃3",
L"81 エピローグ",
L"82 Truth In Me",

L"84 幻夢"
};

TCHAR tiarc_en[][128] = {
L"★OPEN YOUR EYES",
L"02 Hymn of the Children of Sin",
L"03 Continental Vista",
L"04 Victory!",
L"05 Unexpected Conclusion",
L"06 Brief Rest",
L"07 Sleepless Night",
L"08 ENCOUNTER BATTLE",
L"09 Battle #2",
L"10 Sanctuary",
L"11 Field #1",
L"12 Ball",
L"13 Tranquility",
L"14 Tension",
L"15 Lagni Village",
L"16 Day of Departure",
L"17 To the Open Sea",
L"18 Port Town Tiny",
L"19 Evil Scheme",
L"20 Time for Training!",
L"21 Footsteps in the Dark-Omen-",
L"22 Border City Martuni",
L"23 Republic Capital Dome",
L"24 Impending Crisis",
L"25 Hurry!",
L"26 The Two of Us...",
L"27 Field #2",
L"28 Usual Morning",
L"29 Port Town Ansverth",
L"30 Gulf of Sardis",
L"31 Holy City Baal",
L"32 Elizabeth Engine",
L"33 Nostalgic Scenery",
L"34 Dungeon #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Lagni Village another version",
L"38 BURST INTO THE BATTLE",
L"39 Field #3",
L"40 Shadow of Devastation",
L"41 Fork in the Road",
L"42 Parting with God",
L"43 Showdown",
L"44 Field #4",
L"45 Priscillona's Theme",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominous",
L"49 Seteban Research District",
L"50 DESERTED TOWN",
L"51 Prayer",
L"52 Changing World",
L"53 Lacrimosa Valley",
L"54 ESPIONAGE",
L"55 Erheiv Fortress",
L"56 Descent",
L"57 Battle #4",
L"58 Field #5",
L"59 Gelna Plateau",
L"60 Phantasm",
L"61 BREAKTHROUGH",
L"62 Ephesus",
L"63 A Magi's Memory",
L"64 Hour of Judgment",
L"65 MBRACE",
L"66 Battle #5",
L"67 FINAL ASSAULT",
L"68 Field #5",
L"69 Frozen Past",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Memories of the Journey",
L"75 Requiem",
L"76 Approaching Threat",
L"77 CASTLE WALKENSWAARD",
L"78 Chapel~Akhenaten~",
L"79 Dungeon #2",
L"80 Dungeon #3",
L"81 Epilogue",
L"82 Truth In Me",
L"84 Phantasm"
};

TCHAR tiarc_fr[][128] = {
L"★OPEN YOUR EYES",
L"02 Hymne des Enfants du Péché",
L"03 Vue Continentale",
L"04 Victoire!",
L"05 Conclusion Inattendue",
L"06 Repos Bref",
L"07 Nuit Sans Sommeil",
L"08 ENCOUNTER BATTLE",
L"09 Bataille #2",
L"10 Sanctuaire",
L"11 Terrain #1",
L"12 Bal",
L"13 Tranquillité",
L"14 Tension",
L"15 Village de Lagni",
L"16 Jour du Départ",
L"17 Vers la Grande Mer",
L"18 Ville Portuaire Tiny",
L"19 Complot Maléfique",
L"20 C'est l'Heure de S'entraîner!",
L"21 Pas dans l'Obscurité-Présage-",
L"22 Ville Frontière Martuni",
L"23 Dôme de la Capitale Républicaine",
L"24 Crise Imminente",
L"25 Dépêche-toi!",
L"26 À Nous Deux...",
L"27 Terrain #2",
L"28 Matin Habituel",
L"29 Ville Portuaire Ansverth",
L"30 Golfe de Sardis",
L"31 Ville Sainte Baal",
L"32 Elizabeth Engine",
L"33 Paysage Nostalgique",
L"34 Donjon #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Village de Lagni autre version",
L"38 BURST INTO THE BATTLE",
L"39 Terrain #3",
L"40 Ombre de la Dévastation",
L"41 Carrefour",
L"42 Séparation avec Dieu",
L"43 Confrontation",
L"44 Terrain #4",
L"45 Thème de Priscillona",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominieux",
L"49 District de Recherche Seteban",
L"50 DESERTED TOWN",
L"51 Prière",
L"52 Monde en Mutation",
L"53 Vallée de Lacrimosa",
L"54 ESPIONAGE",
L"55 Forteresse d'Erheiv",
L"56 Descente",
L"57 Bataille #4",
L"58 Terrain #5",
L"59 Plateau de Gelna",
L"60 Fantasme",
L"61 BREAKTHROUGH",
L"62 Éphèse",
L"63 Mémoire d'un Mage",
L"64 Heure du Jugement",
L"65 MBRACE",
L"66 Bataille #5",
L"67 FINAL ASSAULT",
L"68 Terrain #5",
L"69 Passé Gelé",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Souvenirs du Voyage",
L"75 Requiem",
L"76 Menace Approchante",
L"77 CASTLE WALKENSWAARD",
L"78 Chapelle~Akhenaton~",
L"79 Donjon #2",
L"80 Donjon #3",
L"81 Épilogue",
L"82 Truth In Me",
L"84 Fantasme"
};

TCHAR tiarc_it[][128] = {
L"★OPEN YOUR EYES",
L"02 Inno dei Figli del Peccato",
L"03 Vista Continentale",
L"04 Vittoria!",
L"05 Conclusione Inaspettata",
L"06 Breve Riposo",
L"07 Notte Insonne",
L"08 ENCOUNTER BATTLE",
L"09 Battaglia #2",
L"10 Santuario",
L"11 Campo #1",
L"12 Ballo",
L"13 Tranquillità",
L"14 Tensione",
L"15 Villaggio di Lagni",
L"16 Giorno della Partenza",
L"17 Verso il Mare Aperto",
L"18 Città Portuale Tiny",
L"19 Piano Malvagio",
L"20 È Ora di Allenarsi!",
L"21 Passi nel Buio-Presagio-",
L"22 Città di Frontiera Martuni",
L"23 Cupola della Capitale Repubblicana",
L"24 Crisi Imminente",
L"25 Sbrigati!",
L"26 Noi Due...",
L"27 Campo #2",
L"28 Mattina Solita",
L"29 Città Portuale Ansverth",
L"30 Golfo di Sardi",
L"31 Città Santa Baal",
L"32 Elizabeth Engine",
L"33 Scenario Nostalgico",
L"34 Dungeon #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Villaggio di Lagni altra versione",
L"38 BURST INTO THE BATTLE",
L"39 Campo #3",
L"40 Ombra della Devastazione",
L"41 Bivio",
L"42 Separazione da Dio",
L"43 Scontro",
L"44 Campo #4",
L"45 Tema di Priscillona",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominoso",
L"49 Distretto di Ricerca Seteban",
L"50 DESERTED TOWN",
L"51 Preghiera",
L"52 Mondo che Cambia",
L"53 Valle di Lacrimosa",
L"54 ESPIONAGE",
L"55 Fortezza di Erheiv",
L"56 Discesa",
L"57 Battaglia #4",
L"58 Campo #5",
L"59 Altopiano di Gelna",
L"60 Fantasma",
L"61 BREAKTHROUGH",
L"62 Efeso",
L"63 Memoria di un Magi",
L"64 Ora del Giudizio",
L"65 MBRACE",
L"66 Battaglia #5",
L"67 FINAL ASSAULT",
L"68 Campo #5",
L"69 Passato Congelato",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Ricordi del Viaggio",
L"75 Requiem",
L"76 Minaccia Incombente",
L"77 CASTLE WALKENSWAARD",
L"78 Cappella~Akhenaton~",
L"79 Dungeon #2",
L"80 Dungeon #3",
L"81 Epilogo",
L"82 Truth In Me",
L"84 Fantasma"
};

TCHAR tiarc_es[][128] = {
L"★OPEN YOUR EYES",
L"02 Himno de los Hijos del Pecado",
L"03 Vista Continental",
L"04 ¡Victoria!",
L"05 Conclusión Inesperada",
L"06 Descanso Breve",
L"07 Noche en Vela",
L"08 ENCOUNTER BATTLE",
L"09 Batalla #2",
L"10 Santuario",
L"11 Campo #1",
L"12 Baile",
L"13 Tranquilidad",
L"14 Tensión",
L"15 Aldea de Lagni",
L"16 Día de Partida",
L"17 Hacia el Mar Abierto",
L"18 Puerto Tiny",
L"19 Complot Malvado",
L"20 ¡Hora de Entrenar!",
L"21 Pasos en la Oscuridad-Presagio-",
L"22 Ciudad Fronteriza Martuni",
L"23 Cúpula de la Capital Republicana",
L"24 Crisis Inminente",
L"25 ¡Apresúrate!",
L"26 Los Dos...",
L"27 Campo #2",
L"28 Mañana Habitual",
L"29 Puerto Ansverth",
L"30 Golfo de Sardis",
L"31 Ciudad Santa Baal",
L"32 Elizabeth Engine",
L"33 Paisaje Nostálgico",
L"34 Mazmorra #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Aldea de Lagni otra versión",
L"38 BURST INTO THE BATTLE",
L"39 Campo #3",
L"40 Sombra de la Devastación",
L"41 Encrucijada",
L"42 Separación de Dios",
L"43 Enfrentamiento",
L"44 Campo #4",
L"45 Tema de Priscillona",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominoso",
L"49 Distrito de Investigación Seteban",
L"50 DESERTED TOWN",
L"51 Oración",
L"52 Mundo Cambiante",
L"53 Valle Lacrimosa",
L"54 ESPIONAGE",
L"55 Fortaleza de Erheiv",
L"56 Descenso",
L"57 Batalla #4",
L"58 Campo #5",
L"59 Meseta de Gelna",
L"60 Fantasma",
L"61 BREAKTHROUGH",
L"62 Éfeso",
L"63 Memoria de un Magi",
L"64 Hora del Juicio",
L"65 MBRACE",
L"66 Batalla #5",
L"67 FINAL ASSAULT",
L"68 Campo #5",
L"69 Pasado Congelado",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Recuerdos del Viaje",
L"75 Requiem",
L"76 Amenaza Aproximante",
L"77 CASTLE WALKENSWAARD",
L"78 Capilla~Akhenaton~",
L"79 Mazmorra #2",
L"80 Mazmorra #3",
L"81 Epílogo",
L"82 Truth In Me",
L"84 Fantasma"
};

TCHAR tiarc_ko[][128] = {
L"★OPEN YOUR EYES",
L"02 죄의 자녀들의 찬미가",
L"03 대륙 원망",
L"04 승리!",
L"05 예기치 못한 결말",
L"06 잠깐의 휴식",
L"07 잠 못드는 밤",
L"08 ENCOUNTER BATTLE",
L"09 전투 #2",
L"10 성당",
L"11 필드 #1",
L"12 무도회",
L"13 트랑퀼리티",
L"14 긴박",
L"15 라그니 마을",
L"16 출발의 날",
L"17 대해원으로",
L"18 항구 마을 타이나",
L"19 악의 음모",
L"20 자, 특훈이다!",
L"21 어둠의 발소리-예조-",
L"22 국경 도시 마르투니",
L"23 공화국 수도 돔",
L"24 닥쳐오는 위기",
L"25 서둘러!",
L"26 우리 둘이…",
L"27 필드 #2",
L"28 평소 아침",
L"29 항구 마을 안스베르스",
L"30 사르디스 만",
L"31 성도 바알",
L"32 엘리자베스 엔진",
L"33 그리운 풍경",
L"34 던전 #1",
L"35 오카리나",
L"36 EVERLASTING NIGHTMARE",
L"37 라그니 마을 another version",
L"38 BURST INTO THE BATTLE",
L"39 필드 #3",
L"40 황폐의 그림자",
L"41 갈라진 길",
L"42 신과의 결별",
L"43 대결",
L"44 필드 #4",
L"45 프리실로나의 테마",
L"46 DESTRUCTION",
L"47 에스테뉴 초다르",
L"48 불길",
L"49 세테반 연구지구",
L"50 DESERTED TOWN",
L"51 기도",
L"52 변하는 세계",
L"53 라크리모사 계곡",
L"54 ESPIONAGE",
L"55 에르하이브 요새",
L"56 강림",
L"57 전투 #4",
L"58 필드 #5",
L"59 겔나 고원",
L"60 환몽",
L"61 BREAKTHROUGH",
L"62 에페소",
L"63 어느 마기의 기억",
L"64 심판의 때",
L"65 MBRACE",
L"66 전투 #5",
L"67 FINAL ASSAULT",
L"68 필드 #5",
L"69 얼어붙은 과거",
L"70 FALL OF THE EMPIRE",
L"71 콘스텔라리움",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 여행의 추억",
L"75 진혼곡",
L"76 다가오는 위협",
L"77 CASTLE WALKENSWAARD",
L"78 예배당~아케나톤~",
L"79 던전 #2",
L"80 던전 #3",
L"81 에필로그",
L"82 Truth In Me",
L"84 환몽"
};

TCHAR tiarc_zh[][128] = {
L"★OPEN YOUR EYES",
L"02 罪之子的赞歌",
L"03 大陆远望",
L"04 胜利！",
L"05 意外的终结",
L"06 短暂的休息",
L"07 不眠之夜",
L"08 ENCOUNTER BATTLE",
L"09 战斗#2",
L"10 圣堂",
L"11 原野#1",
L"12 舞会",
L"13 宁静",
L"14 紧迫",
L"15 拉格尼村",
L"16 出发之日",
L"17 驶向大海",
L"18 港町泰尼",
L"19 阴谋",
L"20 开始特训！",
L"21 暗夜脚步声-预兆-",
L"22 边境都市马尔图尼",
L"23 共和国首都穹顶",
L"24 迫近的危机",
L"25 快！",
L"26 两人一起…",
L"27 原野#2",
L"28 寻常早晨",
L"29 港町安斯韦尔斯",
L"30 萨迪斯湾",
L"31 圣都巴阿尔",
L"32 伊丽莎白引擎",
L"33 怀念的景色",
L"34 地下城#1",
L"35 陶笛",
L"36 EVERLASTING NIGHTMARE",
L"37 拉格尼村 another version",
L"38 BURST INTO THE BATTLE",
L"39 原野#3",
L"40 荒废之影",
L"41 分叉之路",
L"42 与神诀别",
L"43 对决",
L"44 原野#4",
L"45 普莉西罗娜主题曲",
L"46 DESTRUCTION",
L"47 埃斯特努科达尔",
L"48 不吉",
L"49 塞特班研究区",
L"50 DESERTED TOWN",
L"51 祈祷",
L"52 变化的世界",
L"53 拉克利莫萨峡谷",
L"54 ESPIONAGE",
L"55 埃尔海布要塞",
L"56 降临",
L"57 战斗#4",
L"58 原野#5",
L"59 格尔纳高原",
L"60 幻梦",
L"61 BREAKTHROUGH",
L"62 以弗所",
L"63 某位贤者的记忆",
L"64 审判之时",
L"65 MBRACE",
L"66 战斗#5",
L"67 FINAL ASSAULT",
L"68 原野#5",
L"69 冰冻的过去",
L"70 FALL OF THE EMPIRE",
L"71 康斯特拉利乌姆",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 旅途回忆",
L"75 镇魂歌",
L"76 迫近的威胁",
L"77 CASTLE WALKENSWAARD",
L"78 礼拜堂～阿肯那顿～",
L"79 地下城#2",
L"80 地下城#3",
L"81 尾声",
L"82 Truth In Me",
L"84 幻梦"
};

TCHAR tiarc_ar[][128] = {
L"★OPEN YOUR EYES",
L"02 ترنيمة أبناء الخطيئة",
L"03 المشهد القاري",
L"04 انتصار!",
L"05 خاتمة غير متوقعة",
L"06 راحة وجيزة",
L"07 ليلة بلا نوم",
L"08 ENCOUNTER BATTLE",
L"09 معركة #2",
L"10 الملاذ",
L"11 الحقل #1",
L"12 الحفلة",
L"13 الهدوء",
L"14 التوتر",
L"15 قرية لاغني",
L"16 يوم المغادرة",
L"17 إلى البحر المفتوح",
L"18 ميناء تايني",
L"19 المؤامرة الشريرة",
L"20 حان وقت التدريب!",
L"21 خطى في الظلام-نذير-",
L"22 مدينة الحدود مارتوني",
L"23 قبة العاصمة الجمهورية",
L"24 أزمة وشيكة",
L"25 أسرع!",
L"26 نحن الاثنان...",
L"27 الحقل #2",
L"28 الصباح المعتاد",
L"29 ميناء أنسفيرث",
L"30 خليج ساردس",
L"31 المدينة المقدسة بعل",
L"32 Elizabeth Engine",
L"33 المنظر الحنين",
L"34 السرداب #1",
L"35 الأوكارينا",
L"36 EVERLASTING NIGHTMARE",
L"37 قرية لاغني نسخة أخرى",
L"38 BURST INTO THE BATTLE",
L"39 الحقل #3",
L"40 ظل الدمار",
L"41 مفترق الطرق",
L"42 الفراق مع الله",
L"43 المواجهة",
L"44 الحقل #4",
L"45 ثيم بريسيلونا",
L"46 DESTRUCTION",
L"47 إستينو تشودار",
L"48 مشؤوم",
L"49 حي أبحاث سيتيبان",
L"50 DESERTED TOWN",
L"51 الصلاة",
L"52 العالم المتغير",
L"53 وادي لاكريموزا",
L"54 ESPIONAGE",
L"55 قلعة إرهيف",
L"56 النزول",
L"57 معركة #4",
L"58 الحقل #5",
L"59 هضبة غيلنا",
L"60 وهم",
L"61 BREAKTHROUGH",
L"62 أفسس",
L"63 ذكرى ماجي",
L"64 ساعة الحكم",
L"65 MBRACE",
L"66 معركة #5",
L"67 FINAL ASSAULT",
L"68 الحقل #5",
L"69 الماضي المتجمد",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 ذكريات الرحلة",
L"75 قداس",
L"76 التهديد القادم",
L"77 CASTLE WALKENSWAARD",
L"78 الكنيسة~أخناتون~",
L"79 السرداب #2",
L"80 السرداب #3",
L"81 الخاتمة",
L"82 Truth In Me",
L"84 وهم"
};

TCHAR tiarc_ru[][128] = {
L"★OPEN YOUR EYES",
L"02 Гимн Детей Греха",
L"03 Континентальная Панорама",
L"04 Победа!",
L"05 Неожиданный Исход",
L"06 Короткий Отдых",
L"07 Бессонная Ночь",
L"08 ENCOUNTER BATTLE",
L"09 Битва #2",
L"10 Святилище",
L"11 Поле #1",
L"12 Бал",
L"13 Безмятежность",
L"14 Напряжение",
L"15 Деревня Лагни",
L"16 День Отправления",
L"17 В Открытое Море",
L"18 Порт Тайни",
L"19 Злой Замысел",
L"20 Время Тренировок!",
L"21 Шаги в Темноте-Предзнаменование-",
L"22 Приграничный Город Мартуни",
L"23 Купол Республиканской Столицы",
L"24 Надвигающийся Кризис",
L"25 Спеши!",
L"26 Мы Двое...",
L"27 Поле #2",
L"28 Обычное Утро",
L"29 Порт Ансверт",
L"30 Залив Сардис",
L"31 Святой Город Ваал",
L"32 Elizabeth Engine",
L"33 Ностальгический Пейзаж",
L"34 Подземелье #1",
L"35 Окарина",
L"36 EVERLASTING NIGHTMARE",
L"37 Деревня Лагни другая версия",
L"38 BURST INTO THE BATTLE",
L"39 Поле #3",
L"40 Тень Разрушения",
L"41 Развилка",
L"42 Разлука с Богом",
L"43 Противостояние",
L"44 Поле #4",
L"45 Тема Присциллоны",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Зловещий",
L"49 Исследовательский Район Сетебана",
L"50 DESERTED TOWN",
L"51 Молитва",
L"52 Меняющийся Мир",
L"53 Долина Лакримозы",
L"54 ESPIONAGE",
L"55 Крепость Эрхейв",
L"56 Нисхождение",
L"57 Битва #4",
L"58 Поле #5",
L"59 Плато Гельна",
L"60 Фантом",
L"61 BREAKTHROUGH",
L"62 Эфес",
L"63 Память Мага",
L"64 Час Суда",
L"65 MBRACE",
L"66 Битва #5",
L"67 FINAL ASSAULT",
L"68 Поле #5",
L"69 Замороженное Прошлое",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Воспоминания Путешествия",
L"75 Реквием",
L"76 Приближающаяся Угроза",
L"77 CASTLE WALKENSWAARD",
L"78 Часовня~Эхнатон~",
L"79 Подземелье #2",
L"80 Подземелье #3",
L"81 Эпилог",
L"82 Truth In Me",
L"84 Фантом"
};

TCHAR tiarc_de[][128] = {
L"★OPEN YOUR EYES",
L"02 Hymne der Kinder der Sünde",
L"03 Kontinentale Aussicht",
L"04 Sieg!",
L"05 Unerwarteter Abschluss",
L"06 Kurze Rast",
L"07 Schlaflose Nacht",
L"08 ENCOUNTER BATTLE",
L"09 Schlacht #2",
L"10 Heiligtum",
L"11 Feld #1",
L"12 Ball",
L"13 Ruhe",
L"14 Spannung",
L"15 Lagni-Dorf",
L"16 Tag der Abreise",
L"17 Auf die Offene See",
L"18 Hafenstadt Tiny",
L"19 Böser Plan",
L"20 Zeit zum Trainieren!",
L"21 Schritte in der Dunkelheit-Omen-",
L"22 Grenzstadt Martuni",
L"23 Republik-Hauptstadt-Kuppel",
L"24 Bevorstehende Krise",
L"25 Beeil dich!",
L"26 Wir Zwei...",
L"27 Feld #2",
L"28 Gewöhnlicher Morgen",
L"29 Hafenstadt Ansverth",
L"30 Golf von Sardis",
L"31 Heilige Stadt Baal",
L"32 Elizabeth Engine",
L"33 Nostalgische Landschaft",
L"34 Verlies #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Lagni-Dorf andere Version",
L"38 BURST INTO THE BATTLE",
L"39 Feld #3",
L"40 Schatten der Verwüstung",
L"41 Wegscheide",
L"42 Trennung von Gott",
L"43 Showdown",
L"44 Feld #4",
L"45 Priscillonas Thema",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominös",
L"49 Seteban Forschungsbezirk",
L"50 DESERTED TOWN",
L"51 Gebet",
L"52 Sich Wandelnde Welt",
L"53 Lacrimosa-Tal",
L"54 ESPIONAGE",
L"55 Erheiv-Festung",
L"56 Abstieg",
L"57 Schlacht #4",
L"58 Feld #5",
L"59 Gelna-Hochebene",
L"60 Phantasma",
L"61 BREAKTHROUGH",
L"62 Ephesus",
L"63 Erinnerung eines Magi",
L"64 Stunde des Gerichts",
L"65 MBRACE",
L"66 Schlacht #5",
L"67 FINAL ASSAULT",
L"68 Feld #5",
L"69 Gefrorene Vergangenheit",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Erinnerungen der Reise",
L"75 Requiem",
L"76 Herannahende Bedrohung",
L"77 CASTLE WALKENSWAARD",
L"78 Kapelle~Echnaton~",
L"79 Verlies #2",
L"80 Verlies #3",
L"81 Epilog",
L"82 Truth In Me",
L"84 Phantasma"
};

TCHAR tiarc_pt[][128] = {
L"★OPEN YOUR EYES",
L"02 Hino dos Filhos do Pecado",
L"03 Vista Continental",
L"04 Vitória!",
L"05 Conclusão Inesperada",
L"06 Breve Descanso",
L"07 Noite em Claro",
L"08 ENCOUNTER BATTLE",
L"09 Batalha #2",
L"10 Santuário",
L"11 Campo #1",
L"12 Baile",
L"13 Tranquilidade",
L"14 Tensão",
L"15 Vila de Lagni",
L"16 Dia da Partida",
L"17 Para o Mar Aberto",
L"18 Porto Tiny",
L"19 Trama Maligna",
L"20 Hora de Treinar!",
L"21 Passos na Escuridão-Presságio-",
L"22 Cidade Fronteiriça Martuni",
L"23 Cúpula da Capital Republicana",
L"24 Crise Iminente",
L"25 Apressa-te!",
L"26 Nós Dois...",
L"27 Campo #2",
L"28 Manhã Habitual",
L"29 Porto Ansverth",
L"30 Golfo de Sardis",
L"31 Cidade Santa Baal",
L"32 Elizabeth Engine",
L"33 Cenário Nostálgico",
L"34 Masmorra #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Vila de Lagni outra versão",
L"38 BURST INTO THE BATTLE",
L"39 Campo #3",
L"40 Sombra da Devastação",
L"41 Encruzilhada",
L"42 Separação de Deus",
L"43 Confronto",
L"44 Campo #4",
L"45 Tema de Priscillona",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominoso",
L"49 Distrito de Pesquisa Seteban",
L"50 DESERTED TOWN",
L"51 Oração",
L"52 Mundo em Mutação",
L"53 Vale Lacrimosa",
L"54 ESPIONAGE",
L"55 Fortaleza Erheiv",
L"56 Descida",
L"57 Batalha #4",
L"58 Campo #5",
L"59 Planalto de Gelna",
L"60 Fantasma",
L"61 BREAKTHROUGH",
L"62 Éfeso",
L"63 Memória de um Magi",
L"64 Hora do Julgamento",
L"65 MBRACE",
L"66 Batalha #5",
L"67 FINAL ASSAULT",
L"68 Campo #5",
L"69 Passado Congelado",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Memórias da Jornada",
L"75 Requiem",
L"76 Ameaça Aproximante",
L"77 CASTLE WALKENSWAARD",
L"78 Capela~Aquenáton~",
L"79 Masmorra #2",
L"80 Masmorra #3",
L"81 Epílogo",
L"82 Truth In Me",
L"84 Fantasma"
};

TCHAR tiarc_nl[][128] = {
L"★OPEN YOUR EYES",
L"02 Hymne van de Kinderen der Zonde",
L"03 Continentale Uitzicht",
L"04 Overwinning!",
L"05 Onverwachte Conclusie",
L"06 Korte Rust",
L"07 Slapeloze Nacht",
L"08 ENCOUNTER BATTLE",
L"09 Slag #2",
L"10 Heiligdom",
L"11 Veld #1",
L"12 Bal",
L"13 Rust",
L"14 Spanning",
L"15 Lagni Dorp",
L"16 Vertrekdag",
L"17 Naar de Open Zee",
L"18 Havenstad Tiny",
L"19 Kwaad Beraamsel",
L"20 Tijd om te Trainen!",
L"21 Stappen in het Duister-Voorbode-",
L"22 Grensstad Martuni",
L"23 Republiek Hoofdstad Koepel",
L"24 Naderende Crisis",
L"25 Haast Je!",
L"26 Wij Twee...",
L"27 Veld #2",
L"28 Gewone Ochtend",
L"29 Havenstad Ansverth",
L"30 Golf van Sardis",
L"31 Heilige Stad Baal",
L"32 Elizabeth Engine",
L"33 Nostalgisch Landschap",
L"34 Kerker #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Lagni Dorp andere versie",
L"38 BURST INTO THE BATTLE",
L"39 Veld #3",
L"40 Schaduw van Verwoesting",
L"41 Kruispunt",
L"42 Scheiding van God",
L"43 Confrontatie",
L"44 Veld #4",
L"45 Priscillona's Thema",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Onheilspellend",
L"49 Seteban Onderzoeksdistrict",
L"50 DESERTED TOWN",
L"51 Gebed",
L"52 Veranderende Wereld",
L"53 Lacrimosa Vallei",
L"54 ESPIONAGE",
L"55 Erheiv Vesting",
L"56 Afdaling",
L"57 Slag #4",
L"58 Veld #5",
L"59 Gelna Plateau",
L"60 Fantoom",
L"61 BREAKTHROUGH",
L"62 Efeze",
L"63 Herinnering van een Magi",
L"64 Uur des Oordeels",
L"65 MBRACE",
L"66 Slag #5",
L"67 FINAL ASSAULT",
L"68 Veld #5",
L"69 Bevroren Verleden",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Herinneringen van de Reis",
L"75 Requiem",
L"76 Naderende Dreiging",
L"77 CASTLE WALKENSWAARD",
L"78 Kapel~Achnaton~",
L"79 Kerker #2",
L"80 Kerker #3",
L"81 Epiloog",
L"82 Truth In Me",
L"84 Fantoom"
};

TCHAR tiarc_pl[][128] = {
L"★OPEN YOUR EYES",
L"02 Hymn Dzieci Grzechu",
L"03 Widok Kontynentalny",
L"04 Zwycięstwo!",
L"05 Nieoczekiwane Zakończenie",
L"06 Krótki Odpoczynek",
L"07 Noc bez Snu",
L"08 ENCOUNTER BATTLE",
L"09 Bitwa #2",
L"10 Sanktuarium",
L"11 Pole #1",
L"12 Bal",
L"13 Spokój",
L"14 Napięcie",
L"15 Wieś Lagni",
L"16 Dzień Odjazdu",
L"17 Na Otwarte Morze",
L"18 Port Tiny",
L"19 Zły Spisek",
L"20 Czas na Trening!",
L"21 Kroki w Ciemności-Omen-",
L"22 Miasto Graniczne Martuni",
L"23 Kopuła Stolicy Republiki",
L"24 Zbliżający się Kryzys",
L"25 Pospiesz się!",
L"26 My Dwoje...",
L"27 Pole #2",
L"28 Zwykły Ranek",
L"29 Port Ansverth",
L"30 Zatoka Sardis",
L"31 Święte Miasto Baal",
L"32 Elizabeth Engine",
L"33 Nostalgiczny Krajobraz",
L"34 Loch #1",
L"35 Okaryna",
L"36 EVERLASTING NIGHTMARE",
L"37 Wieś Lagni inna wersja",
L"38 BURST INTO THE BATTLE",
L"39 Pole #3",
L"40 Cień Dewastacji",
L"41 Rozdroże",
L"42 Rozstanie z Bogiem",
L"43 Konfrontacja",
L"44 Pole #4",
L"45 Motyw Priscillonii",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Ominiczny",
L"49 Dzielnica Badawcza Setebana",
L"50 DESERTED TOWN",
L"51 Modlitwa",
L"52 Zmieniający się Świat",
L"53 Dolina Lacrimosa",
L"54 ESPIONAGE",
L"55 Twierdza Erheiv",
L"56 Zejście",
L"57 Bitwa #4",
L"58 Pole #5",
L"59 Płaskowyż Gelna",
L"60 Fantom",
L"61 BREAKTHROUGH",
L"62 Efez",
L"63 Wspomnienie Maga",
L"64 Godzina Sądu",
L"65 MBRACE",
L"66 Bitwa #5",
L"67 FINAL ASSAULT",
L"68 Pole #5",
L"69 Zamrożona Przeszłość",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Wspomnienia z Podróży",
L"75 Requiem",
L"76 Zbliżające się Zagrożenie",
L"77 CASTLE WALKENSWAARD",
L"78 Kaplica~Echnaton~",
L"79 Loch #2",
L"80 Loch #3",
L"81 Epilog",
L"82 Truth In Me",
L"84 Fantom"
};

TCHAR tiarc_tr[][128] = {
L"★OPEN YOUR EYES",
L"02 Günahın Çocuklarının İlahisi",
L"03 Kıta Manzarası",
L"04 Zafer!",
L"05 Beklenmedik Sonuç",
L"06 Kısa Dinlenme",
L"07 Uykusuz Gece",
L"08 ENCOUNTER BATTLE",
L"09 Savaş #2",
L"10 Mabed",
L"11 Alan #1",
L"12 Balo",
L"13 Huzur",
L"14 Gerilim",
L"15 Lagni Köyü",
L"16 Ayrılış Günü",
L"17 Açık Denize",
L"18 Liman Kasabası Tiny",
L"19 Kötü Plan",
L"20 Antrenman Zamanı!",
L"21 Karanlıktaki Adımlar-İşaret-",
L"22 Sınır Şehri Martuni",
L"23 Cumhuriyet Başkenti Kubbe",
L"24 Yaklaşan Kriz",
L"25 Acele Et!",
L"26 İkimiz...",
L"27 Alan #2",
L"28 Her Zamanki Sabah",
L"29 Liman Kasabası Ansverth",
L"30 Sardis Körfezi",
L"31 Kutsal Şehir Baal",
L"32 Elizabeth Engine",
L"33 Nostaljik Manzara",
L"34 Zindan #1",
L"35 Ocarina",
L"36 EVERLASTING NIGHTMARE",
L"37 Lagni Köyü başka versiyon",
L"38 BURST INTO THE BATTLE",
L"39 Alan #3",
L"40 Yıkımın Gölgesi",
L"41 Kavşak",
L"42 Tanrı'dan Ayrılış",
L"43 Yüzleşme",
L"44 Alan #4",
L"45 Priscillona'nın Teması",
L"46 DESTRUCTION",
L"47 Estenu Chodar",
L"48 Uğursuz",
L"49 Seteban Araştırma Bölgesi",
L"50 DESERTED TOWN",
L"51 Dua",
L"52 Değişen Dünya",
L"53 Lacrimosa Vadisi",
L"54 ESPIONAGE",
L"55 Erheiv Kalesi",
L"56 İniş",
L"57 Savaş #4",
L"58 Alan #5",
L"59 Gelna Platosu",
L"60 Hayalet",
L"61 BREAKTHROUGH",
L"62 Efes",
L"63 Bir Magi'nin Anısı",
L"64 Yargı Saati",
L"65 MBRACE",
L"66 Savaş #5",
L"67 FINAL ASSAULT",
L"68 Alan #5",
L"69 Dondurulmuş Geçmiş",
L"70 FALL OF THE EMPIRE",
L"71 Constellarium",
L"72 N.O.A.H.",
L"73 EDEN",
L"74 Yolculuk Anıları",
L"75 Requiem",
L"76 Yaklaşan Tehdit",
L"77 CASTLE WALKENSWAARD",
L"78 Şapel~Akhenaton~",
L"79 Zindan #2",
L"80 Zindan #3",
L"81 Sonsöz",
L"82 Truth In Me",
L"84 Hayalet"
};


static inline CString ArcTrack(int i) {
	switch (savedata.lang) {
		case 0: return CString(tiarc[i]);
		case 1: return CString(tiarc_en[i]);
		case 2: return CString(tiarc_fr[i]);
		case 3: return CString(tiarc_it[i]);
		case 4: return CString(tiarc_es[i]);
		case 5: return CString(tiarc_ko[i]);
		case 6: return CString(tiarc_zh[i]);
		case 7: return CString(tiarc_ar[i]);
		case 8: return CString(tiarc_ru[i]);
		case 9: return CString(tiarc_de[i]);
		case 10: return CString(tiarc_pt[i]);
		case 11: return CString(tiarc_nl[i]);
		case 12: return CString(tiarc_pl[i]);
		case 13: return CString(tiarc_tr[i]);
		default: return CString(tiarc_en[i]);
	}
}

CString CArc::Gett(int a){
	CString s,ss;
	s = ArcTrack(a);
	ss=s.Left(2);ss.TrimRight();
	fnn=s.Mid(3);
	return ss;
}

/////////////////////////////////////////////////////////////////////////////
// CZWEIII メッセージ ハンドラ
void CArc::OnDblclkList1() 
{
	// TODO: この位置にコントロール通知ハンドラ用のコードを追加してください
	int idx=m_list.GetItemData(m_list.GetCurSel());
	CString s;	s = ArcTrack(idx);
	ret=s.Left(2); ret.TrimRight();
	ret2=m_list.GetCurSel();
#if UNICODE
	if(s.Left(1)=="★"){
		fnn=s.Mid(1);
#else
	if(s.Left(2)=="★"){
		fnn=s.Mid(2);
#endif
	}else{
		fnn=s.Mid(3);
	}
	EndDialog(1567);
}

BOOL CArc::OnInitDialog() 
{
	CCustomDialog::OnInitDialog();
	SetWindowText(LL14(L"アークトゥルス -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-", L"Arcturus -Arcturus-"));
	SetDlgItemText(IDOK, LL14(L"閉じる", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close"));
	
	// TODO: この位置に初期化の補足処理を追加してください
	int dx;
	for(int i=0;i<(83);i++)
	{
		CString s = ArcTrack(i);
		dx= m_list.AddString(s);
		m_list.SetItemData(dx,i);	
	}

	m_list.SetCurSel(0);
	if(ret2!=0) 
//		if(ret>65) m_list.SetCurSel(ret);
//		else m_list.SetCurSel(ret-1);
		m_list.SetCurSel(ret2);
	m_list.SetFocus();
	return FALSE;  // コントロールにフォーカスを設定しないとき、戻り値は TRUE となります
	              // 例外: OCX プロパティ ページの戻り値は FALSE となります
}


void CArc::OnPaint()
{
	CPaintDC dc(this); // device context for painting
					   // TODO: ここにメッセージ ハンドラー コードを追加します。
					   // 描画メッセージで CCustomDialog::OnPaint() を呼び出さないでください。
}

void CArc::OnBnClickedOk()
{
	CCustomDialog::OnOK();
}




