// ED4.cpp : 実装ファイル
//

#include "stdafx.h"
#include "ogg.h"
#include "ED4.h"


// CED4 ダイアログ

IMPLEMENT_DYNAMIC(CED4, CCustomBlurDialogBase)

CED4::CED4(CWnd* pParent /*=NULL*/)
	: CCustomBlurDialogBase(CED4::IDD, pParent)
{

}

CED4::~CED4()
{
}

void CED4::DoDataExchange(CDataExchange* pDX)
{
	CCustomBlurDialogBase::DoDataExchange(pDX);
	DDX_Control(pDX, IDC_LIST1, m_list);
	DDX_Control(pDX, IDOK, m_okdummy);
}

#include "CImageBase.h"
BEGIN_MESSAGE_MAP(CED4, CCustomBlurDialogBase)
	ON_LBN_DBLCLK(IDC_LIST1, OnDblclkList1)
	cmn(CED4);


// CED4 メッセージ ハンドラ
extern CString fnn;

TCHAR tied4[][128] = {
L"E4S00 朱紅い雫　-memoria-",
L"★OP1 朱紅い雫　-伝承-（オープニングムービー）",
L"★OP2 絆　-熱き想いを胸に（オープニングムービー）",
L"E4B01 ぬくもりに抱かれて・・・",
L"E4N28 異端者の襲撃　-邪神オクトゥムの陰-",
L"E4A00 やすらぎの日々",
L"E4S02 いつか来た村",
L"E4S04 足取り軽く",
L"E4N00 そりゃあないでSHOW",
L"E4S05 希望へ続く道",
L"E4S13 負けるものか！",
L"E4A01 王都フィルディン",
L"E4A02 フィルディン城",
L"E4N01 さらに愉快な仲間たち",
L"E4S17 走れアヴィン！！",
L"E4C01 怯える人々",
L"E4N17 向かうべき路途（みち）へ",
L"E4S06 暗闇に巣食う者",
L"E4S14 迷宮乱舞",
L"E4S28 シャムシール団",
L"E4S18 元気なシャノン",
L"E4S07 森を行け",
L"E4N24 朱紅い雫 -神に選ばれし娘-",
L"E4S01 にぎやかな街角",
L"E4C00 鉄鋼の町～ギア～",
L"E4S15 邪魔をするな！",
L"E4S24 明日があります",
L"E4C03 途方にくれて -ギア・ブルース-",
L"E4S03 潮風のリズム",
L"E4S11 海原を風に乗り",
L"E4S25 朱紅い雫　-愛しのアイメル-",
L"E4N14 朱紅い雫 -幸せな時間（とき）-",
L"E4N20 燃えろアヴィン！！",
L"E4N25 たすけに来たぜ！",
L"E4N19 朱紅い雫 -待ってろアイメル-",
L"E4N99 楽勝！",
L"E4N22 旅立ち",
L"E4N12 邪神官ベリアス -襲撃-",
L"E4E00 聖都",
L"E4E01 礼拝堂 -運命と宿命の中で-",
L"E4N10 絆 -哀しみを越えて-",
L"E4N11 Blue -取り戻す旅-",
L"E4N29 守るべき一線",
L"E4D00 真実を求めて",
L"E4N80 我が名はバルドゥス　-真実-",
L"E4N15 バルドゥスの眠りし祠",
L"E4N33 死闘　-汚された精霊-",
L"E4N23 暗雲たちこめる中で",
L"E4S10 太古の遺産",
L"E4S08 泥炭沼",
L"E4N13 神々の犠牲",
L"E4N27 異端者の襲撃　-ボルゲイド-",
L"E4S19 絆　-凍てつくほどに-",
L"E4N81 我が名はバルドゥス　-集結-",
L"E4G06 我が名はバルドゥス -集結-",
L"E4N32 避けられぬ戦い",
L"E4G00 封印の地",
L"E4G02 時空間迷宮",
L"E4G03 邪神官ベリアス -信念-",
L"E4G04 我が信念の為に！",
L"E4G05 オクトゥムの願い",
L"E4N30 かくも強き願い　-代償-",
L"E4N34 かくも強き願い　-冥府-",
L"E4N31 ルティスのこころ",
L"E4N26 絆 -それぞれの場所へ-",
L"E4N35 朱紅い雫　-エンドクレジット-"
};

TCHAR tied4_en[][128] = {
L"E4S00 Tear of Vermillion -memoria-",
L"★OP1 Tear of Vermillion -Legend- (Opening movie)",
L"★OP2 Bond -With Burning Heart- (Opening movie)",
L"E4B01 Embraced by Warmth...",
L"E4N28 Heretic Assault -Shadow of Octum-",
L"E4A00 Days of Tranquility",
L"E4S02 Village Once Visited",
L"E4S04 Light Steps",
L"E4N00 That Won't Do SHOW",
L"E4S05 Path to Hope",
L"E4S13 Never Give Up!",
L"E4A01 Royal Capital Fildin",
L"E4A02 Fildin Castle",
L"E4N01 Merry Companions",
L"E4S17 Run Avin!!",
L"E4C01 Terrified People",
L"E4N17 To the Path We Must Take",
L"E4S06 Those Who Nest in Darkness",
L"E4S14 Labyrinth Dance",
L"E4S28 Shamshir Corps",
L"E4S18 Spirited Shannon",
L"E4S07 Into the Forest",
L"E4N24 Tear of Vermillion -Chosen Maiden-",
L"E4S01 Bustling Street Corner",
L"E4C00 Steel Town ~Gear~",
L"E4S15 Don't Interfere!",
L"E4S24 There's Tomorrow",
L"E4C03 At a Loss -Gear Blues-",
L"E4S03 Rhythm of the Sea Breeze",
L"E4S11 Riding the Ocean Wind",
L"E4S25 Tear of Vermillion -Beloved Aimer-",
L"E4N14 Tear of Vermillion -Happy Time-",
L"E4N20 Burn Avin!!",
L"E4N25 I've Come to Help!",
L"E4N19 Tear of Vermillion -Wait for Me Aimer-",
L"E4N99 Easy Win!",
L"E4N22 Departure",
L"E4N12 Heretic Bishop Bellius -Assault-",
L"E4E00 Holy Capital",
L"E4E01 Chapel -Fate and Destiny-",
L"E4N10 Bond -Beyond Sorrow-",
L"E4N11 Blue -Journey to Reclaim-",
L"E4N29 Line to Defend",
L"E4D00 In Search of Truth",
L"E4N80 I Am Baldus -Truth-",
L"E4N15 Baldus' Sleeping Shrine",
L"E4N33 Death Battle -Defiled Spirit-",
L"E4N23 Amid Gathering Dark Clouds",
L"E4S10 Ancient Legacy",
L"E4S08 Peat Bog",
L"E4N13 Sacrifice of the Gods",
L"E4N27 Heretic Assault -Borgade-",
L"E4S19 Bond -Frozen-",
L"E4N81 I Am Baldus -Assembly-",
L"E4G06 I Am Baldus -Assembly-",
L"E4N32 Unavoidable Battle",
L"E4G00 Land of Seals",
L"E4G02 Space-Time Labyrinth",
L"E4G03 Heretic Bishop Bellius -Conviction-",
L"E4G04 For My Conviction!",
L"E4G05 Octum's Wish",
L"E4N30 So Strong a Wish -Price-",
L"E4N34 So Strong a Wish -Underworld-",
L"E4N31 Rutis' Heart",
L"E4N26 Bond -To Our Own Places-",
L"E4N35 Tear of Vermillion -End Credits-"
};

TCHAR tied4_fr[][128] = {
L"E4S00 Larme de Vermillon -memoria-",
L"★OP1 Larme de Vermillon -Légende- (Générique)",
L"★OP2 Lien -Cœur Ardent- (Générique)",
L"E4B01 Embrassé par la Chaleur...",
L"E4N28 Assaut Hérétique -Ombre d'Octum-",
L"E4A00 Jours de Tranquillité",
L"E4S02 Village Autrefois Visité",
L"E4S04 Pas Légers",
L"E4N00 Ça Ne Va Pas SHOW",
L"E4S05 Chemin vers l'Espoir",
L"E4S13 Ne Jamais Abandonner!",
L"E4A01 Capitale Royale Fildin",
L"E4A02 Château de Fildin",
L"E4N01 Joyeux Compagnons",
L"E4S17 Cours Avin!!",
L"E4C01 Peuple Terrifié",
L"E4N17 Vers le Chemin à Suivre",
L"E4S06 Ceux Qui Nidifient dans l'Obscurité",
L"E4S14 Danse du Labyrinthe",
L"E4S28 Corps Shamshir",
L"E4S18 Shannon Plein d'Entrain",
L"E4S07 Dans la Forêt",
L"E4N24 Larme de Vermillon -Vierge Élue-",
L"E4S01 Coin de Rue Animé",
L"E4C00 Ville d'Acier ~Gear~",
L"E4S15 Ne t'Immisce Pas!",
L"E4S24 Il Y a Demain",
L"E4C03 Perdu -Gear Blues-",
L"E4S03 Rythme de la Brise Marine",
L"E4S11 Porté par le Vent de l'Océan",
L"E4S25 Larme de Vermillon -Bien-Aimée Aimer-",
L"E4N14 Larme de Vermillon -Heureux Moment-",
L"E4N20 Brûle Avin!!",
L"E4N25 Je Suis Venu Aider!",
L"E4N19 Larme de Vermillon -Attends-moi Aimer-",
L"E4N99 Victoire Facile!",
L"E4N22 Départ",
L"E4N12 Évêque Hérétique Bellius -Assaut-",
L"E4E00 Sainte Capitale",
L"E4E01 Chapelle -Destin et Providence-",
L"E4N10 Lien -Au-delà du Chagrin-",
L"E4N11 Blue -Voyage pour Reprendre-",
L"E4N29 Ligne à Défendre",
L"E4D00 À la Recherche de la Vérité",
L"E4N80 Je Suis Baldus -Vérité-",
L"E4N15 Sanctuaire Endormi de Baldus",
L"E4N33 Bataille Mortelle -Esprit Profané-",
L"E4N23 Parmi les Nuages Sombres",
L"E4S10 Héritage Ancien",
L"E4S08 Tourbière",
L"E4N13 Sacrifice des Dieux",
L"E4N27 Assaut Hérétique -Borgade-",
L"E4S19 Lien -Gelé-",
L"E4N81 Je Suis Baldus -Assemblée-",
L"E4G06 Je Suis Baldus -Assemblée-",
L"E4N32 Bataille Inévitable",
L"E4G00 Terre des Sceaux",
L"E4G02 Labyrinthe Spatio-Temporel",
L"E4G03 Évêque Hérétique Bellius -Conviction-",
L"E4G04 Pour Ma Conviction!",
L"E4G05 Vœu d'Octum",
L"E4N30 Vœu Si Fort -Prix-",
L"E4N34 Vœu Si Fort -Enfers-",
L"E4N31 Cœur de Rutis",
L"E4N26 Lien -Vers Nos Lieux-",
L"E4N35 Larme de Vermillon -Générique de Fin-"
};

TCHAR tied4_it[][128] = {
L"E4S00 Lacrima di Vermiglio -memoria-",
L"★OP1 Lacrima di Vermiglio -Leggenda- (Sigla)",
L"★OP2 Legame -Con Cuore Ardente- (Sigla)",
L"E4B01 Abbracciato dal Calore...",
L"E4N28 Assalto Eretico -Ombra di Octum-",
L"E4A00 Giorni di Tranquillità",
L"E4S02 Villaggio Una Volta Visitato",
L"E4S04 Passi Leggeri",
L"E4N00 Non Va Bene SHOW",
L"E4S05 Sentiero verso la Speranza",
L"E4S13 Non Arrendersi Mai!",
L"E4A01 Capitale Reale Fildin",
L"E4A02 Castello di Fildin",
L"E4N01 Allegri Compagni",
L"E4S17 Corri Avin!!",
L"E4C01 Gente Terrificata",
L"E4N17 Verso il Sentiero da Seguire",
L"E4S06 Coloro che Nidificano nell'Oscurità",
L"E4S14 Danza del Labirinto",
L"E4S28 Corpo Shamshir",
L"E4S18 Shannon Spiritoso",
L"E4S07 Nella Foresta",
L"E4N24 Lacrima di Vermiglio -Vergine Scelta-",
L"E4S01 Angolo di Strada Animato",
L"E4C00 Città dell'Acciaio ~Gear~",
L"E4S15 Non Interferire!",
L"E4S24 C'è Domani",
L"E4C03 Sconcertato -Gear Blues-",
L"E4S03 Ritmo della Brezza Marina",
L"E4S11 Cavalcando il Vento dell'Oceano",
L"E4S25 Lacrima di Vermiglio -Amata Aimer-",
L"E4N14 Lacrima di Vermiglio -Momento Felice-",
L"E4N20 Brucia Avin!!",
L"E4N25 Sono Venuto ad Aiutare!",
L"E4N19 Lacrima di Vermiglio -Aspettami Aimer-",
L"E4N99 Vittoria Facile!",
L"E4N22 Partenza",
L"E4N12 Vescovo Eretico Bellius -Assalto-",
L"E4E00 Santa Capitale",
L"E4E01 Cappella -Destino e Provvidenza-",
L"E4N10 Legame -Oltre il Dolore-",
L"E4N11 Blue -Viaggio per Riconquistare-",
L"E4N29 Linea da Difendere",
L"E4D00 Alla Ricerca della Verità",
L"E4N80 Sono Baldus -Verità-",
L"E4N15 Santuario Addormentato di Baldus",
L"E4N33 Battaglia Mortale -Spirito Profanato-",
L"E4N23 Tra le Nuvole Oscure",
L"E4S10 Eredità Antica",
L"E4S08 Torbiera",
L"E4N13 Sacrificio degli Dei",
L"E4N27 Assalto Eretico -Borgade-",
L"E4S19 Legame -Congelato-",
L"E4N81 Sono Baldus -Assemblea-",
L"E4G06 Sono Baldus -Assemblea-",
L"E4N32 Battaglia Inevitabile",
L"E4G00 Terra dei Sigilli",
L"E4G02 Labirinto Spazio-Temporale",
L"E4G03 Vescovo Eretico Bellius -Convinzione-",
L"E4G04 Per La Mia Convinzione!",
L"E4G05 Desiderio di Octum",
L"E4N30 Desiderio Così Forte -Prezzo-",
L"E4N34 Desiderio Così Forte -Oltretomba-",
L"E4N31 Cuore di Rutis",
L"E4N26 Legame -Verso i Nostri Luoghi-",
L"E4N35 Lacrima di Vermiglio -Crediti Finali-"
};

TCHAR tied4_es[][128] = {
L"E4S00 Lágrima de Bermellón -memoria-",
L"★OP1 Lágrima de Bermellón -Leyenda- (Apertura)",
L"★OP2 Vínculo -Con Corazón Ardiente- (Apertura)",
L"E4B01 Abrazado por el Calor...",
L"E4N28 Asalto Herético -Sombra de Octum-",
L"E4A00 Días de Tranquilidad",
L"E4S02 Pueblo Una Vez Visitado",
L"E4S04 Pasos Ligeros",
L"E4N00 Eso No Vale SHOW",
L"E4S05 Camino a la Esperanza",
L"E4S13 ¡Nunca Rendirse!",
L"E4A01 Capital Real Fildin",
L"E4A02 Castillo de Fildin",
L"E4N01 Alegres Compañeros",
L"E4S17 ¡Corre Avin!!",
L"E4C01 Gente Aterrorizada",
L"E4N17 Hacia el Camino que Debemos Tomar",
L"E4S06 Los que Anidan en la Oscuridad",
L"E4S14 Danza del Laberinto",
L"E4S28 Cuerpo Shamshir",
L"E4S18 Shannon Animado",
L"E4S07 Hacia el Bosque",
L"E4N24 Lágrima de Bermellón -Doncella Elegida-",
L"E4S01 Esquina de Calle Concurrida",
L"E4C00 Ciudad del Acero ~Gear~",
L"E4S15 ¡No Intervengas!",
L"E4S24 Hay Mañana",
L"E4C03 Perplejo -Gear Blues-",
L"E4S03 Ritmo de la Brisa Marina",
L"E4S11 Cabalgando el Viento del Océano",
L"E4S25 Lágrima de Bermellón -Amada Aimer-",
L"E4N14 Lágrima de Bermellón -Momento Feliz-",
L"E4N20 ¡Arde Avin!!",
L"E4N25 ¡He Venido a Ayudar!",
L"E4N19 Lágrima de Bermellón -Espérame Aimer-",
L"E4N99 ¡Victoria Fácil!",
L"E4N22 Partida",
L"E4N12 Obispo Herético Bellius -Asalto-",
L"E4E00 Santa Capital",
L"E4E01 Capilla -Destino y Providencia-",
L"E4N10 Vínculo -Más Allá del Dolor-",
L"E4N11 Blue -Viaje para Recuperar-",
L"E4N29 Línea a Defender",
L"E4D00 En Busca de la Verdad",
L"E4N80 Soy Baldus -Verdad-",
L"E4N15 Santuario Durmiente de Baldus",
L"E4N33 Batalla Mortal -Espíritu Profanado-",
L"E4N23 Entre Nubes Oscuras",
L"E4S10 Legado Antiguo",
L"E4S08 Turbera",
L"E4N13 Sacrificio de los Dioses",
L"E4N27 Asalto Herético -Borgade-",
L"E4S19 Vínculo -Congelado-",
L"E4N81 Soy Baldus -Asamblea-",
L"E4G06 Soy Baldus -Asamblea-",
L"E4N32 Batalla Inevitable",
L"E4G00 Tierra de los Sellos",
L"E4G02 Laberinto Espacio-Temporal",
L"E4G03 Obispo Herético Bellius -Convicción-",
L"E4G04 ¡Por Mi Convicción!",
L"E4G05 Deseo de Octum",
L"E4N30 Deseo Tan Fuerte -Precio-",
L"E4N34 Deseo Tan Fuerte -Inframundo-",
L"E4N31 Corazón de Rutis",
L"E4N26 Vínculo -A Nuestros Lugares-",
L"E4N35 Lágrima de Bermellón -Créditos Finales-"
};

TCHAR tied4_ko[][128] = {
L"E4S00 주홍빛 물방울 -memoria-",
L"★OP1 주홍빛 물방울 -전승- (오프닝)",
L"★OP2 유대 -뜨거운 마음과 함께- (오프닝)",
L"E4B01 따뜻함에 안겨서...",
L"E4N28 이단자의 습격 -옥툼의 그림자-",
L"E4A00 평온한 나날",
L"E4S02 한때 방문한 마을",
L"E4S04 가벼운 발걸음",
L"E4N00 그건 안 돼 SHOW",
L"E4S05 희망으로 가는 길",
L"E4S13 지지 않는다!",
L"E4A01 왕도 필딘",
L"E4A02 필딘 성",
L"E4N01 즐거운 동료들",
L"E4S17 달려라 아빈!!",
L"E4C01 공포에 떠는 사람들",
L"E4N17 가야 할 길로",
L"E4S06 어둠에 깃드는 자들",
L"E4S14 미궁의 춤",
L"E4S28 샴시르 부대",
L"E4S18 활기찬 섀넌",
L"E4S07 숲으로",
L"E4N24 주홍빛 물방울 -선택받은 소녀-",
L"E4S01 북적이는 거리",
L"E4C00 철의 마을 ~기어~",
L"E4S15 방해하지 마!",
L"E4S24 내일이 있어",
L"E4C03 막막함 -기어 블루스-",
L"E4S03 바닷바람의 리듬",
L"E4S11 바람을 타고",
L"E4S25 주홍빛 물방울 -사랑하는 아이메르-",
L"E4N14 주홍빛 물방울 -행복한 시간-",
L"E4N20 타올라라 아빈!!",
L"E4N25 도우러 왔다!",
L"E4N19 주홍빛 물방울 -기다려 아이메르-",
L"E4N99 쉬운 승리!",
L"E4N22 출발",
L"E4N12 이단 주교 벨리우스 -습격-",
L"E4E00 성도",
L"E4E01 예배당 -운명과 숙명-",
L"E4N10 유대 -슬픔을 넘어서-",
L"E4N11 Blue -되찾는 여행-",
L"E4N29 지켜야 할 선",
L"E4D00 진실을 찾아서",
L"E4N80 나는 발두스 -진실-",
L"E4N15 발두스의 잠든 신전",
L"E4N33 사투 -더럽혀진 정령-",
L"E4N23 검은 구름 속에서",
L"E4S10 고대의 유산",
L"E4S08 토탄 늪",
L"E4N13 신들의 희생",
L"E4N27 이단자의 습격 -보르게이드-",
L"E4S19 유대 -얼어붙은-",
L"E4N81 나는 발두스 -결집-",
L"E4G06 나는 발두스 -결집-",
L"E4N32 피할 수 없는 전투",
L"E4G00 봉인의 땅",
L"E4G02 시공간 미궁",
L"E4G03 이단 주교 벨리우스 -신념-",
L"E4G04 나의 신념을 위해!",
L"E4G05 옥툼의 소원",
L"E4N30 강한 소원 -대가-",
L"E4N34 강한 소원 -명부-",
L"E4N31 루티스의 마음",
L"E4N26 유대 -각자의 장소로-",
L"E4N35 주홍빛 물방울 -엔드 크레딧-"
};

TCHAR tied4_zh[][128] = {
L"E4S00 朱红泪滴 -memoria-",
L"★OP1 朱红泪滴 -传承- (片头)",
L"★OP2 羁绊 -心怀热忱- (片头)",
L"E4B01 被温暖拥抱...",
L"E4N28 异端者袭击 -奥克顿之影-",
L"E4A00 安宁的日子",
L"E4S02 曾访之村",
L"E4S04 轻盈步伐",
L"E4N00 那可不行SHOW",
L"E4S05 通往希望之路",
L"E4S13 绝不认输!",
L"E4A01 王都菲尔丁",
L"E4A02 菲尔丁城",
L"E4N01 愉快的伙伴们",
L"E4S17 冲啊阿文!!",
L"E4C01 恐惧的人们",
L"E4N17 应行之路",
L"E4S06 蛰伏暗处者",
L"E4S14 迷宫乱舞",
L"E4S28 夏姆希尔团",
L"E4S18 元气夏侬",
L"E4S07 深入森林",
L"E4N24 朱红泪滴 -神选之女-",
L"E4S01 繁华街角",
L"E4C00 钢铁之镇～齿轮～",
L"E4S15 别妨碍!",
L"E4S24 还有明天",
L"E4C03 束手无策 -齿轮布鲁斯-",
L"E4S03 潮风节奏",
L"E4S11 乘风破浪",
L"E4S25 朱红泪滴 -挚爱艾梅尔-",
L"E4N14 朱红泪滴 -幸福时光-",
L"E4N20 燃烧吧阿文!!",
L"E4N25 来帮忙了!",
L"E4N19 朱红泪滴 -等着我艾梅尔-",
L"E4N99 轻松获胜!",
L"E4N22 启程",
L"E4N12 异端神官贝利亚斯 -袭击-",
L"E4E00 圣都",
L"E4E01 礼拜堂 -命运与宿命-",
L"E4N10 羁绊 -超越悲伤-",
L"E4N11 Blue -寻回之旅-",
L"E4N29 应守之线",
L"E4D00 追寻真理",
L"E4N80 吾名巴尔杜斯 -真理-",
L"E4N15 巴尔杜斯沉睡之祠",
L"E4N33 死斗 -被污之灵-",
L"E4N23 阴云密布之中",
L"E4S10 太古遗产",
L"E4S08 泥炭沼",
L"E4N13 诸神牺牲",
L"E4N27 异端者袭击 -博尔盖德-",
L"E4S19 羁绊 -冰封-",
L"E4N81 吾名巴尔杜斯 -集结-",
L"E4G06 吾名巴尔杜斯 -集结-",
L"E4N32 不可避免之战",
L"E4G00 封印之地",
L"E4G02 时空迷宫",
L"E4G03 异端神官贝利亚斯 -信念-",
L"E4G04 为吾信念!",
L"E4G05 奥克顿之愿",
L"E4N30 强烈之愿 -代价-",
L"E4N34 强烈之愿 -冥府-",
L"E4N31 露蒂丝之心",
L"E4N26 羁绊 -各赴其所-",
L"E4N35 朱红泪滴 -片尾字幕-"
};

TCHAR tied4_ar[][128] = {
L"E4S00 دمعة القرمزي -memoria-",
L"★OP1 دمعة القرمزي -الأسطورة- (المقدمة)",
L"★OP2 الرابطة -بقلب مشتعل- (المقدمة)",
L"E4B01 محتضنا بالدفء...",
L"E4N28 هجوم هرطوقي -ظل أوكتوم-",
L"E4A00 أيام الهدوء",
L"E4S02 القرية التي زُرِيت سابقاً",
L"E4S04 خطوات خفيفة",
L"E4N00 هذا لا يجوز SHOW",
L"E4S05 الطريق إلى الأمل",
L"E4S13 لا تستسلم أبداً!",
L"E4A01 العاصمة الملكية فيلدين",
L"E4A02 قلعة فيلدين",
L"E4N01 الرفاق المرحون",
L"E4S17 اركض أفين!!",
L"E4C01 الشعب المرتعد",
L"E4N17 نحو الطريق الذي يجب سلوكه",
L"E4S06 من يعشش في الظلام",
L"E4S14 رقصة المتاهة",
L"E4S28 فيلق شمشير",
L"E4S18 شانون النشيط",
L"E4S07 إلى الغابة",
L"E4N24 دمعة القرمزي -البكر المختارة-",
L"E4S01 زاوية الشارع المزدحمة",
L"E4C00 مدينة الفولاذ ~Gear~",
L"E4S15 لا تتدخل!",
L"E4S24 هناك غداً",
L"E4C03 في حيرة -Gear Blues-",
L"E4S03 إيقاع نسيم البحر",
L"E4S11 راكباً ريح المحيط",
L"E4S25 دمعة القرمزي -الحبيبة أيمر-",
L"E4N14 دمعة القرمزي -وقت سعيد-",
L"E4N20 احترق أفين!!",
L"E4N25 جئت للمساعدة!",
L"E4N19 دمعة القرمزي -انتظريني أيمر-",
L"E4N99 انتصار سهل!",
L"E4N22 المغادرة",
L"E4N12 الأسقف الهرطوقي بليوس -الهجوم-",
L"E4E00 العاصمة المقدسة",
L"E4E01 الكنيسة -القدر والمصير-",
L"E4N10 الرابطة -ما وراء الحزن-",
L"E4N11 Blue -رحلة الاستعادة-",
L"E4N29 الخط للدفاع",
L"E4D00 في البحث عن الحقيقة",
L"E4N80 أنا بالدوس -الحقيقة-",
L"E4N15 ضريح بالدوس النائم",
L"E4N33 معركة الموت -الروح المدنسة-",
L"E4N23 وسط السحب الداكنة",
L"E4S10 الإرث القديم",
L"E4S08 مستنقع الخث",
L"E4N13 تضحية الآلهة",
L"E4N27 هجوم هرطوقي -بورغيد-",
L"E4S19 الرابطة -المجمدة-",
L"E4N81 أنا بالدوس -التجمع-",
L"E4G06 أنا بالدوس -التجمع-",
L"E4N32 المعركة التي لا مفر منها",
L"E4G00 أرض الأختام",
L"E4G02 متاهة الزمكان",
L"E4G03 الأسقف الهرطوقي بليوس -القناعة-",
L"E4G04 من أجل قناعتي!",
L"E4G05 أمنية أوكتوم",
L"E4N30 أمنية قوية جداً -الثمن-",
L"E4N34 أمنية قوية جداً -العالم السفلي-",
L"E4N31 قلب روتيس",
L"E4N26 الرابطة -إلى أماكننا-",
L"E4N35 دمعة القرمزي -شكر النهاية-"
};

TCHAR tied4_ru[][128] = {
L"E4S00 Слеза Пурпура -memoria-",
L"★OP1 Слеза Пурпура -Легенда- (Заставка)",
L"★OP2 Связь -С Пылающим Сердцем- (Заставка)",
L"E4B01 Объятый Теплом...",
L"E4N28 Еретический Штурм -Тень Октума-",
L"E4A00 Дни Покоя",
L"E4S02 Посещённая Деревня",
L"E4S04 Лёгкие Шаги",
L"E4N00 Это Не Подходит SHOW",
L"E4S05 Путь к Надежде",
L"E4S13 Никогда Сдаваться!",
L"E4A01 Королевская Столица Филдин",
L"E4A02 Замок Филдин",
L"E4N01 Весёлые Соратники",
L"E4S17 Беги Авин!!",
L"E4C01 Напуганные Люди",
L"E4N17 К Пути, Который Надо Пройти",
L"E4S06 Те, Кто Гнездится во Тьме",
L"E4S14 Танец Лабиринта",
L"E4S28 Шамширский Корпус",
L"E4S18 Бодрая Шэннон",
L"E4S07 В Лес",
L"E4N24 Слеза Пурпура -Избранная Дева-",
L"E4S01 Оживлённый Угол Улицы",
L"E4C00 Стальной Город ~Gear~",
L"E4S15 Не Мешай!",
L"E4S24 Есть Завтра",
L"E4C03 В Растерянности -Gear Blues-",
L"E4S03 Ритм Морского Бриза",
L"E4S11 Оседлав Океанский Ветер",
L"E4S25 Слеза Пурпура -Возлюбленная Аймер-",
L"E4N14 Слеза Пурпура -Счастливый Момент-",
L"E4N20 Гори Авин!!",
L"E4N25 Я Пришёл Помочь!",
L"E4N19 Слеза Пурпура -Жди Меня Аймер-",
L"E4N99 Лёгкая Победа!",
L"E4N22 Отправление",
L"E4N12 Еретический Епископ Беллиус -Штурм-",
L"E4E00 Святая Столица",
L"E4E01 Часовня -Судьба и Удел-",
L"E4N10 Связь -За Горем-",
L"E4N11 Blue -Путь к Возвращению-",
L"E4N29 Линия для Защиты",
L"E4D00 В Поисках Истины",
L"E4N80 Я Балдус -Истина-",
L"E4N15 Святилище Спящего Балдуса",
L"E4N33 Смертельная Битва -Осквернённый Дух-",
L"E4N23 Среди Сгущающихся Туч",
L"E4S10 Древнее Наследие",
L"E4S08 Торфяное Болото",
L"E4N13 Жертва Богов",
L"E4N27 Еретический Штурм -Боргейд-",
L"E4S19 Связь -Замороженная-",
L"E4N81 Я Балдус -Собрание-",
L"E4G06 Я Балдус -Собрание-",
L"E4N32 Неизбежная Битва",
L"E4G00 Земля Печатей",
L"E4G02 Пространственно-Временной Лабиринт",
L"E4G03 Еретический Епископ Беллиус -Убеждённость-",
L"E4G04 Ради Моей Убеждённости!",
L"E4G05 Желание Октума",
L"E4N30 Столь Сильное Желание -Цена-",
L"E4N34 Столь Сильное Желание -Подземный Мир-",
L"E4N31 Сердце Рутиса",
L"E4N26 Связь -В Наши Места-",
L"E4N35 Слеза Пурпура -Титры-"
};

TCHAR tied4_de[][128] = {
L"E4S00 Träne von Zinnober -memoria-",
L"★OP1 Träne von Zinnober -Legende- (Vorspann)",
L"★OP2 Band -Mit Brennendem Herzen- (Vorspann)",
L"E4B01 In Wärme Umarmt...",
L"E4N28 Ketzerischer Angriff -Schatten von Octum-",
L"E4A00 Tage der Ruhe",
L"E4S02 Einmal Besuchtes Dorf",
L"E4S04 Leichte Schritte",
L"E4N00 Das Geht Nicht SHOW",
L"E4S05 Pfad zur Hoffnung",
L"E4S13 Niemals Aufgeben!",
L"E4A01 Königliche Hauptstadt Fildin",
L"E4A02 Fildin Schloss",
L"E4N01 Fröhliche Gefährten",
L"E4S17 Lauf Avin!!",
L"E4C01 Verängstigte Menschen",
L"E4N17 Zum Weg den Wir Gehen Müssen",
L"E4S06 Die im Dunkel Nisten",
L"E4S14 Labyrinth-Tanz",
L"E4S28 Shamshir-Korps",
L"E4S18 Lebensfrohe Shannon",
L"E4S07 In den Wald",
L"E4N24 Träne von Zinnober -Auserwählte Jungfrau-",
L"E4S01 Belebte Straßenecke",
L"E4C00 Stahlstadt ~Gear~",
L"E4S15 Nicht Stören!",
L"E4S24 Es Gibt Morgen",
L"E4C03 Ratlos -Gear Blues-",
L"E4S03 Rhythmus der Meeresbrise",
L"E4S11 Auf dem Ozeanwind Reitend",
L"E4S25 Träne von Zinnober -Geliebte Aimer-",
L"E4N14 Träne von Zinnober -Glückliche Zeit-",
L"E4N20 Brenne Avin!!",
L"E4N25 Ich Bin Zum Helfen Gekommen!",
L"E4N19 Träne von Zinnober -Warte Auf Mich Aimer-",
L"E4N99 Leichter Sieg!",
L"E4N22 Aufbruch",
L"E4N12 Ketzerischer Bischof Bellius -Angriff-",
L"E4E00 Heilige Hauptstadt",
L"E4E01 Kapelle -Schicksal und Bestimmung-",
L"E4N10 Band -Jenseits der Trauer-",
L"E4N11 Blue -Reise zur Wiedererlangung-",
L"E4N29 Zu Verteidigende Linie",
L"E4D00 Auf der Suche nach der Wahrheit",
L"E4N80 Ich Bin Baldus -Wahrheit-",
L"E4N15 Baldus' Schlafendes Heiligtum",
L"E4N33 Todeskampf -Entweihter Geist-",
L"E4N23 Inmitten Sich Sammelnder Dunkelwolken",
L"E4S10 Altes Erbe",
L"E4S08 Torfmoor",
L"E4N13 Opfer der Götter",
L"E4N27 Ketzerischer Angriff -Borgade-",
L"E4S19 Band -Eingefroren-",
L"E4N81 Ich Bin Baldus -Versammlung-",
L"E4G06 Ich Bin Baldus -Versammlung-",
L"E4N32 Unvermeidbare Schlacht",
L"E4G00 Land der Siegel",
L"E4G02 Raum-Zeit-Labyrinth",
L"E4G03 Ketzerischer Bischof Bellius -Überzeugung-",
L"E4G04 Für Meine Überzeugung!",
L"E4G05 Octums Wunsch",
L"E4N30 So Starker Wunsch -Preis-",
L"E4N34 So Starker Wunsch -Unterwelt-",
L"E4N31 Rutis' Herz",
L"E4N26 Band -An Unsere Orte-",
L"E4N35 Träne von Zinnober -Abspann-"
};

TCHAR tied4_pt[][128] = {
L"E4S00 Lágrima de Vermelhão -memoria-",
L"★OP1 Lágrima de Vermelhão -Lenda- (Abertura)",
L"★OP2 Vínculo -Com Coração Ardente- (Abertura)",
L"E4B01 Abraçado pelo Calor...",
L"E4N28 Assalto Herético -Sombra de Octum-",
L"E4A00 Dias de Tranquilidade",
L"E4S02 Vila Uma Vez Visitada",
L"E4S04 Passos Leves",
L"E4N00 Isso Não Vale SHOW",
L"E4S05 Caminho para a Esperança",
L"E4S13 Nunca Desistir!",
L"E4A01 Capital Real Fildin",
L"E4A02 Castelo de Fildin",
L"E4N01 Companheiros Alegres",
L"E4S17 Corre Avin!!",
L"E4C01 Povo Aterrorizado",
L"E4N17 Para o Caminho que Devemos Seguir",
L"E4S06 Aqueles que Aninham na Escuridão",
L"E4S14 Dança do Labirinto",
L"E4S28 Corpo Shamshir",
L"E4S18 Shannon Animado",
L"E4S07 Para a Floresta",
L"E4N24 Lágrima de Vermelhão -Donzela Escolhida-",
L"E4S01 Esquina de Rua Movimentada",
L"E4C00 Cidade do Aço ~Gear~",
L"E4S15 Não Interfira!",
L"E4S24 Há Amanhã",
L"E4C03 Perplexo -Gear Blues-",
L"E4S03 Ritmo da Brisa Marinha",
L"E4S11 Cavalgando o Vento do Oceano",
L"E4S25 Lágrima de Vermelhão -Amada Aimer-",
L"E4N14 Lágrima de Vermelhão -Momento Feliz-",
L"E4N20 Queima Avin!!",
L"E4N25 Vim para Ajudar!",
L"E4N19 Lágrima de Vermelhão -Espere por Mim Aimer-",
L"E4N99 Vitória Fácil!",
L"E4N22 Partida",
L"E4N12 Bispo Herético Bellius -Assalto-",
L"E4E00 Santa Capital",
L"E4E01 Capela -Destino e Providência-",
L"E4N10 Vínculo -Além da Tristeza-",
L"E4N11 Blue -Jornada para Recuperar-",
L"E4N29 Linha a Defender",
L"E4D00 Em Busca da Verdade",
L"E4N80 Sou Baldus -Verdade-",
L"E4N15 Santuário Adormecido de Baldus",
L"E4N33 Batalha Mortal -Espírito Profanado-",
L"E4N23 Entre Nuvens Negras",
L"E4S10 Legado Antigo",
L"E4S08 Pântano de Turfa",
L"E4N13 Sacrifício dos Deuses",
L"E4N27 Assalto Herético -Borgade-",
L"E4S19 Vínculo -Congelado-",
L"E4N81 Sou Baldus -Assembleia-",
L"E4G06 Sou Baldus -Assembleia-",
L"E4N32 Batalha Inevitável",
L"E4G00 Terra dos Selos",
L"E4G02 Labirinto Espaço-Temporal",
L"E4G03 Bispo Herético Bellius -Convicção-",
L"E4G04 Por Minha Convicção!",
L"E4G05 Desejo de Octum",
L"E4N30 Desejo Tão Forte -Preço-",
L"E4N34 Desejo Tão Forte -Mundo Inferior-",
L"E4N31 Coração de Rutis",
L"E4N26 Vínculo -Para Nossos Lugares-",
L"E4N35 Lágrima de Vermelhão -Créditos Finais-"
};

TCHAR tied4_nl[][128] = {
L"E4S00 Traan van Vermiljoen -memoria-",
L"★OP1 Traan van Vermiljoen -Legende- (Opening)",
L"★OP2 Band -Met Brandend Hart- (Opening)",
L"E4B01 Omarmd door Warmte...",
L"E4N28 Ketterlijke Aanval -Schaduw van Octum-",
L"E4A00 Dagen van Rust",
L"E4S02 Eenmaal Bezocht Dorp",
L"E4S04 Lichte Stappen",
L"E4N00 Dat Kan Niet SHOW",
L"E4S05 Pad naar Hoop",
L"E4S13 Nooit Opgeven!",
L"E4A01 Koninklijke Hoofdstad Fildin",
L"E4A02 Fildin Kasteel",
L"E4N01 Vrolijke Metgezellen",
L"E4S17 Ren Avin!!",
L"E4C01 Bang Volk",
L"E4N17 Naar het Pad dat We Moeten Volgen",
L"E4S06 Zij die in Duisternis Nestelen",
L"E4S14 Labyrint Dans",
L"E4S28 Shamshir Corps",
L"E4S18 Levendige Shannon",
L"E4S07 Het Bos In",
L"E4N24 Traan van Vermiljoen -Uitverkoren Maagd-",
L"E4S01 Drukke Straathoek",
L"E4C00 Staalstad ~Gear~",
L"E4S15 Niet Storen!",
L"E4S24 Er is Morgen",
L"E4C03 Verward -Gear Blues-",
L"E4S03 Ritme van de Zeebries",
L"E4S11 Rijdend op de Oceaanwind",
L"E4S25 Traan van Vermiljoen -Geliefde Aimer-",
L"E4N14 Traan van Vermiljoen -Gelukkig Moment-",
L"E4N20 Brand Avin!!",
L"E4N25 Ik Ben Gekomen om te Helpen!",
L"E4N19 Traan van Vermiljoen -Wacht op Mij Aimer-",
L"E4N99 Gemakkelijke Overwinning!",
L"E4N22 Vertrek",
L"E4N12 Ketterlijke Bisschop Bellius -Aanval-",
L"E4E00 Heilige Hoofdstad",
L"E4E01 Kapel -Lot en Voorzienigheid-",
L"E4N10 Band -Voorbij Verdriet-",
L"E4N11 Blue -Reis om Terug te Winnen-",
L"E4N29 Te Verdedigen Lijn",
L"E4D00 Op Zoek naar de Waarheid",
L"E4N80 Ik Ben Baldus -Waarheid-",
L"E4N15 Baldus' Slapend Heiligdom",
L"E4N33 Doodsbattle -Onteigde Geest-",
L"E4N23 Tussen Donkere Wolken",
L"E4S10 Oude Erfenis",
L"E4S08 Veenmoeras",
L"E4N13 Offer van de Goden",
L"E4N27 Ketterlijke Aanval -Borgade-",
L"E4S19 Band -Bevroren-",
L"E4N81 Ik Ben Baldus -Vergadering-",
L"E4G06 Ik Ben Baldus -Vergadering-",
L"E4N32 Onvermijdelijke Strijd",
L"E4G00 Land van Zegels",
L"E4G02 Ruimte-Tijd Labyrint",
L"E4G03 Ketterlijke Bisschop Bellius -Overtuiging-",
L"E4G04 Voor Mijn Overtuiging!",
L"E4G05 Octums Wens",
L"E4N30 Zo Sterke Wens -Prijs-",
L"E4N34 Zo Sterke Wens -Onderwereld-",
L"E4N31 Rutis' Hart",
L"E4N26 Band -Naar Onze Plaatsen-",
L"E4N35 Traan van Vermiljoen -Einde Titels-"
};

TCHAR tied4_pl[][128] = {
L"E4S00 Łza Cynobru -memoria-",
L"★OP1 Łza Cynobru -Legenda- (Czołówka)",
L"★OP2 Więź -Z Płonącym Sercem- (Czołówka)",
L"E4B01 Objęty Ciepłem...",
L"E4N28 Herecka Napaść -Cień Octuma-",
L"E4A00 Dni Spokoju",
L"E4S02 Odwiedzona Wieś",
L"E4S04 Lekkie Kroki",
L"E4N00 To Się Nie Liczy SHOW",
L"E4S05 Ścieżka do Nadziei",
L"E4S13 Nigdy Się Nie Poddawaj!",
L"E4A01 Królewska Stolica Fildin",
L"E4A02 Zamek Fildin",
L"E4N01 Weseli Towarzysze",
L"E4S17 Biegnij Avin!!",
L"E4C01 Przerażeni Ludzie",
L"E4N17 Ku Ścieżce Którą Musimy Pójść",
L"E4S06 Ci co Gniazdują w Ciemności",
L"E4S14 Taniec Labiryntu",
L"E4S28 Korpus Shamshir",
L"E4S18 Żywa Shannon",
L"E4S07 Do Lasu",
L"E4N24 Łza Cynobru -Wybrańcza Dziewica-",
L"E4S01 Ożywiony Narożnik Ulicy",
L"E4C00 Miasto Stali ~Gear~",
L"E4S15 Nie Przeszkadzaj!",
L"E4S24 Jest Jutro",
L"E4C03 Zdezorientowany -Gear Blues-",
L"E4S03 Rytm Morskiej Bryzy",
L"E4S11 Jechać na Wietrze Oceanu",
L"E4S25 Łza Cynobru -Ukochana Aimer-",
L"E4N14 Łza Cynobru -Szczęśliwa Chwila-",
L"E4N20 Płonij Avin!!",
L"E4N25 Przyszedłem Pomóc!",
L"E4N19 Łza Cynobru -Czekaj Na Mnie Aimer-",
L"E4N99 Łatwe Zwycięstwo!",
L"E4N22 Odjazd",
L"E4N12 Herecki Biskup Bellius -Napaść-",
L"E4E00 Święta Stolica",
L"E4E01 Kaplica -Los i Przeznaczenie-",
L"E4N10 Więź -Za Smutkiem-",
L"E4N11 Blue -Podróż do Odzyskania-",
L"E4N29 Linia do Obrony",
L"E4D00 W Poszukiwaniu Prawdy",
L"E4N80 Jestem Baldus -Prawda-",
L"E4N15 Śpiące Sanktuarium Baldusa",
L"E4N33 Bitwa na Śmierć -Zbezczeszczony Duch-",
L"E4N23 Pośród Gromadzących się Ciemnych Chmur",
L"E4S10 Starożytne Dziedzictwo",
L"E4S08 Torfowisko",
L"E4N13 Ofiara Bogów",
L"E4N27 Herecka Napaść -Borgade-",
L"E4S19 Więź -Zamrożona-",
L"E4N81 Jestem Baldus -Zgromadzenie-",
L"E4G06 Jestem Baldus -Zgromadzenie-",
L"E4N32 Nieuchronna Bitwa",
L"E4G00 Kraina Pieczęci",
L"E4G02 Labirynt Czasoprzestrzenny",
L"E4G03 Herecki Biskup Bellius -Przekonanie-",
L"E4G04 Dla Mojego Przekonania!",
L"E4G05 Życzenie Octuma",
L"E4N30 Tak Silne Życzenie -Cena-",
L"E4N34 Tak Silne Życzenie -Zaświaty-",
L"E4N31 Serce Rutisa",
L"E4N26 Więź -Ku Naszym Miejscom-",
L"E4N35 Łza Cynobru -Czołówka Końcowa-"
};

TCHAR tied4_tr[][128] = {
L"E4S00 Vermilyon Gözyaşı -memoria-",
L"★OP1 Vermilyon Gözyaşı -Efsane- (Açılış)",
L"★OP2 Bağ -Yanan Kalple- (Açılış)",
L"E4B01 Sıcaklıkla Kucaklanmış...",
L"E4N28 Sapkın Saldırı -Octum'un Gölgesi-",
L"E4A00 Huzurlu Günler",
L"E4S02 Bir Zamanlar Ziyaret Edilen Köy",
L"E4S04 Hafif Adımlar",
L"E4N00 Bu Olmaz SHOW",
L"E4S05 Umuda Giden Yol",
L"E4S13 Asla Pes Etme!",
L"E4A01 Kraliyet Başkenti Fildin",
L"E4A02 Fildin Kalesi",
L"E4N01 Neşeli Yoldaşlar",
L"E4S17 Koş Avin!!",
L"E4C01 Korkmuş Halk",
L"E4N17 Gitmemiz Gereken Yola",
L"E4S06 Karanlıkta Yuva Kuranlar",
L"E4S14 Labirent Dansı",
L"E4S28 Shamshir Birliği",
L"E4S18 Canlı Shannon",
L"E4S07 Ormana",
L"E4N24 Vermilyon Gözyaşı -Seçilmiş Bakire-",
L"E4S01 Kalabalık Sokak Köşesi",
L"E4C00 Çelik Şehir ~Gear~",
L"E4S15 Karışma!",
L"E4S24 Yarın Var",
L"E4C03 Şaşkın -Gear Blues-",
L"E4S03 Deniz Meltemi Ritmi",
L"E4S11 Okyanus Rüzgarında Sürülerek",
L"E4S25 Vermilyon Gözyaşı -Sevgili Aimer-",
L"E4N14 Vermilyon Gözyaşı -Mutlu An-",
L"E4N20 Yan Avin!!",
L"E4N25 Yardıma Geldim!",
L"E4N19 Vermilyon Gözyaşı -Bekle Beni Aimer-",
L"E4N99 Kolay Zafer!",
L"E4N22 Ayrılış",
L"E4N12 Sapkın Piskopos Bellius -Saldırı-",
L"E4E00 Kutsal Başkent",
L"E4E01 Şapel -Kader ve Yazgı-",
L"E4N10 Bağ -Acının Ötesinde-",
L"E4N11 Blue -Geri Almak İçin Yolculuk-",
L"E4N29 Savunulacak Çizgi",
L"E4D00 Gerçeği Arayış",
L"E4N80 Ben Baldus -Gerçek-",
L"E4N15 Baldus'un Uyuyan Tapınağı",
L"E4N33 Ölüm Savaşı -Lekelenmiş Ruh-",
L"E4N23 Karanlık Bulutlar Arasında",
L"E4S10 Antik Miras",
L"E4S08 Turbalık",
L"E4N13 Tanrıların Kurbanı",
L"E4N27 Sapkın Saldırı -Borgade-",
L"E4S19 Bağ -Donmuş-",
L"E4N81 Ben Baldus -Toplanma-",
L"E4G06 Ben Baldus -Toplanma-",
L"E4N32 Kaçınılmaz Savaş",
L"E4G00 Mühürlerin Toprağı",
L"E4G02 Uzay-Zaman Labirenti",
L"E4G03 Sapkın Piskopos Bellius -İnanç-",
L"E4G04 İnancım İçin!",
L"E4G05 Octum'un Dileği",
L"E4N30 Çok Güçlü Dilek -Bedel-",
L"E4N34 Çok Güçlü Dilek -Yeraltı Dünyası-",
L"E4N31 Rutis'in Kalbi",
L"E4N26 Bağ -Kendi Yerlerimize-",
L"E4N35 Vermilyon Gözyaşı -Bitiş Jeneriği-"
};

static inline CString ED4Track(int i) {
	switch (savedata.lang) {
	case 0: return CString(tied4[i]);
	case 1: return CString(tied4_en[i]);
	case 2: return CString(tied4_fr[i]);
	case 3: return CString(tied4_it[i]);
	case 4: return CString(tied4_es[i]);
	case 5: return CString(tied4_ko[i]);
	case 6: return CString(tied4_zh[i]);
	case 7: return CString(tied4_ar[i]);
	case 8: return CString(tied4_ru[i]);
	case 9: return CString(tied4_de[i]);
	case 10: return CString(tied4_pt[i]);
	case 11: return CString(tied4_nl[i]);
	case 12: return CString(tied4_pl[i]);
	case 13: return CString(tied4_tr[i]);
	default: return CString(tied4_en[i]);
	}
}

CString CED4::Gett(int a) {
	CString s, ss;
	s = ED4Track(a);
	ss = s.Left(5); ss.TrimRight();
	fnn = s.Mid(6);
	return ss;
}

/////////////////////////////////////////////////////////////////////////////
// CZWEIII メッセージ ハンドラ
void CED4::OnDblclkList1()
{
	// TODO: この位置にコントロール通知ハンドラ用のコードを追加してください
	int idx = m_list.GetItemData(m_list.GetCurSel());
	CString s;	s = ED4Track(idx);
	ret = s.Left(5); ret.TrimRight();
	ret2 = m_list.GetCurSel();
#if UNICODE
	if (s.Left(1) == "★") {
		fnn = s.Mid(1);
#else
	if (s.Left(2) == "★") {
		fnn = s.Mid(2);
#endif
	}
	else {
		fnn = s.Mid(6);
	}
	EndDialog(1567);
	}

BOOL CED4::OnInitDialog()
{
	CCustomBlurDialogBase::OnInitDialog();
	SetWindowText(LL14(L"英雄伝説IV 朱紅い雫", L"Legend of Heroes IV Tear of Vermillion", L"Légende des Héros IV Larme de Vermillon", L"Legend of Heroes IV Lacrima di Vermiglio", L"Legend of Heroes IV Lágrima de Bermellón", L"영웅전설IV 주홍의 물방울", L"英雄传说IV 朱红之泪", L"Legend of Heroes IV Tear of Vermillion", L"Legend of Heroes IV Tear of Vermillion", L"Legend of Heroes IV Träne der Purpur", L"Legend of Heroes IV Tear of Vermillion", L"Legend of Heroes IV Tear of Vermillion", L"Legend of Heroes IV Tear of Vermillion", L"Legend of Heroes IV Tear of Vermillion"));
	SetDlgItemText(IDOK, LL14(L"閉じる", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close"));

	// TODO: この位置に初期化の補足処理を追加してください
	int dx;
	for (int i = 0; i < (66); i++)
	{
		CString s = ED4Track(i);
		dx = m_list.AddString(s);
		m_list.SetItemData(dx, i);
	}

	m_list.SetCurSel(0);
	if (ret2 != 0)
		//		if(ret>65) m_list.SetCurSel(ret);
		//		else m_list.SetCurSel(ret-1);
		m_list.SetCurSel(ret2);
	m_list.SetFocus();
	return FALSE;  // コントロールにフォーカスを設定しないとき、戻り値は TRUE となります
	// 例外: OCX プロパティ ページの戻り値は FALSE となります
}


