// San2.cpp : 実装ファイル
//

#include "stdafx.h"
#include "ogg.h"
#include "San2.h"


// CSan2 ダイアログ

IMPLEMENT_DYNAMIC(CSan2, CCustomBlurDialogBase)

CSan2::CSan2(CWnd* pParent /*=NULL*/)
	: CCustomBlurDialogBase(CSan2::IDD, pParent)
{

}

CSan2::~CSan2()
{
}

void CSan2::DoDataExchange(CDataExchange* pDX)
{
	CCustomBlurDialogBase::DoDataExchange(pDX);
	DDX_Control(pDX, IDC_LIST1, m_list);
	DDX_Control(pDX, IDOK, m_okdummy);
}

#include "CImageBase.h"
BEGIN_MESSAGE_MAP(CSan2, CCustomBlurDialogBase)
	ON_LBN_DBLCLK(IDC_LIST1, OnDblclkList1)
	cmn(CSan2);


// CSan2 メッセージ ハンドラ
extern CString fnn;

TCHAR tisan2[][128]={
_T("41 主題曲：界線(日本語Ver)"),
_T("41 主題曲：界線(中国Ver)"),
_T("45 懸圃：瓊樓玉宇"),
_T("44 大地圖：鴻鵠萬里"),
_T("16 白馬寒潭：碧水洞天"),
_T("12 無界縫細：流雲輕舟"),
_T("01 召徳村：暁風"),
_T("11 古皇宮藏道：寒冰夜"),
_T("19 飛凰宮：戰飛凰"),
_T("48 武將出場：萬夫莫敵"),
_T("36 一般戰鬥2：談笑論劍"),
_T("18 鬼界：黄泉夢地"),
_T("34 浪漫愛情曲：月下寄情"),
_T("08 沙暴廢坑"),
_T("09 潼關水路：空山新雨"),
_T("25 濮陽雷澤：暗夜驚雷"),
_T("22 蕭關：潛影"),
_T("20 射日坡：波瀾動"),
_T("21 壽春：一夫當關"),
_T("39 戰場頭目戰鬥：爭鋒"),
_T("30 緊張2(大)：危機四伏"),
_T("32 非慟：離愁恨"),
_T("13 浮月林：清月幽林"),
_T("33 哀愁：相思無盡"),
_T("47 百花樓"),

_T("15 臥雲榻：半日"),
_T("03 洛陽：秋霜"),
_T("23 下ヒ：英雄末路"),
_T("07 鎮江：美人含笑"),
#if _UNICODE
_T("27 輕鬆俏皮"),
#else
_T("27 輕鬆しょう皮"),
#endif
#if _UNICODE
_T("28 搞笑"),
#else
_T("28 こう笑"),
#endif
_T("29 小緊張"),
#if _UNICODE
_T("10 崆峴山：嵐舞"),
#else
_T("10 そうけん山：嵐舞"),
#endif
_T("14 洛陽西郊棧道：轟"),
_T("06 許都：征前曲"),
_T("02 長安：出巡"),
_T("38 戰場戰鬥：決勝"),
_T("24 官渡：路關險"),
_T("37 一般頭目戰鬥：對峙"),
_T("26 天若宮：天若仙韻"),
_T("04 小沛：春色"),
_T("17 幽妍島：霓裳"),
_T("46 皇宮：皇圖"),
_T("05 徐州：軍陣"),
_T("31 重大打撃：天倫夢斷"),
_T("40 最終頭目戰鬥：探雲霄"),
_T("42 插曲：情衷"),
_T("56 暗思量(幻想三国志1)"),
_T("60 笑笑(幻想三国志1)"),
_T("★ファルコムロゴ"),
_T("★宇峻奥汀ロゴ"),
_T("★オープニング"),
_T("35 (不明)")
};

TCHAR tisan2_en[][128]={
_T("41 Theme: Borderline (Japanese Ver)"),
_T("41 Theme: Borderline (Chinese Ver)"),
_T("45 Hanging Garden: Jade Palace"),
_T("44 World Map: Vast Horizon"),
_T("16 White Horse Cold Pool: Blue Waters"),
_T("12 Boundless: Light Clouds"),
_T("01 Zhaode Village: Dawn Wind"),
_T("11 Ancient Palace Path: Cold Ice Night"),
_T("19 Feihuang Palace: Flying Phoenix"),
_T("48 General Appearance: Invincible"),
_T("36 Normal Battle 2: Sword Talk"),
_T("18 Ghost Realm: Dream of the Underworld"),
_T("34 Romance: Moonlit Feelings"),
_T("08 Sandstorm Wasteland"),
_T("09 Tong Pass Waterway: Mountain Rain"),
_T("25 Puyang Lei Marsh: Night Thunder"),
_T("22 Xiaoguan: Hidden Shadow"),
_T("20 Sheri Slope: Waves"),
_T("21 Shouchun: One Against All"),
_T("39 Field Boss Battle: Contest"),
_T("30 Tension 2 (Major): Danger Everywhere"),
_T("32 Sorrow: Parting Grief"),
_T("13 Floating Moon Forest: Quiet Moon Woods"),
_T("33 Melancholy: Endless Longing"),
_T("47 Hundred Flowers Tower"),
_T("15 Cloud Rest: Half Day"),
_T("03 Luoyang: Autumn Frost"),
_T("23 Xiahou: Hero's End"),
_T("07 Zhenjiang: Beauty's Smile"),
_T("27 Light and Playful"),
_T("28 Comedy"),
_T("29 Minor Tension"),
_T("10 Kongxian Mountain: Storm Dance"),
_T("14 Luoyang Western Road: Roar"),
_T("06 Xudu: Marching Song"),
_T("02 Chang'an: Royal Progress"),
_T("38 Field Battle: Decisive"),
_T("24 Guandu: Dangerous Pass"),
_T("37 Normal Boss Battle: Confrontation"),
_T("26 Tianruo Palace: Heavenly Melody"),
_T("04 Xiaopei: Spring Colors"),
_T("17 Youyan Island: Rainbow Dress"),
_T("46 Imperial Palace: Imperial Dream"),
_T("05 Xuzhou: Military Array"),
_T("31 Major Blow: Broken Dreams"),
_T("40 Final Boss Battle: Reach the Clouds"),
_T("42 Interlude: True Feelings"),
_T("56 Dark Thoughts (Fantasy Sanguo 1)"),
_T("60 Smile (Fantasy Sanguo 1)"),
_T("★FALCOM Logo"),
_T("★UserJoy Logo"),
_T("★Opening"),
_T("35 (Unknown)")
};

TCHAR tisan2_fr[][128]={
_T("41 Thème: Ligne de Démarcation (Ver Japonais)"),
_T("41 Thème: Ligne de Démarcation (Ver Chinois)"),
_T("45 Jardin Suspendu: Palais de Jade"),
_T("44 Carte du Monde: Vaste Horizon"),
_T("16 Piscine du Cheval Blanc: Eaux Bleues"),
_T("12 Sans Limites: Nuages Légers"),
_T("01 Village Zhaode: Vent de l'Aube"),
_T("11 Chemin du Palais Antique: Nuit de Glace"),
_T("19 Palais Feihuang: Phénix Volant"),
_T("48 Apparition du Général: Invincible"),
_T("36 Bataille Normale 2: Discussion d'Épées"),
_T("18 Royaume des Esprits: Rêve de l'Au-delà"),
_T("34 Romance: Sentiments au Clair de Lune"),
_T("08 Désert de Tempête de Sable"),
_T("09 Voie Maritime de Tong: Pluie des Montagnes"),
_T("25 Marais Puyang Lei: Tonnerre Nocturne"),
_T("22 Xiaoguan: Ombre Cachée"),
_T("20 Pente Sheri: Vagues"),
_T("21 Shouchun: Un Contre Tous"),
_T("39 Bataille Boss de Terrain: Combat"),
_T("30 Tension 2 (Majeure): Danger Partout"),
_T("32 Chagrin: Douleur de Séparation"),
_T("13 Forêt de la Lune Flottante: Bois Silencieux"),
_T("33 Mélancolie: Désir Infini"),
_T("47 Tour aux Cent Fleurs"),
_T("15 Repos des Nuages: Demi-Journée"),
_T("03 Luoyang: Givre d'Automne"),
_T("23 Xiahou: Fin du Héros"),
_T("07 Zhenjiang: Sourire de la Beauté"),
_T("27 Léger et Enjoué"),
_T("28 Comédie"),
_T("29 Tension Mineure"),
_T("10 Mont Kongxian: Danse de la Tempête"),
_T("14 Route Occidentale de Luoyang: Rugissement"),
_T("06 Xudu: Chant de Marche"),
_T("02 Chang'an: Procession Royale"),
_T("38 Bataille de Terrain: Décisif"),
_T("24 Guandu: Passage Dangereux"),
_T("37 Bataille Boss Normale: Confrontation"),
_T("26 Palais Tianruo: Mélodie Céleste"),
_T("04 Xiaopei: Couleurs de Printemps"),
_T("17 Île Youyan: Robe Arc-en-Ciel"),
_T("46 Palais Impérial: Rêve Impérial"),
_T("05 Xuzhou: Formation Militaire"),
_T("31 Coup Majeur: Rêves Brisés"),
_T("40 Bataille Boss Final: Atteindre les Nuages"),
_T("42 Interlude: Vrais Sentiments"),
_T("56 Pensées Sombres (Fantasy Sanguo 1)"),
_T("60 Sourire (Fantasy Sanguo 1)"),
_T("★Logo FALCOM"),
_T("★Logo UserJoy"),
_T("★Ouverture"),
_T("35 (Inconnu)")
};

TCHAR tisan2_it[][128]={
_T("41 Tema: Confine (Ver Giapponese)"),
_T("41 Tema: Confine (Ver Cinese)"),
_T("45 Giardino Pensile: Palazzo di Giada"),
_T("44 Mappa del Mondo: Vasto Orizzonte"),
_T("16 Piscina del Cavallo Bianco: Acque Blu"),
_T("12 Senza Limiti: Nuvole Leggere"),
_T("01 Villaggio Zhaode: Vento dell'Alba"),
_T("11 Sentiero del Palazzo Antico: Notte di Ghiaccio"),
_T("19 Palazzo Feihuang: Fenice Volante"),
_T("48 Apparizione del Generale: Invincibile"),
_T("36 Battaglia Normale 2: Discussione di Spade"),
_T("18 Regno dei Fantasmi: Sogno dell'Aldilà"),
_T("34 Romanza: Sentimenti al Chiaro di Luna"),
_T("08 Deserto di Tempesta di Sabbia"),
_T("09 Via Acquatica di Tong: Pioggia di Montagna"),
_T("25 Palude Puyang Lei: Tuono Notturno"),
_T("22 Xiaoguan: Ombra Nascosta"),
_T("20 Pendio Sheri: Onde"),
_T("21 Shouchun: Uno Contro Tutti"),
_T("39 Battaglia Boss di Campo: Competizione"),
_T("30 Tensione 2 (Maggiore): Pericolo Ovunque"),
_T("32 Dolore: Addio Straziante"),
_T("13 Foresta della Luna Fluttuante: Boschi Silenziosi"),
_T("33 Malinconia: Desiderio Infinito"),
_T("47 Torre dei Cento Fiori"),
_T("15 Riposo delle Nuvole: Mezza Giornata"),
_T("03 Luoyang: Brina Autunnale"),
_T("23 Xiahou: Fine dell'Eroe"),
_T("07 Zhenjiang: Sorriso della Bellezza"),
_T("27 Leggero e Giocoso"),
_T("28 Commedia"),
_T("29 Tensione Minore"),
_T("10 Monte Kongxian: Danza della Tempesta"),
_T("14 Strada Occidentale di Luoyang: Fragore"),
_T("06 Xudu: Canto di Marcia"),
_T("02 Chang'an: Processione Reale"),
_T("38 Battaglia di Campo: Decisiva"),
_T("24 Guandu: Passaggio Pericoloso"),
_T("37 Battaglia Boss Normale: Confrontazione"),
_T("26 Palazzo Tianruo: Melodia Celeste"),
_T("04 Xiaopei: Colori di Primavera"),
_T("17 Isola Youyan: Veste Arcobaleno"),
_T("46 Palazzo Imperiale: Sogno Imperiale"),
_T("05 Xuzhou: Schieramento Militare"),
_T("31 Colpo Maggiore: Sogni Infranti"),
_T("40 Battaglia Boss Finale: Raggiungere le Nuvole"),
_T("42 Intermezzo: Veri Sentimenti"),
_T("56 Pensieri Oscuri (Fantasy Sanguo 1)"),
_T("60 Sorriso (Fantasy Sanguo 1)"),
_T("★Logo FALCOM"),
_T("★Logo UserJoy"),
_T("★Apertura"),
_T("35 (Sconosciuto)")
};

TCHAR tisan2_es[][128]={
_T("41 Tema: Límite (Ver Japonés)"),
_T("41 Tema: Límite (Ver Chino)"),
_T("45 Jardín Colgante: Palacio de Jade"),
_T("44 Mapa del Mundo: Vasto Horizonte"),
_T("16 Piscina del Caballo Blanco: Aguas Azules"),
_T("12 Sin Límites: Nubes Ligeras"),
_T("01 Pueblo Zhaode: Viento del Alba"),
_T("11 Sendero del Palacio Antiguo: Noche de Hielo"),
_T("19 Palacio Feihuang: Fénix Volador"),
_T("48 Aparición del General: Invencible"),
_T("36 Batalla Normal 2: Charla de Espadas"),
_T("18 Reino de los Espíritus: Sueño del Más Allá"),
_T("34 Romance: Sentimientos a la Luz de la Luna"),
_T("08 Desierto de Tormenta de Arena"),
_T("09 Vía Acuática de Tong: Lluvia de Montaña"),
_T("25 Pantano Puyang Lei: Trueno Nocturno"),
_T("22 Xiaoguan: Sombra Oculta"),
_T("20 Pendiente Sheri: Olas"),
_T("21 Shouchun: Uno Contra Todos"),
_T("39 Batalla Boss de Campo: Contienda"),
_T("30 Tensión 2 (Mayor): Peligro en Todas Partes"),
_T("32 Dolor: Pena de Despedida"),
_T("13 Bosque de la Luna Flotante: Bosque Silencioso"),
_T("33 Melancolía: Anhelo Infinito"),
_T("47 Torre de las Cien Flores"),
_T("15 Descanso en las Nubes: Medio Día"),
_T("03 Luoyang: Escarcha de Otoño"),
_T("23 Xiahou: Fin del Héroe"),
_T("07 Zhenjiang: Sonrisa de la Belleza"),
_T("27 Ligero y Juguetón"),
_T("28 Comedia"),
_T("29 Tensión Menor"),
_T("10 Monte Kongxian: Danza de la Tormenta"),
_T("14 Camino Occidental de Luoyang: Rugido"),
_T("06 Xudu: Canción de Marcha"),
_T("02 Chang'an: Procesión Real"),
_T("38 Batalla de Campo: Decisiva"),
_T("24 Guandu: Paso Peligroso"),
_T("37 Batalla Boss Normal: Confrontación"),
_T("26 Palacio Tianruo: Melodía Celestial"),
_T("04 Xiaopei: Colores de Primavera"),
_T("17 Isla Youyan: Vestido Arcoíris"),
_T("46 Palacio Imperial: Sueño Imperial"),
_T("05 Xuzhou: Formación Militar"),
_T("31 Golpe Mayor: Sueños Rotos"),
_T("40 Batalla Boss Final: Alcanzar las Nubes"),
_T("42 Interludio: Verdaderos Sentimientos"),
_T("56 Pensamientos Oscuros (Fantasy Sanguo 1)"),
_T("60 Sonrisa (Fantasy Sanguo 1)"),
_T("★Logo FALCOM"),
_T("★Logo UserJoy"),
_T("★Apertura"),
_T("35 (Desconocido)")
};

TCHAR tisan2_ko[][128]={
_T("41 주제곡: 경계선 (일본어 Ver)"),
_T("41 주제곡: 경계선 (중국어 Ver)"),
_T("45 현포: 경루옥우"),
_T("44 대지도: 홍곡만리"),
_T("16 백마한담: 벽수동천"),
_T("12 무계봉세: 류운경주"),
_T("01 소덕촌: 효풍"),
_T("11 고황궁장도: 한빙야"),
_T("19 비황궁: 전비황"),
_T("48 무장출장: 만부막적"),
_T("36 일반전투2: 담소논검"),
_T("18 귀계: 황천몽지"),
_T("34 낭만애정곡: 월하기정"),
_T("08 사폭폐갱"),
_T("09 동관수로: 공산신우"),
_T("25 복양뢰택: 암야경뢰"),
_T("22 소관: 잠영"),
_T("20 사일파: 파란동"),
_T("21 수춘: 일부당관"),
_T("39 전장두목전투: 쟁봉"),
_T("30 긴장2(대): 위기사복"),
_T("32 비동: 이수한"),
_T("13 부월림: 청월유림"),
_T("33 애수: 상사무진"),
_T("47 백화루"),
_T("15 와운탑: 반일"),
_T("03 낙양: 추상"),
_T("23 하후: 영웅말로"),
_T("07 진강: 미인함소"),
_T("27 경쾌하고 장난스러운"),
_T("28 코미디"),
_T("29 소긴장"),
_T("10 공현산: 람무"),
_T("14 낙양서교잔도: 굉"),
_T("06 허도: 정전곡"),
_T("02 장안: 출순"),
_T("38 전장전투: 결승"),
_T("24 관도: 로관험"),
_T("37 일반두목전투: 대치"),
_T("26 천약궁: 천약선운"),
_T("04 소패: 춘색"),
_T("17 유연도: 예상"),
_T("46 황궁: 황도"),
_T("05 서주: 군진"),
_T("31 중대타격: 천륜몽단"),
_T("40 최종두목전투: 탐운소"),
_T("42 삽곡: 정충"),
_T("56 암사량(환상삼국지1)"),
_T("60 소소(환상삼국지1)"),
_T("★팔콤 로고"),
_T("★유저조이 로고"),
_T("★오프닝"),
_T("35 (알 수 없음)")
};

TCHAR tisan2_zh[][128]={
_T("41 主題曲：界線(日語Ver)"),
_T("41 主題曲：界線(中文Ver)"),
_T("45 懸圃：瓊樓玉宇"),
_T("44 大地圖：鴻鵠萬里"),
_T("16 白馬寒潭：碧水洞天"),
_T("12 無界縫細：流雲輕舟"),
_T("01 召德村：曉風"),
_T("11 古皇宮藏道：寒冰夜"),
_T("19 飛凰宮：戰飛凰"),
_T("48 武將出場：萬夫莫敵"),
_T("36 一般戰鬥2：談笑論劍"),
_T("18 鬼界：黃泉夢地"),
_T("34 浪漫愛情曲：月下寄情"),
_T("08 沙暴廢坑"),
_T("09 潼關水路：空山新雨"),
_T("25 濮陽雷澤：暗夜驚雷"),
_T("22 蕭關：潛影"),
_T("20 射日坡：波瀾動"),
_T("21 壽春：一夫當關"),
_T("39 戰場頭目戰鬥：爭鋒"),
_T("30 緊張2(大)：危機四伏"),
_T("32 非慟：離愁恨"),
_T("13 浮月林：清月幽林"),
_T("33 哀愁：相思無盡"),
_T("47 百花樓"),
_T("15 臥雲榻：半日"),
_T("03 洛陽：秋霜"),
_T("23 夏侯：英雄末路"),
_T("07 鎮江：美人含笑"),
_T("27 輕鬆俏皮"),
_T("28 搞笑"),
_T("29 小緊張"),
_T("10 崆峴山：嵐舞"),
_T("14 洛陽西郊棧道：轟"),
_T("06 許都：征前曲"),
_T("02 長安：出巡"),
_T("38 戰場戰鬥：決勝"),
_T("24 官渡：路關險"),
_T("37 一般頭目戰鬥：對峙"),
_T("26 天若宮：天若仙韻"),
_T("04 小沛：春色"),
_T("17 幽妍島：霓裳"),
_T("46 皇宮：皇圖"),
_T("05 徐州：軍陣"),
_T("31 重大打擊：天倫夢斷"),
_T("40 最終頭目戰鬥：探雲霄"),
_T("42 插曲：情衷"),
_T("56 暗思量(幻想三國志1)"),
_T("60 笑笑(幻想三國志1)"),
_T("★法爾康標誌"),
_T("★宇峻奧汀標誌"),
_T("★開場"),
_T("35 (不明)")
};

TCHAR tisan2_ar[][128]={
_T("41 الموضوع: الحدود (النسخة اليابانية)"),
_T("41 الموضوع: الحدود (النسخة الصينية)"),
_T("45 حديقة معلقة: قصر اليشم"),
_T("44 خريطة العالم: أفق واسع"),
_T("16 بركة الحصان الأبيض: مياه زرقاء"),
_T("12 بلا حدود: سحب خفيفة"),
_T("01 قرية تشاودي: رياح الفجر"),
_T("11 طريق القصر القديم: ليلة الجليد"),
_T("19 قصر فيهوانغ: العنقاء الطائرة"),
_T("48 ظهور الجنرال: لا يقهر"),
_T("36 المعركة العادية 2: حديث السيف"),
_T("18 عالم الأرواح: حلم الآخرة"),
_T("34 رومانسية: مشاعر تحت ضوء القمر"),
_T("08 صحراء العاصفة الرملية"),
_T("09 ممر تونغ المائي: مطر الجبل"),
_T("25 مستنقع بويانغ لي: رعد ليلي"),
_T("22 شياوقوان: ظل مخفي"),
_T("20 منحدر شيري: أمواج"),
_T("21 شوتشون: واحد ضد الجميع"),
_T("39 معركة زعيم الميدان: تنافس"),
_T("30 التوتر 2 (كبرى): خطر في كل مكان"),
_T("32 حزن: ألم الوداع"),
_T("13 غابة القمر العائم: غابة هادئة"),
_T("33 كآبة: شوق لا نهاية له"),
_T("47 برج المائة زهرة"),
_T("15 راحة السحاب: نصف يوم"),
_T("03 لويانغ: صقيع الخريف"),
_T("23 شياهو: نهاية البطل"),
_T("07 تشن جيانغ: ابتسامة الجمال"),
_T("27 خفيف ومرح"),
_T("28 كوميديا"),
_T("29 توتر طفيف"),
_T("10 جبل كونغ شيان: رقصة العاصفة"),
_T("14 الطريق الغربي للويانغ: هدير"),
_T("06 شودو: أغنية المسيرة"),
_T("02 تشانغ آن: موكب ملكي"),
_T("38 معركة الميدان: حاسمة"),
_T("24 قواندو: ممر خطير"),
_T("37 معركة زعيم عادية: مواجهة"),
_T("26 قصر تيان رو: لحن سماوي"),
_T("04 شياوبي: ألوان الربيع"),
_T("17 جزيرة يويان: ثوب قوس قزح"),
_T("46 القصر الإمبراطوري: الحلم الإمبراطوري"),
_T("05 شوتشو: تشكيل عسكري"),
_T("31 ضربة كبرى: أحلام محطمة"),
_T("40 معركة الزعيم النهائي: بلوغ السحاب"),
_T("42 استراحة: مشاعر حقيقية"),
_T("56 أفكار مظلمة (Fantasy Sanguo 1)"),
_T("60 ابتسامة (Fantasy Sanguo 1)"),
_T("★شعار فالكوم"),
_T("★شعار يوزر جووي"),
_T("★المقدمة"),
_T("35 (غير معروف)")
};

TCHAR tisan2_ru[][128]={
_T("41 Тема: Граница (Японская Вер.)"),
_T("41 Тема: Граница (Китайская Вер.)"),
_T("45 Висячий Сад: Нефритовый Дворец"),
_T("44 Карта Мира: Широкий Горизонт"),
_T("16 Холодный Пруд Белой Лошади: Синие Воды"),
_T("12 Безграничный: Лёгкие Облака"),
_T("01 Деревня Чжаодэ: Рассветный Ветер"),
_T("11 Путь Древнего Дворца: Ледяная Ночь"),
_T("19 Дворец Фэйхуан: Летящий Феникс"),
_T("48 Появление Генерала: Непобедимый"),
_T("36 Обычная Битва 2: Беседа о Мечах"),
_T("18 Царство Духов: Сон о Загробье"),
_T("34 Романтика: Чувства при Луне"),
_T("08 Пустыня Песчаной Бури"),
_T("09 Водный Путь Тун: Горный Дождь"),
_T("25 Болото Пуян Лэй: Ночной Гром"),
_T("22 Сяогуань: Скрытая Тень"),
_T("20 Склон Шэри: Волны"),
_T("21 Шоучунь: Один против Всех"),
_T("39 Полевая Битва с Боссом: Состязание"),
_T("30 Напряжение 2 (Большое): Опасность Везде"),
_T("32 Печаль: Боль Разлуки"),
_T("13 Лес Плывущей Луны: Тихий Лес"),
_T("33 Меланхолия: Бесконечная Тоска"),
_T("47 Башня Ста Цветов"),
_T("15 Облачный Покой: Полдня"),
_T("03 Лоян: Осенний Иней"),
_T("23 Сяхоу: Конец Героя"),
_T("07 Чжэньцзян: Улыбка Красавицы"),
_T("27 Лёгкий и Игривый"),
_T("28 Комедия"),
_T("29 Лёгкое Напряжение"),
_T("10 Гора Кунсянь: Танец Бури"),
_T("14 Западная Дорога Лояна: Рёв"),
_T("06 Сюйду: Маршевая Песня"),
_T("02 Чанъань: Королевская Процессия"),
_T("38 Полевая Битва: Решающая"),
_T("24 Гуаньду: Опасный Проход"),
_T("37 Обычная Битва с Боссом: Противостояние"),
_T("26 Дворец Тяньжо: Небесная Мелодия"),
_T("04 Сяопэй: Весенние Краски"),
_T("17 Остров Юянь: Радужное Платье"),
_T("46 Императорский Дворец: Императорская Мечта"),
_T("05 Сюйчжоу: Военный Строй"),
_T("31 Тяжёлый Удар: Разбитые Мечты"),
_T("40 Финальная Битва с Боссом: Достичь Облаков"),
_T("42 Интерлюдия: Истинные Чувства"),
_T("56 Тёмные Мысли (Fantasy Sanguo 1)"),
_T("60 Улыбка (Fantasy Sanguo 1)"),
_T("★Логотип FALCOM"),
_T("★Логотип UserJoy"),
_T("★Заставка"),
_T("35 (Неизвестно)")
};

TCHAR tisan2_de[][128]={
_T("41 Thema: Grenzlinie (Japan. Ver)"),
_T("41 Thema: Grenzlinie (Chin. Ver)"),
_T("45 Hängender Garten: Jade-Palast"),
_T("44 Weltkarte: Weiter Horizont"),
_T("16 Weißes Pferd Kaltes Becken: Blaue Gewässer"),
_T("12 Grenzenlos: Leichte Wolken"),
_T("01 Zhaode-Dorf: Morgenwind"),
_T("11 Alter Palastweg: Eisige Nacht"),
_T("19 Feihuang-Palast: Fliegender Phönix"),
_T("48 Generalerscheinung: Unbesiegbar"),
_T("36 Normale Schlacht 2: Schwertgespräch"),
_T("18 Geisterreich: Traum der Unterwelt"),
_T("34 Romanze: Mondlichtgefühle"),
_T("08 Sandsturmwüste"),
_T("09 Tong-Pass-Wasserweg: Bergregen"),
_T("25 Puyang Lei Sumpf: Nach Donner"),
_T("22 Xiaoguan: Versteckter Schatten"),
_T("20 Sheri-Hang: Wellen"),
_T("21 Shouchun: Einer gegen Alle"),
_T("39 Feld-Boss-Schlacht: Wettstreit"),
_T("30 Spannung 2 (Groß): Gefahr Überall"),
_T("32 Kummer: Abschiedsschmerz"),
_T("13 Schwebender Mondwald: Ruhiger Wald"),
_T("33 Melancholie: Endloses Sehnen"),
_T("47 Hundert-Blumen-Turm"),
_T("15 Wolkenruhe: Halber Tag"),
_T("03 Luoyang: Herbstfrost"),
_T("23 Xiahou: Heldens Ende"),
_T("07 Zhenjiang: Lächeln der Schönheit"),
_T("27 Leicht und Verspielt"),
_T("28 Komödie"),
_T("29 Leichte Spannung"),
_T("10 Kongxian-Berg: Sturmtanz"),
_T("14 Luoyang-Weststraße: Dröhnen"),
_T("06 Xudu: Marschlied"),
_T("02 Chang'an: Königlicher Zug"),
_T("38 Feldschlacht: Entschieden"),
_T("24 Guandu: Gefährlicher Pass"),
_T("37 Normale Boss-Schlacht: Konfrontation"),
_T("26 Tianruo-Palast: Himmlische Melodie"),
_T("04 Xiaopei: Frühlingsfarben"),
_T("17 Youyan-Insel: Regenbogenkleid"),
_T("46 Kaiserpalast: Kaiserlicher Traum"),
_T("05 Xuzhou: Militärische Formation"),
_T("31 Schwerer Schlag: Zerbrochene Träume"),
_T("40 Endboss-Schlacht: Wolken Erreichen"),
_T("42 Zwischenspiel: Wahre Gefühle"),
_T("56 Dunkle Gedanken (Fantasy Sanguo 1)"),
_T("60 Lächeln (Fantasy Sanguo 1)"),
_T("★FALCOM Logo"),
_T("★UserJoy Logo"),
_T("★Eröffnung"),
_T("35 (Unbekannt)")
};

TCHAR tisan2_pt[][128]={
_T("41 Tema: Linha Fronteiriça (Ver Japonês)"),
_T("41 Tema: Linha Fronteiriça (Ver Chinês)"),
_T("45 Jardim Suspenso: Palácio de Jade"),
_T("44 Mapa do Mundo: Horizonte Vasto"),
_T("16 Piscina do Cavalo Branco: Águas Azuis"),
_T("12 Sem Limites: Nuvens Leves"),
_T("01 Vila Zhaode: Vento da Aurora"),
_T("11 Caminho do Palácio Antigo: Noite de Gelo"),
_T("19 Palácio Feihuang: Fênix Voadora"),
_T("48 Aparição do General: Invencível"),
_T("36 Batalha Normal 2: Conversa de Espadas"),
_T("18 Reino dos Espíritos: Sonho do Além"),
_T("34 Romance: Sentimentos ao Luar"),
_T("08 Deserto de Tempestade de Areia"),
_T("09 Via Aquática de Tong: Chuva de Montanha"),
_T("25 Pântano Puyang Lei: Trovão Noturno"),
_T("22 Xiaoguan: Sombra Escondida"),
_T("20 Encosta Sheri: Ondas"),
_T("21 Shouchun: Um Contra Todos"),
_T("39 Batalha Boss de Campo: Competição"),
_T("30 Tensão 2 (Maior): Perigo em Todo Lugar"),
_T("32 Tristeza: Dor de Despedida"),
_T("13 Floresta da Lua Flutuante: Bosque Silencioso"),
_T("33 Melancolia: Saudade Infinita"),
_T("47 Torre das Cem Flores"),
_T("15 Descanso das Nuvens: Meio Dia"),
_T("03 Luoyang: Geada de Outono"),
_T("23 Xiahou: Fim do Herói"),
_T("07 Zhenjiang: Sorriso da Beleza"),
_T("27 Leve e Brincalhão"),
_T("28 Comédia"),
_T("29 Tensão Menor"),
_T("10 Monte Kongxian: Dança da Tempestade"),
_T("14 Estrada Ocidental de Luoyang: Rugido"),
_T("06 Xudu: Canção de Marcha"),
_T("02 Chang'an: Procissão Real"),
_T("38 Batalha de Campo: Decisiva"),
_T("24 Guandu: Passagem Perigosa"),
_T("37 Batalha Boss Normal: Confronto"),
_T("26 Palácio Tianruo: Melodia Celestial"),
_T("04 Xiaopei: Cores da Primavera"),
_T("17 Ilha Youyan: Vestido Arco-íris"),
_T("46 Palácio Imperial: Sonho Imperial"),
_T("05 Xuzhou: Formação Militar"),
_T("31 Golpe Maior: Sonhos Quebrados"),
_T("40 Batalha Boss Final: Alcançar as Nuvens"),
_T("42 Interlúdio: Verdadeiros Sentimentos"),
_T("56 Pensamentos Sombrios (Fantasy Sanguo 1)"),
_T("60 Sorriso (Fantasy Sanguo 1)"),
_T("★Logo FALCOM"),
_T("★Logo UserJoy"),
_T("★Abertura"),
_T("35 (Desconhecido)")
};

TCHAR tisan2_nl[][128]={
_T("41 Thema: Grenslijn (Japanse Ver)"),
_T("41 Thema: Grenslijn (Chinese Ver)"),
_T("45 Hangende Tuin: Jaden Paleis"),
_T("44 Wereldkaart: Wijde Horizon"),
_T("16 Wit Paard Koude Poel: Blauwe Wateren"),
_T("12 Grenzeloos: Lichte Wolken"),
_T("01 Zhaode Dorp: Dageraadswind"),
_T("11 Oud Paleispad: IJzige Nacht"),
_T("19 Feihuang Paleis: Vliegende Feniks"),
_T("48 Generaal Verschijning: Onverslaanbaar"),
_T("36 Normale Slag 2: Zwaard Gesprek"),
_T("18 Geestenrijk: Droom van het Hiernamaals"),
_T("34 Romanse: Maanlicht Gevoelens"),
_T("08 Zandstorm Woestenij"),
_T("09 Tong Pass Waterweg: Bergregen"),
_T("25 Puyang Lei Moeras: Nachtelijke Donder"),
_T("22 Xiaoguan: Verborgen Schaduw"),
_T("20 Sheri Helling: Golven"),
_T("21 Shouchun: Eén tegen Allen"),
_T("39 Veld Boss Slag: Wedstrijd"),
_T("30 Spanning 2 (Groot): Gevaar Overal"),
_T("32 Verdriet: Afscheidspijn"),
_T("13 Zwevende Maan Bos: Stille Bossen"),
_T("33 Melancholie: Eindeloze Verlangen"),
_T("47 Honderd Bloemen Toren"),
_T("15 Wolk Rúst: Halve Dag"),
_T("03 Luoyang: Herfstvorst"),
_T("23 Xiahou: Helden einde"),
_T("07 Zhenjiang: Schoonheid Glimlach"),
_T("27 Licht en Speels"),
_T("28 Komedie"),
_T("29 Kleine Spanning"),
_T("10 Kongxian Berg: Storm Dans"),
_T("14 Luoyang Westelijke Weg: Gebrul"),
_T("06 Xudu: Marslied"),
_T("02 Chang'an: Koninklijke Optocht"),
_T("38 Veld Slag: Beslissend"),
_T("24 Guandu: Gevaarlijke Pas"),
_T("37 Normale Boss Slag: Confrontatie"),
_T("26 Tianruo Paleis: Hemelse Melodie"),
_T("04 Xiaopei: Lente Kleuren"),
_T("17 Youyan Eiland: Regenboog Jurk"),
_T("46 Keizerlijk Paleis: Keizerlijke Droom"),
_T("05 Xuzhou: Militaire Formatie"),
_T("31 Grote Klap: Gebroken Dromen"),
_T("40 Eindbaas Slag: Wolken Bereiken"),
_T("42 Tussenspel: Ware Gevoelens"),
_T("56 Donkere Gedachten (Fantasy Sanguo 1)"),
_T("60 Glimlach (Fantasy Sanguo 1)"),
_T("★FALCOM Logo"),
_T("★UserJoy Logo"),
_T("★Opening"),
_T("35 (Onbekend)")
};

TCHAR tisan2_pl[][128]={
_T("41 Motyw: Linia Graniczna (Ver Jap.)"),
_T("41 Motyw: Linia Graniczna (Ver Chiń.)"),
_T("45 Wiszący Ogród: Pałac Jadeitowy"),
_T("44 Mapa Świata: Szeroki Horyzont"),
_T("16 Basen Białego Konia: Błękitne Wody"),
_T("12 Bez Granic: Lekkie Chmury"),
_T("01 Wieś Zhaode: Wiatr Świtu"),
_T("11 Ścieżka Starego Pałacu: Lodowata Noc"),
_T("19 Pałac Feihuang: Latający Feniks"),
_T("48 Pojawienie Generała: Niezwyciężony"),
_T("36 Normalna Bitwa 2: Rozmowa o Mieczach"),
_T("18 Królestwo Duchów: Sen Zaświatów"),
_T("34 Romans: Uczucia przy Księżycu"),
_T("08 Pustynia Burzy Piaskowej"),
_T("09 Droga Wodna Tong: Deszcz Górski"),
_T("25 Bagno Puyang Lei: Nocny Grzmot"),
_T("22 Xiaoguan: Ukryty Cień"),
_T("20 Zbocze Sheri: Fale"),
_T("21 Shouchun: Jeden przeciw Wszystkim"),
_T("39 Bitwa Boss Pola: Rywalizacja"),
_T("30 Napięcie 2 (Duże): Niebezpieczeństwo Wszędzie"),
_T("32 Smutek: Ból Pożegnania"),
_T("13 Las Pływającego Księżyca: Cichy Las"),
_T("33 Melancholia: Nieskończona Tęsknota"),
_T("47 Wieża Stu Kwiatów"),
_T("15 Spoczynek Chmur: Pół Dnia"),
_T("03 Luoyang: Jesienny Mróz"),
_T("23 Xiahou: Koniec Bohatera"),
_T("07 Zhenjiang: Uśmiech Piękności"),
_T("27 Lekki i Zabawowy"),
_T("28 Komedia"),
_T("29 Drobne Napięcie"),
_T("10 Góra Kongxian: Taniec Burzy"),
_T("14 Zachodnia Droga Luoyang: Ryk"),
_T("06 Xudu: Marszowa Pieśń"),
_T("02 Chang'an: Królewski Orszak"),
_T("38 Bitwa Pola: Decydująca"),
_T("24 Guandu: Niebezpieczny Przejazd"),
_T("37 Normalna Bitwa Boss: Konfrontacja"),
_T("26 Pałac Tianruo: Niebiańska Melodia"),
_T("04 Xiaopei: Wiosenne Kolory"),
_T("17 Wyspa Youyan: Suknia Tęczowa"),
_T("46 Pałac Cesarski: Cesarski Sen"),
_T("05 Xuzhou: Formacja Wojskowa"),
_T("31 Mocne Uderzenie: Złamane Marzenia"),
_T("40 Bitwa Końcowego Bossa: Siegając Chmury"),
_T("42 Wstawka: Prawdziwe Uczucia"),
_T("56 Mroczne Myśli (Fantasy Sanguo 1)"),
_T("60 Uśmiech (Fantasy Sanguo 1)"),
_T("★Logo FALCOM"),
_T("★Logo UserJoy"),
_T("★Otwarcie"),
_T("35 (Nieznany)")
};

TCHAR tisan2_tr[][128]={
_T("41 Tema: Sınır Çizgisi (Japonca Ver)"),
_T("41 Tema: Sınır Çizgisi (Çince Ver)"),
_T("45 Asılı Bahçe: Yeşim Sarayı"),
_T("44 Dünya Haritası: Geniş Ufuk"),
_T("16 Beyaz At Soğuk Havuz: Mavi Sular"),
_T("12 Sınırsız: Hafif Bulutlar"),
_T("01 Zhaode Köyü: Şafak Rüzgarı"),
_T("11 Eski Saray Yolu: Buz Gecesi"),
_T("19 Feihuang Sarayı: Uçan Anka"),
_T("48 General Görünümü: Yenilmez"),
_T("36 Normal Savaş 2: Kılıç Sohbeti"),
_T("18 Hayalet Diyarı: Öbür Dünya Rüyası"),
_T("34 Romantizm: Ay Işığında Duygular"),
_T("08 Kum Fırtınası Çölü"),
_T("09 Tong Geçidi Suyolu: Dağ Yağmuru"),
_T("25 Puyang Lei Bataklığı: Gece Gök Gürültüsü"),
_T("22 Xiaoguan: Gizli Gölge"),
_T("20 Sheri Yokuşu: Dalgalar"),
_T("21 Shouchun: Bir Karşı Hepsi"),
_T("39 Saha Patron Savaşı: Mücadele"),
_T("30 Gerilim 2 (Büyük): Her Yerde Tehlike"),
_T("32 Keder: Ayrılık Acısı"),
_T("13 Yüzen Ay Ormanı: Sessiz Orman"),
_T("33 Melankoli: Sonsuz Özlem"),
_T("47 Yüz Çiçek Kulesi"),
_T("15 Bulut Dinlenmesi: Yarım Gün"),
_T("03 Luoyang: Sonbahar Donu"),
_T("23 Xiahou: Kahramanın Sonu"),
_T("07 Zhenjiang: Güzellik Gülümsemesi"),
_T("27 Hafif ve Şakacı"),
_T("28 Komedi"),
_T("29 Küçük Gerilim"),
_T("10 Kongxian Dağı: Fırtına Dansı"),
_T("14 Luoyang Batı Yolu: Kükreme"),
_T("06 Xudu: Yürüyüş Şarkısı"),
_T("02 Chang'an: Kraliyet Geçidi"),
_T("38 Saha Savaşı: Kararlı"),
_T("24 Guandu: Tehlikeli Geçit"),
_T("37 Normal Patron Savaşı: Karşı Karşıya"),
_T("26 Tianruo Sarayı: Göksel Melodi"),
_T("04 Xiaopei: Bahar Renkleri"),
_T("17 Youyan Adası: Gökkuşağı Elbisesi"),
_T("46 İmparatorluk Sarayı: İmparatorluk Rüyası"),
_T("05 Xuzhou: Askeri Düzen"),
_T("31 Büyük Darbe: Kırık Rüyalar"),
_T("40 Final Patron Savaşı: Bulutlara Ulaşmak"),
_T("42 Ara Bölüm: Gerçek Duygular"),
_T("56 Karanlık Düşünceler (Fantasy Sanguo 1)"),
_T("60 Gülümseme (Fantasy Sanguo 1)"),
_T("★FALCOM Logosu"),
_T("★UserJoy Logosu"),
_T("★Açılış"),
_T("35 (Bilinmiyor)")
};

static inline CString San2Track(int i) {
	switch (savedata.lang) {
		case 0: return CString(tisan2[i]);
		case 1: return CString(tisan2_en[i]);
		case 2: return CString(tisan2_fr[i]);
		case 3: return CString(tisan2_it[i]);
		case 4: return CString(tisan2_es[i]);
		case 5: return CString(tisan2_ko[i]);
		case 6: return CString(tisan2_zh[i]);
		case 7: return CString(tisan2_ar[i]);
		case 8: return CString(tisan2_ru[i]);
		case 9: return CString(tisan2_de[i]);
		case 10: return CString(tisan2_pt[i]);
		case 11: return CString(tisan2_nl[i]);
		case 12: return CString(tisan2_pl[i]);
		case 13: return CString(tisan2_tr[i]);
		default: return CString(tisan2_en[i]);
	}
}

CString CSan2::Gett(int a){
	CString s,ss;
	s = San2Track(a);
	ss=s.Left(2);ss.TrimRight();
	fnn=s.Mid(3);
	return ss;
}

/////////////////////////////////////////////////////////////////////////////
// CZWEIII メッセージ ハンドラ
void CSan2::OnDblclkList1() 
{
	// TODO: この位置にコントロール通知ハンドラ用のコードを追加してください
	int idx=m_list.GetItemData(m_list.GetCurSel());
	CString s;	s = San2Track(idx);
	ret=s.Left(2); ret.TrimRight();
	ret2=m_list.GetCurSel();
#if UNICODE
	if(s.Left(1)=="★"){
		fnn=s.Mid(1);
#else
	if(s.Left(2)=="★"){
		fnn=s.Mid(2);
#endif
	}else{
		fnn=s.Mid(3);
	}
	EndDialog(1567);
}

BOOL CSan2::OnInitDialog() 
{
	CCustomBlurDialogBase::OnInitDialog();
	SetWindowText(LL14(L"幻想三国志２", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"환상삼국지 2", L"幻想三国志2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2", L"Fantasy Sanguo 2"));
	SetDlgItemText(IDOK, LL14(L"閉じる", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close"));
	SetDlgItemText(IDC_STATIC, LL14(L"動画(★印)を再生するにはBinkの環境が必要です\nreadme.txtを読んで導入してください。", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup.", L"Bink runtime required for video (★) playback.\nSee readme.txt for setup."));
	
	// TODO: この位置に初期化の補足処理を追加してください
	int dx;
	for(int i=0;i<(50+3);i++)
	{
		CString s = San2Track(i);
		dx= m_list.AddString(s);
		m_list.SetItemData(dx,i);	
	}

	m_list.SetCurSel(0);
	if(ret2!=0) 
//		if(ret>65) m_list.SetCurSel(ret);
//		else m_list.SetCurSel(ret-1);
		m_list.SetCurSel(ret2);
	m_list.SetFocus();
	return FALSE;  // コントロールにフォーカスを設定しないとき、戻り値は TRUE となります
	              // 例外: OCX プロパティ ページの戻り値は FALSE となります
}
