// Sor.cpp : 実装ファイル
//

#include "stdafx.h"
#include "ogg.h"
#include "Sor.h"


// CSor ダイアログ

IMPLEMENT_DYNAMIC(CSor, CCustomDialog)

CSor::CSor(CWnd* pParent /*=NULL*/)
	: CCustomDialog(CSor::IDD, pParent)
{

}

CSor::~CSor()
{
}

void CSor::DoDataExchange(CDataExchange* pDX)
{
	CCustomDialog::DoDataExchange(pDX);
	DDX_Control(pDX, IDC_LIST1, m_list);
	DDX_Control(pDX, IDOK, m_okdummy);
}

#include "CImageBase.h"
BEGIN_MESSAGE_MAP(CSor, CCustomDialog)
	ON_LBN_DBLCLK(IDC_LIST1, OnDblclkList1)
	cmn(CSor);


// CSor メッセージ ハンドラ
extern CString fnn;

TCHAR tisor[][128] = {
L"SSO001 オープニング",
L"SSO002 城 (ここで逢えるね)",
L"SSO003 町1",
L"SSO004 町2",
L"SSO008 トラベラーズ・イン",
L"SSO059 シナリオクリア",
L"SSO005 消えた王様の杖 ダンジョン",
L"SSO006 消えた王様の杖 ヒドラ",
L"SSO007 消えた王様の杖 生還",
L"SSO009 失われたタリスマン 森",
L"SSO010 失われたタリスマン 地下ダンジョン",
L"SSO011 失われたタリスマン 神官テルヒチ",
L"SSO012 失われたタリスマン サンド・マリボー",
L"SSO013 ルシフェルの水門 地下ダンジョン",
L"SSO014 ルシフェルの水門 クラーケン",
L"SSO015 ルシフェルの水門 ブラディー・リバー",
L"SSO016 呪われたオアシス 砂漠",
L"SSO017 呪われたオアシス 砂の城",
L"SSO018 呪われたオアシス ルワンとゴールド・ドラゴン",
L"SSO019 盗賊達の塔 塔",
L"SSO020 盗賊達の塔 地底",
L"SSO021 盗賊達の塔 屋上",
L"SSO022 盗賊達の塔 メジャー・デーモン",
L"SSO023 盗賊達の塔 シャドー・ドラゴン",
L"SSO024 盗賊達の塔 封印",
L"SSO025 暗き沼の魔法使い 暗き沼",
L"SSO026 暗き沼の魔法使い レッド・ドラゴン",
L"SSO027 ロマンシア ロマンシア王国",
L"SSO028 ロマンシア ロマンシア城",
L"SSO029 ロマンシア アゾルバ王国",
L"SSO030 ロマンシア ヴァイデス",
L"SSO060 ロマンシア専用クリア",
L"SSO031 紅玉の謎 森",
L"SSO032 紅玉の謎 モス・ジャイアント",
L"SSO033 紅玉の謎 平和な森",
L"SSO034 暗黒の魔道士 ダンジョン",
L"SSO035 暗黒の魔道士 ゲディス",
L"SSO064 暗黒の魔道士 ゲディスII",
L"SSO036 暗黒の魔道士 ブルー・ドラゴン",
L"SSO037 呪われたクイーンマリー号 船内",
L"SSO038 呪われたクイーンマリー号 上陸後",
L"SSO039 呪われたクイーンマリー号 アーク・デーモン",
L"SSO040 天の神々たち 村",
L"SSO041 天の神々たち コンバット・シーン",
L"SSO042 天の神々たち 天上界",
L"SSO043 天の神々たち 竪琴",
L"SSO044 天の神々たち エビル=シャーマン",
L"SSO045 氷の洞窟 洞窟",
L"SSO046 氷の洞窟 洞窟II",
L"SSO047 氷の洞窟 エキム",
L"SSO048 メデューサの首 森",
L"SSO049 メデューサの首 村",
L"SSO050 メデューサの首 メデューサ",
L"SSO051 囚われた魔法使い 地下要塞",
L"SSO052 囚われた魔法使い ファイヤー・エレメント",
L"SSO053 不老長寿の水 生きている洞窟",
L"SSO054 不老長寿の水 動く心臓",
L"SSO055 不老長寿の水 ダブル=デビルス",
L"SSO056 キング・ドラゴン",
L"SSO057 エンディングI",
L"SSO058 エンディングII",
L"SSO066 新オープニング",
L"SSO080 ある魔術師の失敗 鉱山の地底湖",
L"SSO081 ある魔術師の失敗 アースエレメンタル",
L"SSO083 真夜中に鐘は鳴る ランドル村",
L"SSO084 真夜中に鐘は鳴る 教会",
L"SSO085 真夜中に鐘は鳴る ザキュレイア",
L"SSO086 真夜中に鐘は鳴る 魔術士ゲラン",
L"SSO087 ドワーフの置き土産 ドワーフの迷宮",
L"SSO088 ドワーフの置き土産 ラビリンス・ドラゴン",
L"SSO089 妖精の大樹を救え 妖精たちの村",
L"SSO090 妖精の大樹を救え 巨大樹木内部",
L"SSO091 妖精の大樹を救え センティピード",
L"SSO092 招かれざる来訪者 怪しげな島",
L"SSO093 招かれざる来訪者 アーク・デーモン",
L"SSO082 フォーエバー シナリオ１～５クリア"
};

TCHAR tisor_en[][128] = {
L"SSO001 Opening",
L"SSO002 Castle (We'll Meet Here)",
L"SSO003 Town 1",
L"SSO004 Town 2",
L"SSO008 Travelers' Inn",
L"SSO059 Scenario Clear",
L"SSO005 Lost King's Staff Dungeon",
L"SSO006 Lost King's Staff Hydra",
L"SSO007 Lost King's Staff Survival",
L"SSO009 Lost Talisman Forest",
L"SSO010 Lost Talisman Underground Dungeon",
L"SSO011 Lost Talisman Priest Terhichi",
L"SSO012 Lost Talisman Sand Marlborough",
L"SSO013 Lucifer's Watergate Underground Dungeon",
L"SSO014 Lucifer's Watergate Kraken",
L"SSO015 Lucifer's Watergate Bloody River",
L"SSO016 Cursed Oasis Desert",
L"SSO017 Cursed Oasis Sand Castle",
L"SSO018 Cursed Oasis Ruan and Gold Dragon",
L"SSO019 Tower of Thieves Tower",
L"SSO020 Tower of Thieves Underground",
L"SSO021 Tower of Thieves Rooftop",
L"SSO022 Tower of Thieves Major Demon",
L"SSO023 Tower of Thieves Shadow Dragon",
L"SSO024 Tower of Thieves Seal",
L"SSO025 Wizard of Dark Marsh Dark Marsh",
L"SSO026 Wizard of Dark Marsh Red Dragon",
L"SSO027 Romancia Romancia Kingdom",
L"SSO028 Romancia Romancia Castle",
L"SSO029 Romancia Azolba Kingdom",
L"SSO030 Romancia Vaides",
L"SSO060 Romancia Exclusive Clear",
L"SSO031 Mystery of the Ruby Forest",
L"SSO032 Mystery of the Ruby Moss Giant",
L"SSO033 Mystery of the Ruby Peaceful Forest",
L"SSO034 Dark Mage Dungeon",
L"SSO035 Dark Mage Gedis",
L"SSO064 Dark Mage Gedis II",
L"SSO036 Dark Mage Blue Dragon",
L"SSO037 Cursed Queen Mary Ship Interior",
L"SSO038 Cursed Queen Mary After Landing",
L"SSO039 Cursed Queen Mary Arc Demon",
L"SSO040 Gods of Heaven Village",
L"SSO041 Gods of Heaven Combat Scene",
L"SSO042 Gods of Heaven Heavenly Realm",
L"SSO043 Gods of Heaven Harp",
L"SSO044 Gods of Heaven Evil Shaman",
L"SSO045 Ice Cave Cave",
L"SSO046 Ice Cave Cave II",
L"SSO047 Ice Cave Ekim",
L"SSO048 Medusa's Head Forest",
L"SSO049 Medusa's Head Village",
L"SSO050 Medusa's Head Medusa",
L"SSO051 Imprisoned Mage Underground Fortress",
L"SSO052 Imprisoned Mage Fire Elemental",
L"SSO053 Water of Eternal Youth Living Cave",
L"SSO054 Water of Eternal Youth Beating Heart",
L"SSO055 Water of Eternal Youth Double Devils",
L"SSO056 King Dragon",
L"SSO057 Ending I",
L"SSO058 Ending II",
L"SSO066 New Opening",
L"SSO080 A Wizard's Failure Mine Underground Lake",
L"SSO081 A Wizard's Failure Earth Elemental",
L"SSO083 Midnight Bell Rings Randle Village",
L"SSO084 Midnight Bell Rings Church",
L"SSO085 Midnight Bell Rings Zaquria",
L"SSO086 Midnight Bell Rings Mage Geran",
L"SSO087 Dwarf's Legacy Dwarf Maze",
L"SSO088 Dwarf's Legacy Labyrinth Dragon",
L"SSO089 Save the Fairy Tree Fairy Village",
L"SSO090 Save the Fairy Tree Giant Tree Interior",
L"SSO091 Save the Fairy Tree Centipede",
L"SSO092 Unwelcome Visitors Suspicious Island",
L"SSO093 Unwelcome Visitors Arc Demon",
L"SSO082 Forever Scenario 1~5 Clear"
};

TCHAR tisor_fr[][128] = {
L"SSO001 Ouverture",
L"SSO002 Château (On Se Retrouvera Ici)",
L"SSO003 Ville 1",
L"SSO004 Ville 2",
L"SSO008 Auberge des Voyageurs",
L"SSO059 Scénario Terminé",
L"SSO005 Sceptre du Roi Perdu Donjon",
L"SSO006 Sceptre du Roi Perdu Hydre",
L"SSO007 Sceptre du Roi Perdu Survie",
L"SSO009 Talisman Perdu Forêt",
L"SSO010 Talisman Perdu Donjon Souterrain",
L"SSO011 Talisman Perdu Prêtre Terhichi",
L"SSO012 Talisman Perdu Sand Marlborough",
L"SSO013 Écluse de Lucifer Donjon Souterrain",
L"SSO014 Écluse de Lucifer Kraken",
L"SSO015 Écluse de Lucifer Rivière Sanglante",
L"SSO016 Oasis Maudite Désert",
L"SSO017 Oasis Maudite Château de Sable",
L"SSO018 Oasis Maudite Ruan et Dragon d'Or",
L"SSO019 Tour des Voleurs Tour",
L"SSO020 Tour des Voleurs Souterrain",
L"SSO021 Tour des Voleurs Toit",
L"SSO022 Tour des Voleurs Démon Majeur",
L"SSO023 Tour des Voleurs Dragon des Ombres",
L"SSO024 Tour des Voleurs Sceau",
L"SSO025 Sorcier du Marais Noir Marais Noir",
L"SSO026 Sorcier du Marais Noir Dragon Rouge",
L"SSO027 Romancia Royaume de Romancia",
L"SSO028 Romancia Château de Romancia",
L"SSO029 Romancia Royaume d'Azolba",
L"SSO030 Romancia Vaides",
L"SSO060 Déblocage Exclusif Romancia",
L"SSO031 Mystère du Rubis Forêt",
L"SSO032 Mystère du Rubis Géant de Mousse",
L"SSO033 Mystère du Rubis Forêt Paisible",
L"SSO034 Mage Noir Donjon",
L"SSO035 Mage Noir Gedis",
L"SSO064 Mage Noir Gedis II",
L"SSO036 Mage Noir Dragon Bleu",
L"SSO037 Reine Mary Maudite Intérieur du Navire",
L"SSO038 Reine Mary Maudite Après Débarquement",
L"SSO039 Reine Mary Maudite Démon Arcanique",
L"SSO040 Dieux du Ciel Village",
L"SSO041 Dieux du Ciel Scène de Combat",
L"SSO042 Dieux du Ciel Royaume Céleste",
L"SSO043 Dieux du Ciel Harpe",
L"SSO044 Dieux du Ciel Chaman Maléfique",
L"SSO045 Grotte de Glace Grotte",
L"SSO046 Grotte de Glace Grotte II",
L"SSO047 Grotte de Glace Ekim",
L"SSO048 Tête de Méduse Forêt",
L"SSO049 Tête de Méduse Village",
L"SSO050 Tête de Méduse Méduse",
L"SSO051 Mage Emprisonné Forteresse Souterraine",
L"SSO052 Mage Emprisonné Élémentaire de Feu",
L"SSO053 Eau de Jouvence Grotte Vivante",
L"SSO054 Eau de Jouvence Cœur Battant",
L"SSO055 Eau de Jouvence Double Démons",
L"SSO056 Roi Dragon",
L"SSO057 Final I",
L"SSO058 Final II",
L"SSO066 Nouvelle Ouverture",
L"SSO080 Échec d'un Magicien Lac Souterrain de Mine",
L"SSO081 Échec d'un Magicien Élémentaire de Terre",
L"SSO083 Minuit Sonne Cloche Village Randle",
L"SSO084 Minuit Sonne Cloche Église",
L"SSO085 Minuit Sonne Cloche Zaquria",
L"SSO086 Minuit Sonne Cloche Mage Geran",
L"SSO087 Héritage du Nain Labyrinthe Nain",
L"SSO088 Héritage du Nain Dragon Labyrinthe",
L"SSO089 Sauvez l'Arbre des Fées Village des Fées",
L"SSO090 Sauvez l'Arbre des Fées Intérieur de l'Arbre Géant",
L"SSO091 Sauvez l'Arbre des Fées Mille-Pattes",
L"SSO092 Visiteurs Indésirables Île Suspecte",
L"SSO093 Visiteurs Indésirables Démon Arcanique",
L"SSO082 Forever Scénario 1~5 Terminé"
};

TCHAR tisor_it[][128] = {
L"SSO001 Apertura",
L"SSO002 Castello (Ci Incontreremo Qui)",
L"SSO003 Città 1",
L"SSO004 Città 2",
L"SSO008 Locanda dei Viaggiatori",
L"SSO059 Scenario Completato",
L"SSO005 Scettro del Re Perduto Dungeon",
L"SSO006 Scettro del Re Perduto Idra",
L"SSO007 Scettro del Re Perduto Sopravvivenza",
L"SSO009 Talismano Perduto Foresta",
L"SSO010 Talismano Perduto Dungeon Sotterraneo",
L"SSO011 Talismano Perduto Sacerdote Terhichi",
L"SSO012 Talismano Perduto Sand Marlborough",
L"SSO013 Chiusa di Lucifero Dungeon Sotterraneo",
L"SSO014 Chiusa di Lucifero Kraken",
L"SSO015 Chiusa di Lucifero Fiume di Sangue",
L"SSO016 Oasi Maledetta Deserto",
L"SSO017 Oasi Maledetta Castello di Sabbia",
L"SSO018 Oasi Maledetta Ruan e Drago d'Oro",
L"SSO019 Torre dei Ladri Torre",
L"SSO020 Torre dei Ladri Sotterraneo",
L"SSO021 Torre dei Ladri Tetto",
L"SSO022 Torre dei Ladri Demone Maggiore",
L"SSO023 Torre dei Ladri Drago dell'Ombra",
L"SSO024 Torre dei Ladri Sigillo",
L"SSO025 Mago della Palude Oscura Palude Oscura",
L"SSO026 Mago della Palude Oscura Drago Rosso",
L"SSO027 Romancia Regno di Romancia",
L"SSO028 Romancia Castello di Romancia",
L"SSO029 Romancia Regno di Azolba",
L"SSO030 Romancia Vaides",
L"SSO060 Completamento Esclusivo Romancia",
L"SSO031 Mistero del Rubino Foresta",
L"SSO032 Mistero del Rubino Gigante di Muschio",
L"SSO033 Mistero del Rubino Foresta Pacifica",
L"SSO034 Mago Oscuro Dungeon",
L"SSO035 Mago Oscuro Gedis",
L"SSO064 Mago Oscuro Gedis II",
L"SSO036 Mago Oscuro Drago Blu",
L"SSO037 Regina Mary Maledetta Interno della Nave",
L"SSO038 Regina Mary Maledetta Dopo lo Sbarco",
L"SSO039 Regina Mary Maledetta Demone Arcano",
L"SSO040 Dei del Cielo Villaggio",
L"SSO041 Dei del Cielo Scena di Combattimento",
L"SSO042 Dei del Cielo Regno Celeste",
L"SSO043 Dei del Cielo Arpa",
L"SSO044 Dei del Cielo Sciamano Malvagio",
L"SSO045 Grotta di Ghiaccio Grotta",
L"SSO046 Grotta di Ghiaccio Grotta II",
L"SSO047 Grotta di Ghiaccio Ekim",
L"SSO048 Testa di Medusa Foresta",
L"SSO049 Testa di Medusa Villaggio",
L"SSO050 Testa di Medusa Medusa",
L"SSO051 Mago Imprigionato Fortezza Sotterranea",
L"SSO052 Mago Imprigionato Elementale di Fuoco",
L"SSO053 Acqua della Giovinezza Grotta Vivente",
L"SSO054 Acqua della Giovinezza Cuore Palpitante",
L"SSO055 Acqua della Giovinezza Doppio Diavoli",
L"SSO056 Re Drago",
L"SSO057 Finale I",
L"SSO058 Finale II",
L"SSO066 Nuova Apertura",
L"SSO080 Fallimento di un Mago Lago Sotterraneo della Miniera",
L"SSO081 Fallimento di un Mago Elementale della Terra",
L"SSO083 Mezzanotte Suona Campana Villaggio Randle",
L"SSO084 Mezzanotte Suona Campana Chiesa",
L"SSO085 Mezzanotte Suona Campana Zaquria",
L"SSO086 Mezzanotte Suona Campana Mago Geran",
L"SSO087 Eredità del Nano Labirinto del Nano",
L"SSO088 Eredità del Nano Drago Labirinto",
L"SSO089 Salva l'Albero delle Fate Villaggio delle Fate",
L"SSO090 Salva l'Albero delle Fate Interno dell'Albero Gigante",
L"SSO091 Salva l'Albero delle Fate Millepiedi",
L"SSO092 Visitatori Indesiderati Isola Sospetta",
L"SSO093 Visitatori Indesiderati Demone Arcano",
L"SSO082 Forever Scenario 1~5 Completato"
};

TCHAR tisor_es[][128] = {
L"SSO001 Apertura",
L"SSO002 Castillo (Nos Veremos Aquí)",
L"SSO003 Pueblo 1",
L"SSO004 Pueblo 2",
L"SSO008 Posada de los Viajeros",
L"SSO059 Escenario Completado",
L"SSO005 Bastón del Rey Perdido Mazmorra",
L"SSO006 Bastón del Rey Perdido Hidra",
L"SSO007 Bastón del Rey Perdido Supervivencia",
L"SSO009 Talismán Perdido Bosque",
L"SSO010 Talismán Perdido Mazmorra Subterránea",
L"SSO011 Talismán Perdido Sacerdote Terhichi",
L"SSO012 Talismán Perdido Sand Marlborough",
L"SSO013 Compuerta de Lucifer Mazmorra Subterránea",
L"SSO014 Compuerta de Lucifer Kraken",
L"SSO015 Compuerta de Lucifer Río Sangriento",
L"SSO016 Oasis Maldito Desierto",
L"SSO017 Oasis Maldito Castillo de Arena",
L"SSO018 Oasis Maldito Ruan y Dragón de Oro",
L"SSO019 Torre de los Ladrones Torre",
L"SSO020 Torre de los Ladrones Subterráneo",
L"SSO021 Torre de los Ladrones Techo",
L"SSO022 Torre de los Ladrones Demonio Mayor",
L"SSO023 Torre de los Ladrones Dragón de Sombras",
L"SSO024 Torre de los Ladrones Sello",
L"SSO025 Mago del Pantano Oscuro Pantano Oscuro",
L"SSO026 Mago del Pantano Oscuro Dragón Rojo",
L"SSO027 Romancia Reino de Romancia",
L"SSO028 Romancia Castillo de Romancia",
L"SSO029 Romancia Reino de Azolba",
L"SSO030 Romancia Vaides",
L"SSO060 Completado Exclusivo Romancia",
L"SSO031 Misterio del Rubí Bosque",
L"SSO032 Misterio del Rubí Gigante de Musgo",
L"SSO033 Misterio del Rubí Bosque Pacífico",
L"SSO034 Mago Oscuro Mazmorra",
L"SSO035 Mago Oscuro Gedis",
L"SSO064 Mago Oscuro Gedis II",
L"SSO036 Mago Oscuro Dragón Azul",
L"SSO037 Reina Mary Maldita Interior del Barco",
L"SSO038 Reina Mary Maldita Tras el Desembarco",
L"SSO039 Reina Mary Maldita Demonio Arcano",
L"SSO040 Dioses del Cielo Aldea",
L"SSO041 Dioses del Cielo Escena de Combate",
L"SSO042 Dioses del Cielo Reino Celestial",
L"SSO043 Dioses del Cielo Arpa",
L"SSO044 Dioses del Cielo Chamán Malévolo",
L"SSO045 Cueva de Hielo Cueva",
L"SSO046 Cueva de Hielo Cueva II",
L"SSO047 Cueva de Hielo Ekim",
L"SSO048 Cabeza de Medusa Bosque",
L"SSO049 Cabeza de Medusa Aldea",
L"SSO050 Cabeza de Medusa Medusa",
L"SSO051 Mago Encarcelado Fortaleza Subterránea",
L"SSO052 Mago Encarcelado Elemental de Fuego",
L"SSO053 Agua de la Eterna Juventud Cueva Viva",
L"SSO054 Agua de la Eterna Juventud Corazón Late",
L"SSO055 Agua de la Eterna Juventud Doble Diablos",
L"SSO056 Rey Dragón",
L"SSO057 Final I",
L"SSO058 Final II",
L"SSO066 Nueva Apertura",
L"SSO080 Fracaso de un Mago Lago Subterráneo de Mina",
L"SSO081 Fracaso de un Mago Elemental de Tierra",
L"SSO083 Medianoche Suenan Campanas Aldea Randle",
L"SSO084 Medianoche Suenan Campanas Iglesia",
L"SSO085 Medianoche Suenan Campanas Zaquria",
L"SSO086 Medianoche Suenan Campanas Mago Geran",
L"SSO087 Legado del Enano Laberinto del Enano",
L"SSO088 Legado del Enano Dragón Laberinto",
L"SSO089 Salva el Árbol de Hadas Aldea de Hadas",
L"SSO090 Salva el Árbol de Hadas Interior del Árbol Gigante",
L"SSO091 Salva el Árbol de Hadas Ciempiés",
L"SSO092 Visitantes Indeseados Isla Sospechosa",
L"SSO093 Visitantes Indeseados Demonio Arcano",
L"SSO082 Forever Escenario 1~5 Completado"
};

TCHAR tisor_ko[][128] = {
L"SSO001 오프닝",
L"SSO002 성 (여기서 만나요)",
L"SSO003 마을 1",
L"SSO004 마을 2",
L"SSO008 여행자의 여관",
L"SSO059 시나리오 클리어",
L"SSO005 사라진 왕의 지팡이 던전",
L"SSO006 사라진 왕의 지팡이 히드라",
L"SSO007 사라진 왕의 지팡이 생환",
L"SSO009 잃어버린 탈리스만 숲",
L"SSO010 잃어버린 탈리스만 지하 던전",
L"SSO011 잃어버린 탈리스만 신관 테르히치",
L"SSO012 잃어버린 탈리스만 샌드 마리보로",
L"SSO013 루시퍼의 수문 지하 던전",
L"SSO014 루시퍼의 수문 크라켄",
L"SSO015 루시퍼의 수문 블러디 리버",
L"SSO016 저주받은 오아시스 사막",
L"SSO017 저주받은 오아시스 모래의 성",
L"SSO018 저주받은 오아시스 루완과 골드 드래곤",
L"SSO019 도적들의 탑 탑",
L"SSO020 도적들의 탑 지하",
L"SSO021 도적들의 탑 옥상",
L"SSO022 도적들의 탑 메이저 데몬",
L"SSO023 도적들의 탑 섀도우 드래곤",
L"SSO024 도적들의 탑 봉인",
L"SSO025 어둠의 늪 마법사 어둠의 늪",
L"SSO026 어둠의 늪 마법사 레드 드래곤",
L"SSO027 로만시아 로만시아 왕국",
L"SSO028 로만시아 로만시아 성",
L"SSO029 로만시아 아졸바 왕국",
L"SSO030 로만시아 바이데스",
L"SSO060 로만시아 전용 클리어",
L"SSO031 홍옥의 수수께끼 숲",
L"SSO032 홍옥의 수수께끼 모스 자이언트",
L"SSO033 홍옥의 수수께끼 평화로운 숲",
L"SSO034 어둠의 마법사 던전",
L"SSO035 어둠의 마법사 게디스",
L"SSO064 어둠의 마법사 게디스 II",
L"SSO036 어둠의 마법사 블루 드래곤",
L"SSO037 저주받은 퀸 메리 호 선내",
L"SSO038 저주받은 퀸 메리 호 상륙 후",
L"SSO039 저주받은 퀸 메리 호 아크 데몬",
L"SSO040 천상의 신들 마을",
L"SSO041 천상의 신들 전투 장면",
L"SSO042 천상의 신들 천상계",
L"SSO043 천상의 신들 하프",
L"SSO044 천상의 신들 이블 샤먼",
L"SSO045 얼음 동굴 동굴",
L"SSO046 얼음 동굴 동굴 II",
L"SSO047 얼음 동굴 에킴",
L"SSO048 메두사의 목 숲",
L"SSO049 메두사의 목 마을",
L"SSO050 메두사의 목 메두사",
L"SSO051 갇힌 마법사 지하 요새",
L"SSO052 갇힌 마법사 파이어 엘리멘탈",
L"SSO053 불로장생의 물 살아있는 동굴",
L"SSO054 불로장생의 물 뛰는 심장",
L"SSO055 불로장생의 물 더블 데빌스",
L"SSO056 킹 드래곤",
L"SSO057 엔딩 I",
L"SSO058 엔딩 II",
L"SSO066 새 오프닝",
L"SSO080 어느 마술사의 실패 광산 지하호",
L"SSO081 어느 마술사의 실패 어스 엘리멘탈",
L"SSO083 한밤중에 종이 울린다 랜들 마을",
L"SSO084 한밤중에 종이 울린다 교회",
L"SSO085 한밤중에 종이 울린다 자큐리아",
L"SSO086 한밤중에 종이 울린다 마술사 게란",
L"SSO087 드워프의 유산 드워프 미궁",
L"SSO088 드워프의 유산 라비린스 드래곤",
L"SSO089 요정의 대수를 구하라 요정 마을",
L"SSO090 요정의 대수를 구하라 거대 나무 내부",
L"SSO091 요정의 대수를 구하라 센티피드",
L"SSO092 불청객 수상한 섬",
L"SSO093 불청객 아크 데몬",
L"SSO082 Forever 시나리오 1~5 클리어"
};

TCHAR tisor_zh[][128] = {
L"SSO001 开场",
L"SSO002 城堡（在此相见）",
L"SSO003 城镇1",
L"SSO004 城镇2",
L"SSO008 旅人之宿",
L"SSO059 剧情通关",
L"SSO005 消失的王杖 地下城",
L"SSO006 消失的王杖 许德拉",
L"SSO007 消失的王杖 生还",
L"SSO009 失落的护身符 森林",
L"SSO010 失落的护身符 地下城",
L"SSO011 失落的护身符 祭司泰尔希奇",
L"SSO012 失落的护身符 桑德马勒堡",
L"SSO013 路西弗水门 地下城",
L"SSO014 路西弗水门 克拉肯",
L"SSO015 路西弗水门 血河",
L"SSO016 诅咒绿洲 沙漠",
L"SSO017 诅咒绿洲 沙之城",
L"SSO018 诅咒绿洲 鲁安与金龙",
L"SSO019 盗贼之塔 塔",
L"SSO020 盗贼之塔 地下",
L"SSO021 盗贼之塔 屋顶",
L"SSO022 盗贼之塔 大恶魔",
L"SSO023 盗贼之塔 暗影龙",
L"SSO024 盗贼之塔 封印",
L"SSO025 暗沼魔法师 暗沼",
L"SSO026 暗沼魔法师 红龙",
L"SSO027 罗曼西亚 罗曼西亚王国",
L"SSO028 罗曼西亚 罗曼西亚城",
L"SSO029 罗曼西亚 阿佐尔巴王国",
L"SSO030 罗曼西亚 瓦伊德斯",
L"SSO060 罗曼西亚专属通关",
L"SSO031 红玉之谜 森林",
L"SSO032 红玉之谜 苔藓巨人",
L"SSO033 红玉之谜 和平森林",
L"SSO034 暗黑魔道士 地下城",
L"SSO035 暗黑魔道士 盖迪斯",
L"SSO064 暗黑魔道士 盖迪斯II",
L"SSO036 暗黑魔道士 蓝龙",
L"SSO037 诅咒玛丽女王号 船内",
L"SSO038 诅咒玛丽女王号 登陆后",
L"SSO039 诅咒玛丽女王号 阿克恶魔",
L"SSO040 天之诸神 村庄",
L"SSO041 天之诸神 战斗场面",
L"SSO042 天之诸神 天界",
L"SSO043 天之诸神 竖琴",
L"SSO044 天之诸神 邪恶魔萨满",
L"SSO045 冰之洞窟 洞窟",
L"SSO046 冰之洞窟 洞窟II",
L"SSO047 冰之洞窟 埃基姆",
L"SSO048 美杜莎之首 森林",
L"SSO049 美杜莎之首 村庄",
L"SSO050 美杜莎之首 美杜莎",
L"SSO051 被囚魔法师 地下要塞",
L"SSO052 被囚魔法师 火元素",
L"SSO053 不老长寿之水 活洞窟",
L"SSO054 不老长寿之水 跳动之心",
L"SSO055 不老长寿之水 双魔",
L"SSO056 龙王",
L"SSO057 结局I",
L"SSO058 结局II",
L"SSO066 新开场",
L"SSO080 某魔术师之失败 矿山地底湖",
L"SSO081 某魔术师之失败 土元素",
L"SSO083 午夜钟鸣 兰德村",
L"SSO084 午夜钟鸣 教会",
L"SSO085 午夜钟鸣 扎库利亚",
L"SSO086 午夜钟鸣 魔术师盖兰",
L"SSO087 矮人遗物 矮人迷宫",
L"SSO088 矮人遗物 迷宫龙",
L"SSO089 拯救妖精之树 妖精村",
L"SSO090 拯救妖精之树 巨树内部",
L"SSO091 拯救妖精之树 蜈蚣",
L"SSO092 不速之客 可疑之岛",
L"SSO093 不速之客 阿克恶魔",
L"SSO082 Forever 剧情1~5通关"
};

TCHAR tisor_ar[][128] = {
L"SSO001 المقدمة",
L"SSO002 القلعة (سنلتقي هنا)",
L"SSO003 المدينة 1",
L"SSO004 المدينة 2",
L"SSO008 نزل المسافرين",
L"SSO059 اكتمال السيناريو",
L"SSO005 عصا الملك المفقود السرداب",
L"SSO006 عصا الملك المفقود هيدرا",
L"SSO007 عصا الملك المفقود البقاء",
L"SSO009 التميمة المفقودة الغابة",
L"SSO010 التميمة المفقودة السرداب السفلي",
L"SSO011 التميمة المفقودة الكاهن تيرهيتشي",
L"SSO012 التميمة المفقودة ساند مارلبورو",
L"SSO013 بوابة لوسيفر السرداب السفلي",
L"SSO014 بوابة لوسيفر كراكن",
L"SSO015 بوابة لوسيفر النهر الدامي",
L"SSO016 واحة ملعونة الصحراء",
L"SSO017 واحة ملعونة قلعة الرمال",
L"SSO018 واحة ملعونة روان والتنين الذهبي",
L"SSO019 برج اللصوص البرج",
L"SSO020 برج اللصوص السفلي",
L"SSO021 برج اللصوص السطح",
L"SSO022 برج اللصوص الشيطان الكبير",
L"SSO023 برج اللصوص تنين الظل",
L"SSO024 برج اللصوص الختم",
L"SSO025 ساحر المستنقع الداكن المستنقع الداكن",
L"SSO026 ساحر المستنقع الداكن التنين الأحمر",
L"SSO027 رومانسيا مملكة رومانسيا",
L"SSO028 رومانسيا قلعة رومانسيا",
L"SSO029 رومانسيا مملكة آزولبا",
L"SSO030 رومانسيا فايدس",
L"SSO060 إكمال حصري رومانسيا",
L"SSO031 لغز الياقوت الغابة",
L"SSO032 لغز الياقوت عملاق الطحالب",
L"SSO033 لغز الياقوت الغابة السلمية",
L"SSO034 الساحر الأسود السرداب",
L"SSO035 الساحر الأسود جيديس",
L"SSO064 الساحر الأسود جيديس II",
L"SSO036 الساحر الأسود التنين الأزرق",
L"SSO037 ملكة ماري الملعونة داخل السفينة",
L"SSO038 ملكة ماري الملعونة بعد الهبوط",
L"SSO039 ملكة ماري الملعونة الشيطان السري",
L"SSO040 آلهة السماء القرية",
L"SSO041 آلهة السماء مشهد القتال",
L"SSO042 آلهة السماء المملكة السماوية",
L"SSO043 آلهة السماء القيثارة",
L"SSO044 آلهة السماء الشامان الشرير",
L"SSO045 كهف الجليد الكهف",
L"SSO046 كهف الجليد الكهف II",
L"SSO047 كهف الجليد إيكيم",
L"SSO048 رأس ميدوسا الغابة",
L"SSO049 رأس ميدوسا القرية",
L"SSO050 رأس ميدوسا ميدوسا",
L"SSO051 الساحر المسجون القلعة السفلية",
L"SSO052 الساحر المسجون عنصر النار",
L"SSO053 ماء الشباب الأبدي الكهف الحي",
L"SSO054 ماء الشباب الأبدي القلب النابض",
L"SSO055 ماء الشباب الأبدي الشيطانان",
L"SSO056 تنين الملك",
L"SSO057 النهاية I",
L"SSO058 النهاية II",
L"SSO066 مقدمة جديدة",
L"SSO080 فشل ساحر بحيرة منجم السفلية",
L"SSO081 فشل ساحر عنصر الأرض",
L"SSO083 جرس منتصف الليل قرية راندل",
L"SSO084 جرس منتصف الليل الكنيسة",
L"SSO085 جرس منتصف الليل زاقوريا",
L"SSO086 جرس منتصف الليل الساحر جيران",
L"SSO087 إرث القزم متاهة الأقزام",
L"SSO088 إرث القزم تنين المتاهة",
L"SSO089 أنقذ شجرة الجن قرية الجن",
L"SSO090 أنقذ شجرة الجن داخل الشجرة العملاقة",
L"SSO091 أنقذ شجرة الجن أودية الأقدام",
L"SSO092 زوار غير مرغوبين جزيرة مشبوهة",
L"SSO093 زوار غير مرغوبين الشيطان السري",
L"SSO082 Forever السيناريو 1~5 مكتمل"
};

TCHAR tisor_ru[][128] = {
L"SSO001 Заставка",
L"SSO002 Замок (Встретимся Здесь)",
L"SSO003 Город 1",
L"SSO004 Город 2",
L"SSO008 Гостиница Путников",
L"SSO059 Сценарий Пройден",
L"SSO005 Посох Потерянного Короля Подземелье",
L"SSO006 Посох Потерянного Короля Гидра",
L"SSO007 Посох Потерянного Короля Выживание",
L"SSO009 Потерянный Талисман Лес",
L"SSO010 Потерянный Талисман Подземное Подземелье",
L"SSO011 Потерянный Талисман Священник Терхичи",
L"SSO012 Потерянный Талисман Сэнд Марлборо",
L"SSO013 Шлюз Люцифера Подземное Подземелье",
L"SSO014 Шлюз Люцифера Кракен",
L"SSO015 Шлюз Люцифера Кровавая Река",
L"SSO016 Проклятый Оазис Пустыня",
L"SSO017 Проклятый Оазис Песчаный Замок",
L"SSO018 Проклятый Оазис Руан и Золотой Дракон",
L"SSO019 Башня Воров Башня",
L"SSO020 Башня Воров Подземелье",
L"SSO021 Башня Воров Крыша",
L"SSO022 Башня Воров Главный Демон",
L"SSO023 Башня Воров Дракон Теней",
L"SSO024 Башня Воров Печать",
L"SSO025 Колдун Тёмного Болота Тёмное Болото",
L"SSO026 Колдун Тёмного Болота Красный Дракон",
L"SSO027 Романсия Королевство Романсия",
L"SSO028 Романсия Замок Романсия",
L"SSO029 Романсия Королевство Азольба",
L"SSO030 Романсия Вайдес",
L"SSO060 Эксклюзивное Прохождение Романсия",
L"SSO031 Тайна Рубина Лес",
L"SSO032 Тайна Рубина Мховый Гигант",
L"SSO033 Тайна Рубина Мирный Лес",
L"SSO034 Тёмный Маг Подземелье",
L"SSO035 Тёмный Маг Гедис",
L"SSO064 Тёмный Маг Гедис II",
L"SSO036 Тёмный Маг Синий Дракон",
L"SSO037 Проклятая Королева Мэри Интерьер Корабля",
L"SSO038 Проклятая Королева Мэри После Высадки",
L"SSO039 Проклятая Королева Мэри Арканный Демон",
L"SSO040 Боги Небес Деревня",
L"SSO041 Боги Небес Боевая Сцена",
L"SSO042 Боги Небес Небесное Царство",
L"SSO043 Боги Небес Арфа",
L"SSO044 Боги Небес Злой Шаман",
L"SSO045 Ледяная Пещера Пещера",
L"SSO046 Ледяная Пещера Пещера II",
L"SSO047 Ледяная Пещера Эким",
L"SSO048 Голова Медузы Лес",
L"SSO049 Голова Медузы Деревня",
L"SSO050 Голова Медузы Медуза",
L"SSO051 Заточенный Маг Подземная Крепость",
L"SSO052 Заточенный Маг Огненный Элементаль",
L"SSO053 Вода Вечной Молодости Живая Пещера",
L"SSO054 Вода Вечной Молодости Бьющееся Сердце",
L"SSO055 Вода Вечной Молодости Двойные Дьяволы",
L"SSO056 Король-Дракон",
L"SSO057 Финал I",
L"SSO058 Финал II",
L"SSO066 Новая Заставка",
L"SSO080 Провал Мага Подземное Озеро Шахты",
L"SSO081 Провал Мага Земляной Элементаль",
L"SSO083 Полночный Колокол Деревня Рандл",
L"SSO084 Полночный Колокол Церковь",
L"SSO085 Полночный Колокол Закурия",
L"SSO086 Полночный Колокол Маг Герана",
L"SSO087 Наследие Гнома Лабиринт Гнома",
L"SSO088 Наследие Гнома Лабиринт Дракон",
L"SSO089 Спасите Дерево Фей Деревня Фей",
L"SSO090 Спасите Дерево Фей Интерьер Гигантского Дерева",
L"SSO091 Спасите Дерево Фей Сороконожка",
L"SSO092 Нежеланные Гости Подозрительный Остров",
L"SSO093 Нежеланные Гости Арканный Демон",
L"SSO082 Forever Сценарий 1~5 Пройден"
};

TCHAR tisor_de[][128] = {
L"SSO001 Eröffnung",
L"SSO002 Schloss (Wir Treffen Uns Hier)",
L"SSO003 Stadt 1",
L"SSO004 Stadt 2",
L"SSO008 Gasthaus der Reisenden",
L"SSO059 Szenario Abgeschlossen",
L"SSO005 Verlorener Königstab Verlies",
L"SSO006 Verlorener Königstab Hydra",
L"SSO007 Verlorener Königstab Überleben",
L"SSO009 Verlorener Talisman Wald",
L"SSO010 Verlorener Talisman Unterirdisches Verlies",
L"SSO011 Verlorener Talisman Priester Terhichi",
L"SSO012 Verlorener Talisman Sand Marlborough",
L"SSO013 Luzifers Schleuse Unterirdisches Verlies",
L"SSO014 Luzifers Schleuse Kraken",
L"SSO015 Luzifers Schleuse Blutiger Fluss",
L"SSO016 Verfluchte Oase Wüste",
L"SSO017 Verfluchte Oase Sandburg",
L"SSO018 Verfluchte Oase Ruan und Golddrache",
L"SSO019 Turm der Diebe Turm",
L"SSO020 Turm der Diebe Untergrund",
L"SSO021 Turm der Diebe Dach",
L"SSO022 Turm der Diebe Hauptdämon",
L"SSO023 Turm der Diebe Schattendrache",
L"SSO024 Turm der Diebe Siegel",
L"SSO025 Magier des Dunklen Sumpfes Dunkler Sumpf",
L"SSO026 Magier des Dunklen Sumpfes Roter Drache",
L"SSO027 Romancia Romancia Königreich",
L"SSO028 Romancia Romancia Schloss",
L"SSO029 Romancia Azolba Königreich",
L"SSO030 Romancia Vaides",
L"SSO060 Romancia Exklusiv Abgeschlossen",
L"SSO031 Mysterium des Rubins Wald",
L"SSO032 Mysterium des Rubins Moosriese",
L"SSO033 Mysterium des Rubins Friedlicher Wald",
L"SSO034 Dunkler Magier Verlies",
L"SSO035 Dunkler Magier Gedis",
L"SSO064 Dunkler Magier Gedis II",
L"SSO036 Dunkler Magier Blauer Drache",
L"SSO037 Verfluchte Königin Mary Schiffsinnere",
L"SSO038 Verfluchte Königin Mary Nach der Landung",
L"SSO039 Verfluchte Königin Mary Arkandämon",
L"SSO040 Götter des Himmels Dorf",
L"SSO041 Götter des Himmels Kampfszene",
L"SSO042 Götter des Himmels Himmlisches Reich",
L"SSO043 Götter des Himmels Harfe",
L"SSO044 Götter des Himmels Böser Schamane",
L"SSO045 Eishöhle Höhle",
L"SSO046 Eishöhle Höhle II",
L"SSO047 Eishöhle Ekim",
L"SSO048 Medusas Haupt Wald",
L"SSO049 Medusas Haupt Dorf",
L"SSO050 Medusas Haupt Medusa",
L"SSO051 Gefangener Magier Unterirdische Festung",
L"SSO052 Gefangener Magier Feuer-Elementar",
L"SSO053 Wasser der Jugend Lebende Höhle",
L"SSO054 Wasser der Jugend Schlagendes Herz",
L"SSO055 Wasser der Jugend Doppelte Dämonen",
L"SSO056 Königlicher Drache",
L"SSO057 Ende I",
L"SSO058 Ende II",
L"SSO066 Neue Eröffnung",
L"SSO080 Fehlschlag eines Magiers Unterirdischer Minensee",
L"SSO081 Fehlschlag eines Magiers Erd-Elementar",
L"SSO083 Mitternachtsglocke Randle Dorf",
L"SSO084 Mitternachtsglocke Kirche",
L"SSO085 Mitternachtsglocke Zaquria",
L"SSO086 Mitternachtsglocke Magier Geran",
L"SSO087 Zwergenerbe Zwergenlabyrinth",
L"SSO088 Zwergenerbe Labyrinth-Drache",
L"SSO089 Rettet den Feenbaum Feendorf",
L"SSO090 Rettet den Feenbaum Inneres des Riesenbaums",
L"SSO091 Rettet den Feenbaum Tausendfüßler",
L"SSO092 Unerwünschte Besucher Verdächtige Insel",
L"SSO093 Unerwünschte Besucher Arkandämon",
L"SSO082 Forever Szenario 1~5 Abgeschlossen"
};

TCHAR tisor_pt[][128] = {
L"SSO001 Abertura",
L"SSO002 Castelo (Nos Encontramos Aqui)",
L"SSO003 Vila 1",
L"SSO004 Vila 2",
L"SSO008 Estalagem dos Viajantes",
L"SSO059 Cenário Completado",
L"SSO005 Cajado do Rei Perdido Masmorra",
L"SSO006 Cajado do Rei Perdido Hidra",
L"SSO007 Cajado do Rei Perdido Sobrevivência",
L"SSO009 Talismã Perdido Floresta",
L"SSO010 Talismã Perdido Masmorra Subterrânea",
L"SSO011 Talismã Perdido Sacerdote Terhichi",
L"SSO012 Talismã Perdido Sand Marlborough",
L"SSO013 Eclusa de Lúcifer Masmorra Subterrânea",
L"SSO014 Eclusa de Lúcifer Kraken",
L"SSO015 Eclusa de Lúcifer Rio Sangrento",
L"SSO016 Oásis Amaldiçoado Deserto",
L"SSO017 Oásis Amaldiçoado Castelo de Areia",
L"SSO018 Oásis Amaldiçoado Ruan e Dragão de Ouro",
L"SSO019 Torre dos Ladrões Torre",
L"SSO020 Torre dos Ladrões Subterrâneo",
L"SSO021 Torre dos Ladrões Telhado",
L"SSO022 Torre dos Ladrões Demônio Maior",
L"SSO023 Torre dos Ladrões Dragão das Sombras",
L"SSO024 Torre dos Ladrões Selo",
L"SSO025 Mago do Pântano Negro Pântano Negro",
L"SSO026 Mago do Pântano Negro Dragão Vermelho",
L"SSO027 Romancia Reino de Romancia",
L"SSO028 Romancia Castelo de Romancia",
L"SSO029 Romancia Reino de Azolba",
L"SSO030 Romancia Vaides",
L"SSO060 Conclusão Exclusiva Romancia",
L"SSO031 Mistério do Rubi Floresta",
L"SSO032 Mistério do Rubi Gigante de Musgo",
L"SSO033 Mistério do Rubi Floresta Pacífica",
L"SSO034 Mago Negro Masmorra",
L"SSO035 Mago Negro Gedis",
L"SSO064 Mago Negro Gedis II",
L"SSO036 Mago Negro Dragão Azul",
L"SSO037 Rainha Mary Amaldiçoada Interior do Navio",
L"SSO038 Rainha Mary Amaldiçoada Após Desembarque",
L"SSO039 Rainha Mary Amaldiçoada Demônio Arcano",
L"SSO040 Deuses do Céu Vila",
L"SSO041 Deuses do Céu Cena de Combate",
L"SSO042 Deuses do Céu Reino Celestial",
L"SSO043 Deuses do Céu Harpa",
L"SSO044 Deuses do Céu Xamã Malévolo",
L"SSO045 Caverna de Gelo Caverna",
L"SSO046 Caverna de Gelo Caverna II",
L"SSO047 Caverna de Gelo Ekim",
L"SSO048 Cabeça da Medusa Floresta",
L"SSO049 Cabeça da Medusa Vila",
L"SSO050 Cabeça da Medusa Medusa",
L"SSO051 Mago Preso Fortaleza Subterrânea",
L"SSO052 Mago Preso Elemental de Fogo",
L"SSO053 Água da Juventude Eterna Caverna Viva",
L"SSO054 Água da Juventude Eterna Coração Palpitante",
L"SSO055 Água da Juventude Eterna Duplo Demônios",
L"SSO056 Rei Dragão",
L"SSO057 Final I",
L"SSO058 Final II",
L"SSO066 Nova Abertura",
L"SSO080 Fracasso de um Mago Lago Subterrâneo da Mina",
L"SSO081 Fracasso de um Mago Elemental da Terra",
L"SSO083 Sino da Meia-Noite Vila Randle",
L"SSO084 Sino da Meia-Noite Igreja",
L"SSO085 Sino da Meia-Noite Zaquria",
L"SSO086 Sino da Meia-Noite Mago Geran",
L"SSO087 Legado do Anão Labirinto do Anão",
L"SSO088 Legado do Anão Dragão Labirinto",
L"SSO089 Salve a Árvore das Fadas Vila das Fadas",
L"SSO090 Salve a Árvore das Fadas Interior da Árvore Gigante",
L"SSO091 Salve a Árvore das Fadas Centopéia",
L"SSO092 Visitantes Indesejados Ilha Suspeita",
L"SSO093 Visitantes Indesejados Demônio Arcano",
L"SSO082 Forever Cenário 1~5 Completado"
};

TCHAR tisor_nl[][128] = {
L"SSO001 Opening",
L"SSO002 Kasteel (We Ontmoeten Elkander Hier)",
L"SSO003 Stad 1",
L"SSO004 Stad 2",
L"SSO008 Herberg der Reizigers",
L"SSO059 Scenario Voltooid",
L"SSO005 Verloren Koningsstaf Kerker",
L"SSO006 Verloren Koningsstaf Hydra",
L"SSO007 Verloren Koningsstaf Overleving",
L"SSO009 Verloren Talisman Bos",
L"SSO010 Verloren Talisman Ondergrondse Kerker",
L"SSO011 Verloren Talisman Priester Terhichi",
L"SSO012 Verloren Talisman Sand Marlborough",
L"SSO013 Lucifers Sluis Ondergrondse Kerker",
L"SSO014 Lucifers Sluis Kraken",
L"SSO015 Lucifers Sluis Bloederige Rivier",
L"SSO016 Vervloekte Oase Woestijn",
L"SSO017 Vervloekte Oase Zandkasteel",
L"SSO018 Vervloekte Oase Ruan en Gouden Draak",
L"SSO019 Toren der Dieven Toren",
L"SSO020 Toren der Dieven Ondergronds",
L"SSO021 Toren der Dieven Dak",
L"SSO022 Toren der Dieven Grote Demon",
L"SSO023 Toren der Dieven Schaduwdraak",
L"SSO024 Toren der Dieven Zegel",
L"SSO025 Tovenaar van het Donkere Moeras Donker Moeras",
L"SSO026 Tovenaar van het Donkere Moeras Rode Draak",
L"SSO027 Romancia Romancia Koninkrijk",
L"SSO028 Romancia Romancia Kasteel",
L"SSO029 Romancia Azolba Koninkrijk",
L"SSO030 Romancia Vaides",
L"SSO060 Romancia Exclusief Voltooid",
L"SSO031 Mysterie van de Robijn Bos",
L"SSO032 Mysterie van de Robijn Mosreus",
L"SSO033 Mysterie van de Robijn Vredig Bos",
L"SSO034 Donkere Magiër Kerker",
L"SSO035 Donkere Magiër Gedis",
L"SSO064 Donkere Magiër Gedis II",
L"SSO036 Donkere Magiër Blauwe Draak",
L"SSO037 Vervloekte Koningin Mary Scheepsinterieur",
L"SSO038 Vervloekte Koningin Mary Na Landing",
L"SSO039 Vervloekte Koningin Mary Arkanedemon",
L"SSO040 Goden van de Hemel Dorp",
L"SSO041 Goden van de Hemel Gevechtsscène",
L"SSO042 Goden van de Hemel Hemels Rijk",
L"SSO043 Goden van de Hemel Harp",
L"SSO044 Goden van de Hemel Kwaadaardige Sjamaan",
L"SSO045 IJsgrot Grot",
L"SSO046 IJsgrot Grot II",
L"SSO047 IJsgrot Ekim",
L"SSO048 Medusa's Hoofd Bos",
L"SSO049 Medusa's Hoofd Dorp",
L"SSO050 Medusa's Hoofd Medusa",
L"SSO051 Gevangene Magiër Ondergrondse Vesting",
L"SSO052 Gevangene Magiër Vuurelement",
L"SSO053 Water van Eeuwige Jeugd Levende Grot",
L"SSO054 Water van Eeuwige Jeugd Kloppend Hart",
L"SSO055 Water van Eeuwige Jeugd Dubbele Duivels",
L"SSO056 Koning Draak",
L"SSO057 Einde I",
L"SSO058 Einde II",
L"SSO066 Nieuwe Opening",
L"SSO080 Falen van een Magiër Ondergronds Mijnmeer",
L"SSO081 Falen van een Magiër Aarde-element",
L"SSO083 Middernachtklok Randle Dorp",
L"SSO084 Middernachtklok Kerk",
L"SSO085 Middernachtklok Zaquria",
L"SSO086 Middernachtklok Magiër Geran",
L"SSO087 Erfenis van de Dwerg Dwerglabyrint",
L"SSO088 Erfenis van de Dwerg Labyrintdraak",
L"SSO089 Red de Feëenboom Feëndorp",
L"SSO090 Red de Feëenboom Reuzeboominterieur",
L"SSO091 Red de Feëenboom Duizendpoot",
L"SSO092 Ongewenste Bezoekers Verdacht Eiland",
L"SSO093 Ongewenste Bezoekers Arkanedemon",
L"SSO082 Forever Scenario 1~5 Voltooid"
};

TCHAR tisor_pl[][128] = {
L"SSO001 Otwarcie",
L"SSO002 Zamek (Spotkamy Się Tutaj)",
L"SSO003 Miasto 1",
L"SSO004 Miasto 2",
L"SSO008 Karczma Podróżników",
L"SSO059 Scenariusz Ukończony",
L"SSO005 Zagubione Berło Króla Loch",
L"SSO006 Zagubione Berło Króla Hydra",
L"SSO007 Zagubione Berło Króla Przetrwanie",
L"SSO009 Zagubiony Talizman Las",
L"SSO010 Zagubiony Talizman Podziemny Loch",
L"SSO011 Zagubiony Talizman Kapłan Terhichi",
L"SSO012 Zagubiony Talizman Sand Marlborough",
L"SSO013 Śluza Lucyfera Podziemny Loch",
L"SSO014 Śluza Lucyfera Kraken",
L"SSO015 Śluza Lucyfera Krwawa Rzeka",
L"SSO016 Przeklęta Oaza Pustynia",
L"SSO017 Przeklęta Oaza Zamek z Piasku",
L"SSO018 Przeklęta Oaza Ruan i Złoty Smok",
L"SSO019 Wieża Złodziei Wieża",
L"SSO020 Wieża Złodziei Podziemia",
L"SSO021 Wieża Złodziei Dach",
L"SSO022 Wieża Złodziei Główny Demon",
L"SSO023 Wieża Złodziei Smok Cieni",
L"SSO024 Wieża Złodziei Pieczęć",
L"SSO025 Czarnoksiężnik Ciemnego Bagna Ciemne Bagno",
L"SSO026 Czarnoksiężnik Ciemnego Bagna Czerwony Smok",
L"SSO027 Romancia Królestwo Romancia",
L"SSO028 Romancia Zamek Romancia",
L"SSO029 Romancia Królestwo Azolba",
L"SSO030 Romancia Vaides",
L"SSO060 Ekskluzywne Ukończenie Romancia",
L"SSO031 Tajemnica Rubinu Las",
L"SSO032 Tajemnica Rubinu Olbrzym Mchu",
L"SSO033 Tajemnica Rubinu Spokojny Las",
L"SSO034 Czarny Mag Loch",
L"SSO035 Czarny Mag Gedis",
L"SSO064 Czarny Mag Gedis II",
L"SSO036 Czarny Mag Niebieski Smok",
L"SSO037 Przeklęta Królowa Mary Wnętrze Statku",
L"SSO038 Przeklęta Królowa Mary Po Lądowaniu",
L"SSO039 Przeklęta Królowa Mary Demon Arkański",
L"SSO040 Bogowie Niebios Wieś",
L"SSO041 Bogowie Niebios Scena Walki",
L"SSO042 Bogowie Niebios Niebiańskie Królestwo",
L"SSO043 Bogowie Niebios Harfa",
L"SSO044 Bogowie Niebios Zły Szaman",
L"SSO045 Lodowa Jaskinia Jaskinia",
L"SSO046 Lodowa Jaskinia Jaskinia II",
L"SSO047 Lodowa Jaskinia Ekim",
L"SSO048 Głowa Meduzy Las",
L"SSO049 Głowa Meduzy Wieś",
L"SSO050 Głowa Meduzy Meduza",
L"SSO051 Uwięziony Mag Podziemna Twierdza",
L"SSO052 Uwięziony Mag Elemental Ognia",
L"SSO053 Woda Wiecznej Młodości Żywa Jaskinia",
L"SSO054 Woda Wiecznej Młodości Bijące Serce",
L"SSO055 Woda Wiecznej Młodości Podwójni Diabły",
L"SSO056 Król Smok",
L"SSO057 Zakończenie I",
L"SSO058 Zakończenie II",
L"SSO066 Nowe Otwarcie",
L"SSO080 Porażka Maga Podziemne Jezioro Kopalni",
L"SSO081 Porażka Maga Elemental Ziemi",
L"SSO083 Północny Dzwon Wieś Randle",
L"SSO084 Północny Dzwon Kościół",
L"SSO085 Północny Dzwon Zaquria",
L"SSO086 Północny Dzwon Mag Geran",
L"SSO087 Spuścizna Krasnoluda Labirynt Krasnoluda",
L"SSO088 Spuścizna Krasnoluda Smok Labiryntu",
L"SSO089 Uratuj Drzewo Wróżek Wieś Wróżek",
L"SSO090 Uratuj Drzewo Wróżek Wnętrze Gigantycznego Drzewa",
L"SSO091 Uratuj Drzewo Wróżek Stonoga",
L"SSO092 Niepożądani Goście Podejrzana Wyspa",
L"SSO093 Niepożądani Goście Demon Arkański",
L"SSO082 Forever Scenariusz 1~5 Ukończony"
};

TCHAR tisor_tr[][128] = {
L"SSO001 Açılış",
L"SSO002 Kale (Burada Buluşacağız)",
L"SSO003 Kasaba 1",
L"SSO004 Kasaba 2",
L"SSO008 Gezginler Hanı",
L"SSO059 Senaryo Tamamlandı",
L"SSO005 Kayıp Kralın Asası Zindan",
L"SSO006 Kayıp Kralın Asası Hydra",
L"SSO007 Kayıp Kralın Asası Hayatta Kalma",
L"SSO009 Kayıp Tılsım Orman",
L"SSO010 Kayıp Tılsım Yer Altı Zindanı",
L"SSO011 Kayıp Tılsım Rahip Terhichi",
L"SSO012 Kayıp Tılsım Sand Marlborough",
L"SSO013 Lucifer'in Kapısı Yer Altı Zindanı",
L"SSO014 Lucifer'in Kapısı Kraken",
L"SSO015 Lucifer'in Kapısı Kanlı Nehir",
L"SSO016 Lanetli Vaha Çöl",
L"SSO017 Lanetli Vaha Kum Kalesi",
L"SSO018 Lanetli Vaha Ruan ve Altın Ejderha",
L"SSO019 Hırsızlar Kulesi Kule",
L"SSO020 Hırsızlar Kulesi Yer Altı",
L"SSO021 Hırsızlar Kulesi Çatı",
L"SSO022 Hırsızlar Kulesi Büyük Şeytan",
L"SSO023 Hırsızlar Kulesi Gölge Ejderha",
L"SSO024 Hırsızlar Kulesi Mühür",
L"SSO025 Karanlık Bataklık Büyücüsü Karanlık Bataklık",
L"SSO026 Karanlık Bataklık Büyücüsü Kırmızı Ejderha",
L"SSO027 Romancia Romancia Krallığı",
L"SSO028 Romancia Romancia Kalesi",
L"SSO029 Romancia Azolba Krallığı",
L"SSO030 Romancia Vaides",
L"SSO060 Romancia Özel Tamamlama",
L"SSO031 Yakut Gizemi Orman",
L"SSO032 Yakut Gizemi Yosun Devi",
L"SSO033 Yakut Gizemi Huzurlu Orman",
L"SSO034 Karanlık Büyücü Zindan",
L"SSO035 Karanlık Büyücü Gedis",
L"SSO064 Karanlık Büyücü Gedis II",
L"SSO036 Karanlık Büyücü Mavi Ejderha",
L"SSO037 Lanetli Kraliçe Mary Gemi İçi",
L"SSO038 Lanetli Kraliçe Mary Karaya Çıktıktan Sonra",
L"SSO039 Lanetli Kraliçe Mary Arka Şeytan",
L"SSO040 Gök Tanrıları Köy",
L"SSO041 Gök Tanrıları Savaş Sahnesi",
L"SSO042 Gök Tanrıları Gök Krallığı",
L"SSO043 Gök Tanrıları Arp",
L"SSO044 Gök Tanrıları Kötü Şaman",
L"SSO045 Buz Mağarası Mağara",
L"SSO046 Buz Mağarası Mağara II",
L"SSO047 Buz Mağarası Ekim",
L"SSO048 Medusa'nın Başı Orman",
L"SSO049 Medusa'nın Başı Köy",
L"SSO050 Medusa'nın Başı Medusa",
L"SSO051 Hapsedilmiş Büyücü Yer Altı Kalesi",
L"SSO052 Hapsedilmiş Büyücü Ateş Elementali",
L"SSO053 Gençlik Suyu Canlı Mağara",
L"SSO054 Gençlik Suyu Atan Kalp",
L"SSO055 Gençlik Suyu İkiz Şeytanlar",
L"SSO056 Kral Ejderha",
L"SSO057 Son I",
L"SSO058 Son II",
L"SSO066 Yeni Açılış",
L"SSO080 Bir Büyücünün Başarısızlığı Maden Yer Altı Gölü",
L"SSO081 Bir Büyücünün Başarısızlığı Toprak Elementali",
L"SSO083 Gece Yarısı Çanları Randle Köyü",
L"SSO084 Gece Yarısı Çanları Kilise",
L"SSO085 Gece Yarısı Çanları Zaquria",
L"SSO086 Gece Yarısı Çanları Büyücü Geran",
L"SSO087 Cüce Mirası Cüce Labirenti",
L"SSO088 Cüce Mirası Labirent Ejderha",
L"SSO089 Peri Ağacını Kurtar Peri Köyü",
L"SSO090 Peri Ağacını Kurtar Dev Ağaç İçi",
L"SSO091 Peri Ağacını Kurtar Kırkayak",
L"SSO092 İstenmeyen Misafirler Şüpheli Ada",
L"SSO093 İstenmeyen Misafirler Arka Şeytan",
L"SSO082 Forever Senaryo 1~5 Tamamlandı"
};

static inline CString SorTrack(int i) {
	switch (savedata.lang) {
	case 0: return CString(tisor[i]);
	case 1: return CString(tisor_en[i]);
	case 2: return CString(tisor_fr[i]);
	case 3: return CString(tisor_it[i]);
	case 4: return CString(tisor_es[i]);
	case 5: return CString(tisor_ko[i]);
	case 6: return CString(tisor_zh[i]);
	case 7: return CString(tisor_ar[i]);
	case 8: return CString(tisor_ru[i]);
	case 9: return CString(tisor_de[i]);
	case 10: return CString(tisor_pt[i]);
	case 11: return CString(tisor_nl[i]);
	case 12: return CString(tisor_pl[i]);
	case 13: return CString(tisor_tr[i]);
	default: return CString(tisor_en[i]);
	}
}

CString CSor::Gett(int a) {
	CString s, ss;
	s = SorTrack(a);
	ss = s.Left(6); ss.TrimRight();
	fnn = s.Mid(7);
	return ss;
}

/////////////////////////////////////////////////////////////////////////////
// CZWEIII メッセージ ハンドラ
void CSor::OnDblclkList1()
{
	// TODO: この位置にコントロール通知ハンドラ用のコードを追加してください
	int idx = m_list.GetItemData(m_list.GetCurSel());
	CString s;	s = SorTrack(idx);
	ret = s.Left(6); ret.TrimRight();
	ret2 = m_list.GetCurSel();
	if (s.Left(2) == "★") {
		fnn = s.Mid(2);
	}
	else {
		fnn = s.Mid(7);
	}
	EndDialog(1567);
}

BOOL CSor::OnInitDialog()
{
	CCustomDialog::OnInitDialog();
	SetWindowText(LL14(L"ソーサリアン オリジナル", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original", L"Sorcerian Original"));
	SetDlgItemText(IDOK, LL14(L"閉じる", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close"));

	// TODO: この位置に初期化の補足処理を追加してください
	int dx;
	for (int i = 0; i < (76); i++)
	{
		CString s = SorTrack(i);
		dx = m_list.AddString(s);
		m_list.SetItemData(dx, i);
	}

	m_list.SetCurSel(0);
	if (ret2 != 0)
		//		if(ret>65) m_list.SetCurSel(ret);
		//		else m_list.SetCurSel(ret-1);
		m_list.SetCurSel(ret2);
	m_list.SetFocus();
	return FALSE;  // コントロールにフォーカスを設定しないとき、戻り値は TRUE となります
	// 例外: OCX プロパティ ページの戻り値は FALSE となります
}

