// ZWEIII.cpp : インプリメンテーション ファイル
//

#include "stdafx.h"
#include "ogg.h"
#include "ZWEIII.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CZWEIII ダイアログ

extern CString fnn;

CZWEIII::CZWEIII(CWnd* pParent /*=NULL*/)
	: CCustomBlurDialogBase(CZWEIII::IDD, pParent)
{
	//{{AFX_DATA_INIT(CZWEIII)
		// メモ - ClassWizard はこの位置にマッピング用のマクロを追加または削除します。
	//}}AFX_DATA_INIT
}


void CZWEIII::DoDataExchange(CDataExchange* pDX)
{
	CCustomBlurDialogBase::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CZWEIII)
	DDX_Control(pDX, IDC_LIST1, m_list);
	//}}AFX_DATA_MAP
	DDX_Control(pDX, IDOK, m_okdummy);
}

#include "CImageBase.h"
BEGIN_MESSAGE_MAP(CZWEIII, CCustomBlurDialogBase)
	//{{AFX_MSG_MAP(CZWEIII)
	ON_LBN_DBLCLK(IDC_LIST1, OnDblclkList1)
	//}}AFX_MSG_MAP
	cmn(CZWEIII);


TCHAR tiz2[][128] = {
L"000 限りなき冒険の新天地",
L"001 グランヴァレンの伝説",
L"002 ボクラノ未来 Opening Version",
L"003 ZWEI II End Credit",
L"004 力尽きても…",
L"006 魔法大戦再び…",
L"007 たすけてアルウェン Rushing in Version",
L"008 宿縁の終焉",
L"100 浮遊島《イルバード》",
L"101 アルッテの町",
L"102 アルッテ飛行場",
L"103 ブランデーヶ丘",
L"104 ロアルタ村",
L"105 星降りの里",
L"106 クリスタルバレー",
L"108 魔女ラーライラ",
L"109 覆面超人ギャランドゥ",
L"200 セクンドゥム廃坑",
L"201 オルディウム神殿",
L"202 金闇の森",
L"203 アウロン大鉄塔",
L"205 闇夜に踊れ",
L"206 ムーンブリア城",
L"207 狂喜の牢獄",
L"208 エスピナへ捧ぐ祈り",
L"209 星ヶ峰",
L"210 覚悟を決めて",
L"211 月の世界《ルナ＝ムンドゥス》",
L"212 螺旋要塞メルセデク",
L"300 まかせろラグナ",
L"301 唸れ！アンカーギア！！",
L"304 真祖の力",
L"305 我にひれ伏せ",
L"306 我が主のために",
L"307 この瞬間に全てを賭けて",
L"308 障害を突破せよ",
L"400 Dog Fight！！",
L"401 不穏な空気",
L"402 モンブランのテーマ",
L"403 レッツ・エクササァイズ！！",
L"404 激情に駆られて",
L"405 ザハールの大望",
L"406 最悪の事態",
L"407 あたたかな想い",
L"408 通い合う心と心",
L"409 お食事は大熊猫楼で",
L"410 機械仕掛けの少女",
L"411 宿縁の少女",
L"412 たすけてアルウェン",
L"413 失意のラグナ",
L"414 課せられた使命",
L"415 かけがえのない日常",
L"416 再会を誓って",
L"417 夜空に佇む",
L"500 音楽 Ys フェルガナの誓い(翼を持った少年)",
L"501 音楽 Ys フェルガナの誓い(バレスタイン城)",
L"502 音楽 Ys オリジン(BEYOND THE BEGINNING)",
L"503 音楽 Ys オリジン(WATER PRISON)",
L"504 音楽 Zwei!!(花と風のうた -arrange-)",
L"505 音楽 Zwei!!(幻の大地 セルペンティナ)",
L"506 音楽 空の軌跡FC(虚ろなる光の封土)",
L"507 音楽 空の軌跡SC(The Fate of The Fairies)",
L"508 音楽 空の軌跡The3rd(Overdosing Heavenly Bliss)",
L"509 音楽 ぐるみん(不可思議オバケ卵)",
L"510 音楽 ぐるみん(TO MAKE THE END OF DIGING)",
L"★オープニング",
L"★エンディング"
};

TCHAR tiz2_en[][128] = {
L"000 New Frontier of Endless Adventure",
L"001 Legend of Granvalen",
L"002 Our Future Opening Version",
L"003 ZWEI II End Credit",
L"004 Even When Exhausted...",
L"006 Magic War Again...",
L"007 Help Alwen Rushing in Version",
L"008 End of Fate",
L"100 Floating Island Ilbard",
L"101 Artte Town",
L"102 Artte Airfield",
L"103 Brande Hill",
L"104 Roalta Village",
L"105 Starfall Village",
L"106 Crystal Valley",
L"108 Witch Lalaile",
L"109 Masked Superman Galland",
L"200 Secondum Abandoned Mine",
L"201 Ordium Temple",
L"202 Forest of Gold and Darkness",
L"203 Aulon Great Iron Tower",
L"205 Dance in the Dark Night",
L"206 Moonbria Castle",
L"207 Prison of Ecstasy",
L"208 Prayer to Espina",
L"209 Star Peak",
L"210 Make Up Your Mind",
L"211 Lunar World Luna=Mundus",
L"212 Spiral Fortress Mercedec",
L"300 Leave It to Ragna",
L"301 Roar! Anchor Gear!!",
L"304 Power of the Ancestor",
L"305 Bow Before Me",
L"306 For My Lord",
L"307 Bet Everything on This Moment",
L"308 Break Through the Obstacles",
L"400 Dog Fight!!",
L"401 Ominous Air",
L"402 Mont Blanc's Theme",
L"403 Let's Exercise!!",
L"404 Driven by Passion",
L"405 Zahhar's Ambition",
L"406 Worst Case",
L"407 Warm Feelings",
L"408 Hearts in Tune",
L"409 Dining at Panda Tower",
L"410 Girl of Machinery",
L"411 Girl of Fate",
L"412 Help Alwen",
L"413 Ragna in Despair",
L"414 Mission Assigned",
L"415 Irreplaceable Daily Life",
L"416 Pledge to Meet Again",
L"417 Standing in the Night Sky",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Opening",
L"★Ending"
};

TCHAR tiz2_fr[][128] = {
L"000 Nouvelle Frontière d'Aventure Infinie",
L"001 Légende de Granvalen",
L"002 Notre Futur Opening Version",
L"003 ZWEI II End Credit",
L"004 Même Épuisé...",
L"006 Guerre Magique à Nouveau...",
L"007 Aide Alwen Rushing in Version",
L"008 Fin du Destin",
L"100 Île Flottante Ilbard",
L"101 Ville d'Artte",
L"102 Aérodrome d'Artte",
L"103 Colline de Brande",
L"104 Village de Roalta",
L"105 Village de Pluie d'Étoiles",
L"106 Vallée de Cristal",
L"108 Sorcière Lalaile",
L"109 Superman Masqué Galland",
L"200 Mine Abandonnée Secondum",
L"201 Temple d'Ordium",
L"202 Forêt d'Or et Ténèbres",
L"203 Grande Tour de Fer d'Aulon",
L"205 Danse dans la Nuit Obscure",
L"206 Château de Moonbria",
L"207 Prison d'Extase",
L"208 Prière à Espina",
L"209 Pic des Étoiles",
L"210 Prends ta Décision",
L"211 Monde Lunaire Luna=Mundus",
L"212 Forteresse en Spirale Mercedec",
L"300 Confie à Ragna",
L"301 Rugis ! Anchor Gear !!",
L"304 Pouvoir de l'Ancêtre",
L"305 Prosterne-toi Devant Moi",
L"306 Pour Mon Seigneur",
L"307 Parie Tout sur Cet Instant",
L"308 Franchis les Obstacles",
L"400 Dog Fight !!",
L"401 Air Ominieux",
L"402 Thème de Mont Blanc",
L"403 À l'Exercice !!",
L"404 Entraîné par la Passion",
L"405 Ambition de Zahhar",
L"406 Pire Cas",
L"407 Sentiments Chaleureux",
L"408 Cœurs à l'Unisson",
L"409 Dîner à la Tour Panda",
L"410 Fille de Mécanismes",
L"411 Fille du Destin",
L"412 Aide Alwen",
L"413 Ragna au Désespoir",
L"414 Mission Assignée",
L"415 Vie Quotidienne Inestimable",
L"416 Promesse de Se Revoir",
L"417 Debout dans la Nuit Étoilée",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Ouverture",
L"★Final"
};

TCHAR tiz2_it[][128] = {
L"000 Nuova Frontiera di Avventura Infinita",
L"001 Leggenda di Granvalen",
L"002 Nostro Futuro Opening Version",
L"003 ZWEI II End Credit",
L"004 Anche Quando Esausto...",
L"006 Guerra Magica Ancora...",
L"007 Aiuta Alwen Rushing in Version",
L"008 Fine del Destino",
L"100 Isola Galleggiante Ilbard",
L"101 Città di Artte",
L"102 Aeroporto di Artte",
L"103 Collina di Brande",
L"104 Villaggio di Roalta",
L"105 Villaggio della Pioggia di Stelle",
L"106 Valle di Cristallo",
L"108 Strega Lalaile",
L"109 Superman Mascherato Galland",
L"200 Miniera Abbandonata Secondum",
L"201 Tempio di Ordium",
L"202 Foresta d'Oro e Tenebra",
L"203 Grande Torre di Ferro di Aulon",
L"205 Danza nella Notte Oscura",
L"206 Castello di Moonbria",
L"207 Prigione d'Estasi",
L"208 Preghiera a Espina",
L"209 Picco delle Stelle",
L"210 Decidi",
L"211 Mondo Lunare Luna=Mundus",
L"212 Fortezza a Spirale Mercedec",
L"300 Lascia Fare a Ragna",
L"301 Ruggisci! Anchor Gear !!",
L"304 Potere dell'Antenato",
L"305 Inchina dinanzi a Me",
L"306 Per il Mio Signore",
L"307 Scommetti Tutto su Questo Momento",
L"308 Supera gli Ostacoli",
L"400 Dog Fight !!",
L"401 Aria Sinistra",
L"402 Tema di Mont Blanc",
L"403 Facciamo Esercizio !!",
L"404 Spinto dalla Passione",
L"405 Ambizione di Zahhar",
L"406 Caso Peggiore",
L"407 Sentimenti Caldi",
L"408 Cuori in Sintonia",
L"409 Cena alla Torre Panda",
L"410 Ragazza di Meccaniche",
L"411 Ragazza del Destino",
L"412 Aiuta Alwen",
L"413 Ragna nella Disperazione",
L"414 Missione Assegnata",
L"415 Vita Quotidiana Insostituibile",
L"416 Promessa di Rivederci",
L"417 In Piedi nel Cielo Notturno",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Apertura",
L"★Finale"
};

TCHAR tiz2_es[][128] = {
L"000 Nueva Frontera de Aventura Infinita",
L"001 Leyenda de Granvalen",
L"002 Nuestro Futuro Opening Version",
L"003 ZWEI II End Credit",
L"004 Aun Agotado...",
L"006 Guerra Mágica de Nuevo...",
L"007 Ayuda a Alwen Rushing in Version",
L"008 Fin del Destino",
L"100 Isla Flotante Ilbard",
L"101 Pueblo de Artte",
L"102 Aeródromo de Artte",
L"103 Colina de Brande",
L"104 Aldea de Roalta",
L"105 Aldea de Lluvia de Estrellas",
L"106 Valle de Cristal",
L"108 Bruja Lalaile",
L"109 Superhombre Enmascarado Galland",
L"200 Mina Abandonada Secondum",
L"201 Templo de Ordium",
L"202 Bosque de Oro y Oscuridad",
L"203 Gran Torre de Hierro de Aulon",
L"205 Danza en la Noche Oscura",
L"206 Castillo de Moonbria",
L"207 Prisión de Éxtasis",
L"208 Oración a Espina",
L"209 Pico Estelar",
L"210 Decide",
L"211 Mundo Lunar Luna=Mundus",
L"212 Fortaleza en Espiral Mercedec",
L"300 Déjalo a Ragna",
L"301 ¡Ruge! ¡Anchor Gear !!",
L"304 Poder del Ancestro",
L"305 Inclínate Ante Mí",
L"306 Por Mi Señor",
L"307 Apuesta Todo en Este Momento",
L"308 Atraviesa los Obstáculos",
L"400 Dog Fight !!",
L"401 Aire Ominoso",
L"402 Tema de Mont Blanc",
L"403 ¡A Ejercitarse !!",
L"404 Impulsado por la Pasión",
L"405 Ambición de Zahhar",
L"406 Peor Caso",
L"407 Sentimientos Cálidos",
L"408 Corazones en Sintonía",
L"409 Cena en la Torre Panda",
L"410 Chica de Mecanismos",
L"411 Chica del Destino",
L"412 Ayuda a Alwen",
L"413 Ragna en la Desesperación",
L"414 Misión Asignada",
L"415 Vida Cotidiana Irreemplazable",
L"416 Promesa de Reencontrarse",
L"417 De Pie en el Cielo Nocturno",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Apertura",
L"★Final"
};

TCHAR tiz2_ko[][128] = {
L"000 끝없는 모험의 신천지",
L"001 그란발렌의 전설",
L"002 우리의 미래 Opening Version",
L"003 ZWEI II End Credit",
L"004 지쳐도...",
L"006 마법 대전 다시...",
L"007 도와줘 알웬 Rushing in Version",
L"008 숙연의 종언",
L"100 부유도 《일바드》",
L"101 아르테 마을",
L"102 아르테 비행장",
L"103 브란데 언덕",
L"104 로알타 마을",
L"105 별내리는 마을",
L"106 크리스탈 밸리",
L"108 마녀 라라일",
L"109 가면 초인 갈란드",
L"200 세쿤둠 폐광",
L"201 오르디움 신전",
L"202 금암의 숲",
L"203 아울론 대철탑",
L"205 암야에 춤춰라",
L"206 문브리아 성",
L"207 광희의 감옥",
L"208 에스피나에게 바치는 기도",
L"209 성봉",
L"210 결심을 내려",
L"211 달의 세계 《루나=문두스》",
L"212 나선 요새 메르세데크",
L"300 맡겨라 라그나",
L"301 으르렁거려라! 앵커 기어!!",
L"304 진조의 힘",
L"305 내 앞에 엎드려라",
L"306 나의 주를 위하여",
L"307 이 순간에 모든 것을 걸어",
L"308 장애를 돌파하라",
L"400 Dog Fight!!",
L"401 불길한 공기",
L"402 몽블랑의 테마",
L"403 레츠・엑서사이즈!!",
L"404 정열에 이끌려",
L"405 자하르의 대망",
L"406 최악의 사태",
L"407 따뜻한 마음",
L"408 통하는 마음과 마음",
L"409 식사는 판다루에서",
L"410 기계 장치의 소녀",
L"411 숙연의 소녀",
L"412 도와줘 알웬",
L"413 실의의 라그나",
L"414 부여된 사명",
L"415 대체할 수 없는 일상",
L"416 재회를 맹세하고",
L"417 밤하늘에 서서",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★오프닝",
L"★엔딩"
};

TCHAR tiz2_zh[][128] = {
L"000 无尽冒险的新天地",
L"001 格兰巴伦传说",
L"002 我们的未来 Opening Version",
L"003 ZWEI II End Credit",
L"004 即使筋疲力尽…",
L"006 魔法大战再临…",
L"007 帮助艾尔温 Rushing in Version",
L"008 宿缘的终结",
L"100 浮游岛《伊尔巴德》",
L"101 阿尔特镇",
L"102 阿尔特机场",
L"103 布兰迪丘陵",
L"104 罗阿尔塔村",
L"105 星降之里",
L"106 水晶谷",
L"108 魔女拉拉蕾",
L"109 蒙面超人伽兰德",
L"200 塞孔杜姆废坑",
L"201 奥狄姆神殿",
L"202 金暗之森",
L"203 奥隆大铁塔",
L"205 暗夜之舞",
L"206 月布里亚城",
L"207 狂喜之牢狱",
L"208 献给艾斯皮娜的祈祷",
L"209 星峰",
L"210 下定决心",
L"211 月之世界《鲁纳=蒙杜斯》",
L"212 螺旋要塞梅尔塞德克",
L"300 交给拉格纳",
L"301 咆哮吧！锚定齿轮！！",
L"304 真祖之力",
L"305 向我跪伏",
L"306 为了吾主",
L"307 将一切赌在这一瞬间",
L"308 突破障碍",
L"400 Dog Fight！！",
L"401 不祥的气氛",
L"402 蒙布朗的主题曲",
L"403 一起运动！！",
L"404 为激情所驱",
L"405 扎哈尔的野心",
L"406 最坏事态",
L"407 温暖的心意",
L"408 心意相通",
L"409 在熊猫楼用餐",
L"410 机械少女",
L"411 宿缘少女",
L"412 帮助艾尔温",
L"413 失意的拉格纳",
L"414 被赋予的使命",
L"415 无可替代的日常",
L"416 誓再相逢",
L"417 伫立于夜空",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★片头曲",
L"★片尾曲"
};

TCHAR tiz2_ar[][128] = {
L"000 حدود جديدة لمغامرة لا نهائية",
L"001 أسطورة غرانفالين",
L"002 مستقبلنا Opening Version",
L"003 ZWEI II End Credit",
L"004 حتى عند الإرهاق...",
L"006 حرب السحر مرة أخرى...",
L"007 ساعد ألفين Rushing in Version",
L"008 نهاية القدر",
L"100 جزيرة إيلبارد العائمة",
L"101 بلدة آرتيه",
L"102 مطار آرتيه",
L"103 تل براندي",
L"104 قرية روالتا",
L"105 قرية تساقط النجوم",
L"106 وادي الكريستال",
L"108 الساحرة لالايل",
L"109 الرجل الخارق المقنع غالاند",
L"200 منجم سيكوندوم المهجور",
L"201 معبد أورديوم",
L"202 غابة الذهب والظلام",
L"203 البرج الحديدي الكبير لأولون",
L"205 رقصة في الليل الدامس",
L"206 قلعة مونبريا",
L"207 سجن النشوة",
L"208 صلاة لإسبينا",
L"209 قمة النجوم",
L"210 عقد العزم",
L"211 العالم القمري لونا=موندوس",
L"212 قلعة ميرسيديك الحلزونية",
L"300 اترك الأمر لراغنا",
L"301 زئير! أنكور جير!!",
L"304 قوة السلف",
L"305 انحن أمامي",
L"306 من أجل سيدي",
L"307 راهن بكل شيء على هذه اللحظة",
L"308 اقتحم العوائق",
L"400 Dog Fight!!",
L"401 جو مشؤوم",
L"402 ثيم مون بلان",
L"403 لنتمرن!!",
L"404 مدفوعاً بالشغف",
L"405 طموح زاهار",
L"406 أسوأ السيناريوهات",
L"407 مشاعر دافئة",
L"408 قلوب متناغمة",
L"409 العشاء في برج الباندا",
L"410 فتاة الآليات",
L"411 فتاة القدر",
L"412 ساعد ألفين",
L"413 راغنا في اليأس",
L"414 المهمة الموكلة",
L"415 الحياة اليومية التي لا تقدر بثمن",
L"416 وعد اللقاء مجدداً",
L"417 وقوفاً تحت سماء الليل",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★المقدمة",
L"★النهاية"
};

TCHAR tiz2_ru[][128] = {
L"000 Новый рубеж бесконечных приключений",
L"001 Легенда Гранвалена",
L"002 Наше Будущее Opening Version",
L"003 ZWEI II End Credit",
L"004 Даже когда истощён...",
L"006 Снова Магическая Война...",
L"007 Помоги Алвен Rushing in Version",
L"008 Конец Судьбы",
L"100 Парящий Остров Ильбард",
L"101 Город Артте",
L"102 Аэродром Артте",
L"103 Холм Бранде",
L"104 Деревня Роалта",
L"105 Деревня Звездопада",
L"106 Хрустальная Долина",
L"108 Ведьма Лалайль",
L"109 Маскированный Супермен Галланд",
L"200 Заброшенная Шахта Секундум",
L"201 Храм Ордиума",
L"202 Лес Золота и Тьмы",
L"203 Великая Железная Башня Аулона",
L"205 Танец в Тёмной Ночи",
L"206 Замок Мунбрия",
L"207 Тюрьма Экстаза",
L"208 Молитва Эспине",
L"209 Звёздный Пик",
L"210 Прими Решение",
L"211 Лунный Мир Луна=Мундус",
L"212 Спиральная Крепость Мерседек",
L"300 Доверь Рагне",
L"301 Рычи! Anchor Gear!!",
L"304 Сила Предка",
L"305 Преклонись предо мной",
L"306 Ради Моего Господина",
L"307 Поставь Всё на Этот Момент",
L"308 Прорви Препятствия",
L"400 Dog Fight!!",
L"401 Зловещая Атмосфера",
L"402 Тема Монблана",
L"403 Занимаемся!!",
L"404 Охваченный Страстью",
L"405 Амбиции Заххара",
L"406 Худший Случай",
L"407 Тёплые Чувства",
L"408 Сердца в Лад",
L"409 Обед в Башне Панды",
L"410 Девушка Механизмов",
L"411 Девушка Судьбы",
L"412 Помоги Алвен",
L"413 Рагна в Отчаянии",
L"414 Возложенная Миссия",
L"415 Незаменимая Повседневность",
L"416 Обещание Встречи",
L"417 Стоя под Ночным Небом",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Заставка",
L"★Финал"
};

TCHAR tiz2_de[][128] = {
L"000 Neue Grenze endlosen Abenteuers",
L"001 Legende von Granvalen",
L"002 Unsere Zukunft Opening Version",
L"003 ZWEI II End Credit",
L"004 Auch wenn erschöpft...",
L"006 Magischer Krieg erneut...",
L"007 Hilf Alwen Rushing in Version",
L"008 Ende des Schicksals",
L"100 Schwebende Insel Ilbard",
L"101 Stadt Artte",
L"102 Flugplatz Artte",
L"103 Brande-Hügel",
L"104 Roalta-Dorf",
L"105 Sternfall-Dorf",
L"106 Kristalltal",
L"108 Hexe Lalaile",
L"109 Maskierter Superheld Galland",
L"200 Verlassene Mine Secondum",
L"201 Ordium-Tempel",
L"202 Wald aus Gold und Dunkelheit",
L"203 Großer Eisenturm Aulon",
L"205 Tanz in der dunklen Nacht",
L"206 Schloss Moonbria",
L"207 Gefängnis der Ekstase",
L"208 Gebet an Espina",
L"209 Sternengipfel",
L"210 Triff deine Entscheidung",
L"211 Mondwelt Luna=Mundus",
L"212 Spiral-Festung Mercedec",
L"300 Überlass es Ragna",
L"301 Brüll! Anchor Gear!!",
L"304 Kraft des Ahnen",
L"305 Beuge dich vor mir",
L"306 Für meinen Herrn",
L"307 Setz alles auf diesen Moment",
L"308 Durchbreche die Hindernisse",
L"400 Dog Fight!!",
L"401 Unheilvolle Atmosphäre",
L"402 Mont Blancs Thema",
L"403 Lass uns trainieren!!",
L"404 Von Leidenschaft getrieben",
L"405 Zahhars Ambition",
L"406 Schlimmster Fall",
L"407 Warme Gefühle",
L"408 Herzen im Einklang",
L"409 Essen im Panda-Turm",
L"410 Mädchen der Mechanik",
L"411 Mädchen des Schicksals",
L"412 Hilf Alwen",
L"413 Ragna in Verzweiflung",
L"414 Aufgetragene Mission",
L"415 Unersetzlicher Alltag",
L"416 Versprechen, sich wiederzusehen",
L"417 Im Sternenhimmel stehend",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Vorspann",
L"★Abspann"
};

TCHAR tiz2_pt[][128] = {
L"000 Nova Fronteira de Aventura Infinita",
L"001 Lenda de Granvalen",
L"002 Nosso Futuro Opening Version",
L"003 ZWEI II End Credit",
L"004 Mesmo Exausto...",
L"006 Guerra Mágica Novamente...",
L"007 Ajude Alwen Rushing in Version",
L"008 Fim do Destino",
L"100 Ilha Flutuante Ilbard",
L"101 Cidade de Artte",
L"102 Aeródromo de Artte",
L"103 Colina de Brande",
L"104 Vila de Roalta",
L"105 Vila da Chuva de Estrelas",
L"106 Vale de Cristal",
L"108 Bruxa Lalaile",
L"109 Super-Homem Mascarado Galland",
L"200 Mina Abandonada Secondum",
L"201 Templo de Ordium",
L"202 Floresta de Ouro e Trevas",
L"203 Grande Torre de Ferro de Aulon",
L"205 Dança na Noite Escura",
L"206 Castelo de Moonbria",
L"207 Prisão de Êxtase",
L"208 Oração a Espina",
L"209 Pico Estelar",
L"210 Decida",
L"211 Mundo Lunar Luna=Mundus",
L"212 Fortaleza Espiral Mercedec",
L"300 Deixe com Ragna",
L"301 Ruja! Anchor Gear!!",
L"304 Poder do Ancestral",
L"305 Curve-se Ante Mim",
L"306 Por Meu Senhor",
L"307 Aposte Tudo Neste Momento",
L"308 Atravesse os Obstáculos",
L"400 Dog Fight!!",
L"401 Ar Ominoso",
L"402 Tema de Mont Blanc",
L"403 Vamos Exercitar!!",
L"404 Impulsionado pela Paixão",
L"405 Ambição de Zahhar",
L"406 Pior Caso",
L"407 Sentimentos Calorosos",
L"408 Corações em Sintonia",
L"409 Jantar na Torre Panda",
L"410 Garota de Mecanismos",
L"411 Garota do Destino",
L"412 Ajude Alwen",
L"413 Ragna em Desespero",
L"414 Missão Atribuída",
L"415 Vida Cotidiana Insubstituível",
L"416 Promessa de Reencontro",
L"417 Em Pé no Céu Noturno",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Abertura",
L"★Encerramento"
};

TCHAR tiz2_nl[][128] = {
L"000 Nieuwe Grens van Eindeloos Avontuur",
L"001 Legende van Granvalen",
L"002 Onze Toekomst Opening Version",
L"003 ZWEI II End Credit",
L"004 Zelfs Wanneer Uitgeput...",
L"006 Magische Oorlog Opnieuw...",
L"007 Help Alwen Rushing in Version",
L"008 Einde van Lotsbestemming",
L"100 Zwevend Eiland Ilbard",
L"101 Stad Artte",
L"102 Vliegveld Artte",
L"103 Brande Heuvel",
L"104 Roalta Dorp",
L"105 Sterrenregen Dorp",
L"106 Kristalvallei",
L"108 Heks Lalaile",
L"109 Gemaskerde Superheld Galland",
L"200 Verlaten Mijn Secondum",
L"201 Ordium Tempel",
L"202 Bos van Goud en Duisternis",
L"203 Grote IJzeren Toren Aulon",
L"205 Dans in de Donkere Nacht",
L"206 Kasteel Moonbria",
L"207 Gevangenis van Extase",
L"208 Gebed aan Espina",
L"209 Sterrenpiek",
L"210 Neem je Beslissing",
L"211 Maanwereld Luna=Mundus",
L"212 Spiraal Fort Mercedec",
L"300 Laat aan Ragna",
L"301 Brul! Anchor Gear!!",
L"304 Kracht van de Voorouder",
L"305 Buig voor Mij",
L"306 Voor Mijn Heer",
L"307 Zet Alles In op Dit Moment",
L"308 Breek Door de Obstakels",
L"400 Dog Fight!!",
L"401 Onheilspellende Sfeer",
L"402 Thema van Mont Blanc",
L"403 Laten we Oefenen!!",
L"404 Gedreven door Passie",
L"405 Zahhars Ambitie",
L"406 Ergste Scenario",
L"407 Warme Gevoelens",
L"408 Harten in Harmonie",
L"409 Diner in Panda Toren",
L"410 Meisje van Mechanieken",
L"411 Meisje van Lotsbestemming",
L"412 Help Alwen",
L"413 Ragna in Wanhoop",
L"414 Toegewezen Missie",
L"415 Onvervangbaar Dagelijks Leven",
L"416 Belofte van Hereniging",
L"417 Staand in de Nachtelijke Hemel",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Opening",
L"★Einde"
};

TCHAR tiz2_pl[][128] = {
L"000 Nowa Granica Niekończącej Się Przygody",
L"001 Legenda Granvalen",
L"002 Nasza Przyszłość Opening Version",
L"003 ZWEI II End Credit",
L"004 Nawet Gdy Wyczerpany...",
L"006 Znowu Wojna Magiczna...",
L"007 Pomóż Alwen Rushing in Version",
L"008 Koniec Losu",
L"100 Unosząca Się Wyspa Ilbard",
L"101 Miasto Artte",
L"102 Lotnisko Artte",
L"103 Wzgórze Brande",
L"104 Wioska Roalta",
L"105 Wioska Spadających Gwiazd",
L"106 Dolina Kryształowa",
L"108 Wiedźma Lalaile",
L"109 Zamaskowany Superman Galland",
L"200 Opuszczona Kopalnia Secondum",
L"201 Świątynia Ordium",
L"202 Las Złota i Ciemności",
L"203 Wielka Żelazna Wieża Aulona",
L"205 Taniec w Ciemną Noc",
L"206 Zamek Moonbria",
L"207 Więzienie Ekstazy",
L"208 Modlitwa do Espiny",
L"209 Gwiazdowy Szczyt",
L"210 Podejmij Decyzję",
L"211 Księżycowy Świat Luna=Mundus",
L"212 Spiralna Twierdza Mercedec",
L"300 Zostaw Ragnie",
L"301 Rycz! Anchor Gear!!",
L"304 Moc Przodka",
L"305 Ukłoń Się Przede Mną",
L"306 Dla Mego Pana",
L"307 Postaw Wszystko na Tę Chwilę",
L"308 Przełam Przeszkody",
L"400 Dog Fight!!",
L"401 Złowieszcza Atmosfera",
L"402 Motyw Mont Blanc",
L"403 Ćwiczmy!!",
L"404 Pędzony Namiętnością",
L"405 Ambicje Zahhara",
L"406 Najgorszy Przypadek",
L"407 Ciepłe Uczucia",
L"408 Serca w Harmonii",
L"409 Obiad w Wieży Pandy",
L"410 Dziewczyna Mechanizmów",
L"411 Dziewczyna Losu",
L"412 Pomóż Alwen",
L"413 Ragna w Rozpaczy",
L"414 Powierzona Misja",
L"415 Niezastąpione Codzienne Życie",
L"416 Obietnica Ponownego Spotkania",
L"417 Stojąc pod Gwieździstym Niebem",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Opening",
L"★Zakończenie"
};

TCHAR tiz2_tr[][128] = {
L"000 Sonsuz Maceranın Yeni Ufukları",
L"001 Granvalen Efsanesi",
L"002 Bizim Geleceğimiz Opening Version",
L"003 ZWEI II End Credit",
L"004 Yorgun Düşünce Bile...",
L"006 Sihir Savaşı Yeniden...",
L"007 Yardım Et Alwen Rushing in Version",
L"008 Kaderin Sonu",
L"100 Yüzen Ada Ilbard",
L"101 Artte Kasabası",
L"102 Artte Havaalanı",
L"103 Brande Tepesi",
L"104 Roalta Köyü",
L"105 Yıldız Yağmuru Köyü",
L"106 Kristal Vadisi",
L"108 Cadı Lalaile",
L"109 Maskeli Süpermen Galland",
L"200 Secondum Terk Edilmiş Maden",
L"201 Ordium Tapınağı",
L"202 Altın ve Karanlık Ormanı",
L"203 Aulon Büyük Demir Kulesi",
L"205 Karanlık Gecede Dans",
L"206 Moonbria Kalesi",
L"207 Coşku Hapishanesi",
L"208 Espina'ya Dua",
L"209 Yıldız Zirvesi",
L"210 Karar Ver",
L"211 Ay Dünyası Luna=Mundus",
L"212 Sarmal Kale Mercedec",
L"300 Ragna'ya Bırak",
L"301 Kükremek! Anchor Gear!!",
L"304 Ata'nın Gücü",
L"305 Önümde Eğil",
L"306 Efendim İçin",
L"307 Her Şeyi Bu Ana Yatır",
L"308 Engelleri Aş",
L"400 Dog Fight!!",
L"401 Uğursuz Hava",
L"402 Mont Blanc'ın Teması",
L"403 Hadi Egzersiz!!",
L"404 Tutkuyla Sürüklenen",
L"405 Zahhar'ın Hırsı",
L"406 En Kötü Durum",
L"407 Sıcak Duygular",
L"408 Uyumlu Kalpler",
L"409 Panda Kulesi'nde Yemek",
L"410 Makine Kızı",
L"411 Kader Kızı",
L"412 Yardım Et Alwen",
L"413 Umutsuz Ragna",
L"414 Verilen Görev",
L"415 Paha Biçilmez Günlük Hayat",
L"416 Tekrar Buluşma Sözü",
L"417 Gece Göğünde Dururken",
L"500 Music Ys Felghana(Boy with Wings)",
L"501 Music Ys Felghana(Barestayn Castle)",
L"502 Music Ys Origin(BEYOND THE BEGINNING)",
L"503 Music Ys Origin(WATER PRISON)",
L"504 Music Zwei!!(Song of Flowers and Wind -arrange-)",
L"505 Music Zwei!!(Phantom Land Serpentina)",
L"506 Music Sora no Kiseki FC(Vacant Land of Light)",
L"507 Music Sora no Kiseki SC(The Fate of The Fairies)",
L"508 Music Sora no Kiseki The3rd(Overdosing Heavenly Bliss)",
L"509 Music Gurumin(Incredible Ghost Egg)",
L"510 Music Gurumin(TO MAKE THE END OF DIGING)",
L"★Giriş",
L"★Bitiş"
};

static inline CString ZWEIIITrack(int i) {
	switch (savedata.lang) {
	case 0: return CString(tiz2[i]);
	case 1: return CString(tiz2_en[i]);
	case 2: return CString(tiz2_fr[i]);
	case 3: return CString(tiz2_it[i]);
	case 4: return CString(tiz2_es[i]);
	case 5: return CString(tiz2_ko[i]);
	case 6: return CString(tiz2_zh[i]);
	case 7: return CString(tiz2_ar[i]);
	case 8: return CString(tiz2_ru[i]);
	case 9: return CString(tiz2_de[i]);
	case 10: return CString(tiz2_pt[i]);
	case 11: return CString(tiz2_nl[i]);
	case 12: return CString(tiz2_pl[i]);
	case 13: return CString(tiz2_tr[i]);
	default: return CString(tiz2_en[i]);
	}
}

CString CZWEIII::Gett(int a) {
	CString s, ss;
	s = ZWEIIITrack(a);
	ss = s.Left(3);
	fnn = s.Mid(4);
	return ss;
}

/////////////////////////////////////////////////////////////////////////////
// CZWEIII メッセージ ハンドラ
void CZWEIII::OnDblclkList1()
{
	// TODO: この位置にコントロール通知ハンドラ用のコードを追加してください
	int idx = m_list.GetItemData(m_list.GetCurSel());
	CString s;	s = ZWEIIITrack(idx);
	ret = _tstoi(s.Left(4));
	ret2 = m_list.GetCurSel();
	if (ret2 > 65)
		ret = ret2;
#if UNICODE
	if (s.Left(1) == "★") {
		fnn = s.Mid(1);
#else
	if (s.Left(2) == "★") {
		fnn = s.Mid(2);
#endif
	}
	else {
		fnn = s.Mid(4);
	}
	EndDialog(1567);
	}

BOOL CZWEIII::OnInitDialog()
{
	CCustomBlurDialogBase::OnInitDialog();
	SetWindowText(L"ZWEI II");
	SetDlgItemText(IDOK, LL14(L"閉じる", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close", L"Close"));

	// TODO: この位置に初期化の補足処理を追加してください
	int dx;
	for (int i = 0; i < 67; i++)
	{
		CString s = ZWEIIITrack(i);
		if (s.Left(2) != _T("★")) { CString t = _T("ZW2_"); t += s; s = t; }
		dx = m_list.AddString(s);
		m_list.SetItemData(dx, i);
	}

	m_list.SetCurSel(0);
	if (ret != 0)
		//		if(ret>65) m_list.SetCurSel(ret);
		//		else m_list.SetCurSel(ret-1);
		m_list.SetCurSel(ret);
	m_list.SetFocus();
	return FALSE;  // コントロールにフォーカスを設定しないとき、戻り値は TRUE となります
	// 例外: OCX プロパティ ページの戻り値は FALSE となります
}
